import type { RegisteredNotificationTemplate } from "../shared/registry/types";
import { NOTIFICATION_TEMPLATE_IDS as IDS } from "../shared/registry/ids";
import { extractAllowedVariables } from "../shared/registry/variables";
import { DEFAULT_DEEP_LINK } from "../shared/registry/legacy-map";

function daysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

function tpl(
  partial: Omit<RegisteredNotificationTemplate, "allowedVariables" | "deepLink"> & {
    allowedVariables?: readonly string[];
    deepLink?: string;
  },
): RegisteredNotificationTemplate {
  return {
    ...partial,
    allowedVariables:
      partial.allowedVariables ?? extractAllowedVariables(partial.title, partial.message),
    deepLink: partial.deepLink ?? DEFAULT_DEEP_LINK[partial.category],
  };
}

export const ADMISSIONS_TEMPLATES: RegisteredNotificationTemplate[] = [
  tpl({
    templateId: IDS.admissions.parent.applicationSubmitted,
    category: "admissions",
    audience: "parent",
    title: "Application submitted",
    message: "{{applicationId}} for {{studentName}} received.",
    priority: "normal",
    status: "published",
    version: "2.4.0",
    description: "Confirm admission application receipt to parents.",
    whereUsed: ["Admin Admissions", "Connect parent"],
    updatedAt: daysAgo(16),
  }),
  tpl({
    templateId: IDS.admissions.parent.parentConfirmationRequired,
    category: "admissions",
    audience: "parent",
    title: "Parent confirmation required",
    message: "{{applicationId}} is ready. Please continue or reject within {{days}} days.",
    priority: "important",
    status: "published",
    version: "2.4.0",
    description: "Ask parent to confirm or reject an offer.",
    whereUsed: ["Admin Admissions", "Connect parent"],
    updatedAt: daysAgo(16),
  }),
  tpl({
    templateId: IDS.admissions.parent.applicationApproved,
    category: "admissions",
    audience: "parent",
    title: "Application approved",
    message: "{{applicationId}} has been approved after parent confirmation.",
    priority: "success",
    status: "published",
    version: "2.4.0",
    whereUsed: ["Admin Admissions", "Connect parent"],
    updatedAt: daysAgo(16),
  }),
  tpl({
    templateId: IDS.admissions.parent.applicationClosed,
    category: "admissions",
    audience: "parent",
    title: "Application closed",
    message: "{{applicationId}} has been closed based on parent rejection.",
    priority: "normal",
    status: "published",
    version: "2.4.0",
    whereUsed: ["Admin Admissions", "Connect parent"],
    updatedAt: daysAgo(16),
  }),
  tpl({
    templateId: IDS.admissions.parent.waitlistJoined,
    category: "admissions",
    audience: "parent",
    title: "Added to waitlist",
    message: "{{applicationId}} joined waitlist for up to {{days}} days.",
    priority: "normal",
    status: "published",
    version: "2.4.0",
    whereUsed: ["Admin Admissions", "Connect parent"],
    updatedAt: daysAgo(16),
  }),
  tpl({
    templateId: IDS.admissions.parent.waitlistDay80Reminder,
    category: "admissions",
    audience: "parent",
    title: "Waitlist reminder",
    message: "{{applicationId}} is on day {{day}} of the 90-day waitlist. 10 days remain.",
    priority: "important",
    status: "published",
    version: "2.4.0",
    whereUsed: ["Admin Admissions", "Connect parent"],
    updatedAt: daysAgo(16),
  }),
  tpl({
    templateId: IDS.admissions.parent.waitlistReminderSent,
    category: "admissions",
    audience: "parent",
    title: "Institute reminder sent",
    message: "{{applicationId}} moved to top of the institute waitlist and marked active.",
    priority: "normal",
    status: "published",
    version: "2.4.0",
    whereUsed: ["Admin Admissions", "Connect parent"],
    updatedAt: daysAgo(16),
  }),
  tpl({
    templateId: IDS.admissions.parent.waitlistRemoved,
    category: "admissions",
    audience: "parent",
    title: "Removed from waitlist",
    message: "{{applicationId}} was removed from waitlist.",
    priority: "normal",
    status: "published",
    version: "2.4.0",
    whereUsed: ["Admin Admissions", "Connect parent"],
    updatedAt: daysAgo(16),
  }),
  tpl({
    templateId: IDS.admissions.parent.waitlistAutoRemoved,
    category: "admissions",
    audience: "parent",
    title: "Removed from waitlist",
    message:
      "{{applicationId}} reached the {{limitDays}}-day waitlist limit and was removed automatically.",
    priority: "important",
    status: "published",
    version: "2.4.0",
    whereUsed: ["Admin Admissions", "Connect parent"],
    updatedAt: daysAgo(16),
  }),
  tpl({
    templateId: IDS.admissions.parent.seatsAvailable,
    category: "admissions",
    audience: "parent",
    title: "Seats are now available",
    message: "{{applicationId}}: Seats opened up. You can continue with admission.",
    priority: "important",
    status: "published",
    version: "2.4.0",
    whereUsed: ["Admin Admissions", "Connect parent"],
    updatedAt: daysAgo(16),
  }),
  tpl({
    templateId: IDS.admissions.parent.correctionRequested,
    category: "admissions",
    audience: "parent",
    title: "Correction requested",
    message: "{{applicationId}}: {{reason}}. Please edit the requested fields and resubmit.",
    priority: "important",
    status: "published",
    version: "2.4.0",
    whereUsed: ["Admin Admissions", "Connect parent"],
    updatedAt: daysAgo(16),
  }),
  tpl({
    templateId: IDS.admissions.parent.correctionsSubmitted,
    category: "admissions",
    audience: "parent",
    title: "Corrections submitted",
    message: "{{applicationId}} has been moved back to review.",
    priority: "normal",
    status: "published",
    version: "2.4.0",
    whereUsed: ["Admin Admissions", "Connect parent"],
    updatedAt: daysAgo(16),
  }),
  tpl({
    templateId: IDS.admissions.parent.confirmationReminderMorning,
    category: "admissions",
    audience: "parent",
    title: "Morning reminder",
    message: "{{applicationId}}: Please respond in {{remainingDays}} day(s) (morning reminder).",
    priority: "important",
    status: "published",
    version: "2.4.0",
    whereUsed: ["Admin Admissions", "Connect parent"],
    updatedAt: daysAgo(16),
  }),
  tpl({
    templateId: IDS.admissions.parent.confirmationReminderEvening,
    category: "admissions",
    audience: "parent",
    title: "Evening reminder",
    message: "{{applicationId}}: Please respond in {{remainingDays}} day(s) (evening reminder).",
    priority: "important",
    status: "published",
    version: "2.4.0",
    whereUsed: ["Admin Admissions", "Connect parent"],
    updatedAt: daysAgo(16),
  }),
  tpl({
    templateId: IDS.admissions.parent.statusUpdate,
    category: "admissions",
    audience: "parent",
    title: "Application status update",
    message: "{{applicationId}} for {{studentName}} is now {{statusLabel}}.",
    priority: "normal",
    status: "published",
    version: "1.0.0",
    deepLink: "/admissions/applications",
    whereUsed: ["Admin Admissions", "Connect Admissions"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.admissions.parent.interviewScheduled,
    category: "admissions",
    audience: "parent",
    title: "Interview / test scheduled",
    message: "{{applicationId}} for {{studentName}}: {{detail}}.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/admissions/applications",
    whereUsed: ["Admin Admissions", "Connect Admissions"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.admissions.parent.selected,
    category: "admissions",
    audience: "parent",
    title: "Selected for admission",
    message: "{{applicationId}} for {{studentName}} has been selected.",
    priority: "success",
    status: "published",
    version: "1.0.0",
    deepLink: "/admissions/applications",
    whereUsed: ["Admin Admissions", "Connect Admissions"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.admissions.parent.rejected,
    category: "admissions",
    audience: "parent",
    title: "Application not selected",
    message: "{{applicationId}} for {{studentName}} was not selected{{reasonSuffix}}.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/admissions/applications",
    whereUsed: ["Admin Admissions", "Connect Admissions"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.admissions.parent.admissionCompleted,
    category: "admissions",
    audience: "parent",
    title: "Admission completed",
    message: "{{applicationId}} for {{studentName}} is complete. Welcome to {{instituteName}}.",
    priority: "success",
    status: "published",
    version: "1.0.0",
    deepLink: "/admissions/applications",
    whereUsed: ["Admin Admissions", "Connect Admissions"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.admissions.parent.missingInformation,
    category: "admissions",
    audience: "parent",
    title: "Missing information / document",
    message: "{{applicationId}}: {{reason}}. Please provide the requested details.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/admissions/applications",
    whereUsed: ["Admin Admissions", "Connect Admissions"],
    updatedAt: daysAgo(1),
  }),
];
