/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTermsRouteImport } from './routes/_app/terms'
import { Route as AppSignupRouteImport } from './routes/_app/signup'
import { Route as AppSetupFromAdminRouteImport } from './routes/_app/setup-from-admin'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSavedRouteImport } from './routes/_app/saved'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPrivacyRouteImport } from './routes/_app/privacy'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppInterviewsRouteImport } from './routes/_app/interviews'
import { Route as AppForgotPasswordRouteImport } from './routes/_app/forgot-password'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppApplyRouteImport } from './routes/_app/apply'
import { Route as AppApplicationsRouteImport } from './routes/_app/applications'
import { Route as AppRecruiterIndexRouteImport } from './routes/_app/recruiter/index'
import { Route as AppJobsIndexRouteImport } from './routes/_app/jobs/index'
import { Route as AppInstitutesIndexRouteImport } from './routes/_app/institutes/index'
import { Route as AppRecruiterTalentRouteImport } from './routes/_app/recruiter/talent'
import { Route as AppRecruiterApplicantsRouteImport } from './routes/_app/recruiter/applicants'
import { Route as AppJobsJobIdRouteImport } from './routes/_app/jobs/$jobId'
import { Route as AppInstitutesInstituteIdRouteImport } from './routes/_app/institutes/$instituteId'
import { Route as AppApplicationsApplicationIdRouteImport } from './routes/_app/applications/$applicationId'
import { Route as AppRecruiterJobsIndexRouteImport } from './routes/_app/recruiter/jobs/index'
import { Route as AppRecruiterJobsNewRouteImport } from './routes/_app/recruiter/jobs/new'
import { Route as AppRecruiterJobsJobIdEditRouteImport } from './routes/_app/recruiter/jobs/$jobId/edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTermsRoute = AppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppRoute,
} as any)
const AppSignupRoute = AppSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupFromAdminRoute = AppSetupFromAdminRouteImport.update({
  id: '/setup-from-admin',
  path: '/setup-from-admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsRoute = AppInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AppRoute,
} as any)
const AppForgotPasswordRoute = AppForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppApplyRoute = AppApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruiterIndexRoute = AppRecruiterIndexRouteImport.update({
  id: '/recruiter/',
  path: '/recruiter/',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const AppInstitutesIndexRoute = AppInstitutesIndexRouteImport.update({
  id: '/institutes/',
  path: '/institutes/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruiterTalentRoute = AppRecruiterTalentRouteImport.update({
  id: '/recruiter/talent',
  path: '/recruiter/talent',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruiterApplicantsRoute = AppRecruiterApplicantsRouteImport.update({
  id: '/recruiter/applicants',
  path: '/recruiter/applicants',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsJobIdRoute = AppJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AppRoute,
} as any)
const AppInstitutesInstituteIdRoute =
  AppInstitutesInstituteIdRouteImport.update({
    id: '/institutes/$instituteId',
    path: '/institutes/$instituteId',
    getParentRoute: () => AppRoute,
  } as any)
const AppApplicationsApplicationIdRoute =
  AppApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AppApplicationsRoute,
  } as any)
const AppRecruiterJobsIndexRoute = AppRecruiterJobsIndexRouteImport.update({
  id: '/recruiter/jobs/',
  path: '/recruiter/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruiterJobsNewRoute = AppRecruiterJobsNewRouteImport.update({
  id: '/recruiter/jobs/new',
  path: '/recruiter/jobs/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruiterJobsJobIdEditRoute =
  AppRecruiterJobsJobIdEditRouteImport.update({
    id: '/recruiter/jobs/$jobId/edit',
    path: '/recruiter/jobs/$jobId/edit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/applications': typeof AppApplicationsRouteWithChildren
  '/apply': typeof AppApplyRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/forgot-password': typeof AppForgotPasswordRoute
  '/interviews': typeof AppInterviewsRoute
  '/login': typeof AppLoginRoute
  '/notifications': typeof AppNotificationsRoute
  '/privacy': typeof AppPrivacyRoute
  '/profile': typeof AppProfileRoute
  '/saved': typeof AppSavedRoute
  '/settings': typeof AppSettingsRoute
  '/setup-from-admin': typeof AppSetupFromAdminRoute
  '/signup': typeof AppSignupRoute
  '/terms': typeof AppTermsRoute
  '/applications/$applicationId': typeof AppApplicationsApplicationIdRoute
  '/institutes/$instituteId': typeof AppInstitutesInstituteIdRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/recruiter/applicants': typeof AppRecruiterApplicantsRoute
  '/recruiter/talent': typeof AppRecruiterTalentRoute
  '/institutes/': typeof AppInstitutesIndexRoute
  '/jobs/': typeof AppJobsIndexRoute
  '/recruiter/': typeof AppRecruiterIndexRoute
  '/recruiter/jobs/new': typeof AppRecruiterJobsNewRoute
  '/recruiter/jobs/': typeof AppRecruiterJobsIndexRoute
  '/recruiter/jobs/$jobId/edit': typeof AppRecruiterJobsJobIdEditRoute
}
export interface FileRoutesByTo {
  '/applications': typeof AppApplicationsRouteWithChildren
  '/apply': typeof AppApplyRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/forgot-password': typeof AppForgotPasswordRoute
  '/interviews': typeof AppInterviewsRoute
  '/login': typeof AppLoginRoute
  '/notifications': typeof AppNotificationsRoute
  '/privacy': typeof AppPrivacyRoute
  '/profile': typeof AppProfileRoute
  '/saved': typeof AppSavedRoute
  '/settings': typeof AppSettingsRoute
  '/setup-from-admin': typeof AppSetupFromAdminRoute
  '/signup': typeof AppSignupRoute
  '/terms': typeof AppTermsRoute
  '/': typeof AppIndexRoute
  '/applications/$applicationId': typeof AppApplicationsApplicationIdRoute
  '/institutes/$instituteId': typeof AppInstitutesInstituteIdRoute
  '/jobs/$jobId': typeof AppJobsJobIdRoute
  '/recruiter/applicants': typeof AppRecruiterApplicantsRoute
  '/recruiter/talent': typeof AppRecruiterTalentRoute
  '/institutes': typeof AppInstitutesIndexRoute
  '/jobs': typeof AppJobsIndexRoute
  '/recruiter': typeof AppRecruiterIndexRoute
  '/recruiter/jobs/new': typeof AppRecruiterJobsNewRoute
  '/recruiter/jobs': typeof AppRecruiterJobsIndexRoute
  '/recruiter/jobs/$jobId/edit': typeof AppRecruiterJobsJobIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/applications': typeof AppApplicationsRouteWithChildren
  '/_app/apply': typeof AppApplyRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/forgot-password': typeof AppForgotPasswordRoute
  '/_app/interviews': typeof AppInterviewsRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/saved': typeof AppSavedRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/setup-from-admin': typeof AppSetupFromAdminRoute
  '/_app/signup': typeof AppSignupRoute
  '/_app/terms': typeof AppTermsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/applications/$applicationId': typeof AppApplicationsApplicationIdRoute
  '/_app/institutes/$instituteId': typeof AppInstitutesInstituteIdRoute
  '/_app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/_app/recruiter/applicants': typeof AppRecruiterApplicantsRoute
  '/_app/recruiter/talent': typeof AppRecruiterTalentRoute
  '/_app/institutes/': typeof AppInstitutesIndexRoute
  '/_app/jobs/': typeof AppJobsIndexRoute
  '/_app/recruiter/': typeof AppRecruiterIndexRoute
  '/_app/recruiter/jobs/new': typeof AppRecruiterJobsNewRoute
  '/_app/recruiter/jobs/': typeof AppRecruiterJobsIndexRoute
  '/_app/recruiter/jobs/$jobId/edit': typeof AppRecruiterJobsJobIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/apply'
    | '/dashboard'
    | '/documents'
    | '/forgot-password'
    | '/interviews'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/saved'
    | '/settings'
    | '/setup-from-admin'
    | '/signup'
    | '/terms'
    | '/applications/$applicationId'
    | '/institutes/$instituteId'
    | '/jobs/$jobId'
    | '/recruiter/applicants'
    | '/recruiter/talent'
    | '/institutes/'
    | '/jobs/'
    | '/recruiter/'
    | '/recruiter/jobs/new'
    | '/recruiter/jobs/'
    | '/recruiter/jobs/$jobId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/applications'
    | '/apply'
    | '/dashboard'
    | '/documents'
    | '/forgot-password'
    | '/interviews'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/saved'
    | '/settings'
    | '/setup-from-admin'
    | '/signup'
    | '/terms'
    | '/'
    | '/applications/$applicationId'
    | '/institutes/$instituteId'
    | '/jobs/$jobId'
    | '/recruiter/applicants'
    | '/recruiter/talent'
    | '/institutes'
    | '/jobs'
    | '/recruiter'
    | '/recruiter/jobs/new'
    | '/recruiter/jobs'
    | '/recruiter/jobs/$jobId/edit'
  id:
    | '__root__'
    | '/_app'
    | '/_app/applications'
    | '/_app/apply'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/forgot-password'
    | '/_app/interviews'
    | '/_app/login'
    | '/_app/notifications'
    | '/_app/privacy'
    | '/_app/profile'
    | '/_app/saved'
    | '/_app/settings'
    | '/_app/setup-from-admin'
    | '/_app/signup'
    | '/_app/terms'
    | '/_app/'
    | '/_app/applications/$applicationId'
    | '/_app/institutes/$instituteId'
    | '/_app/jobs/$jobId'
    | '/_app/recruiter/applicants'
    | '/_app/recruiter/talent'
    | '/_app/institutes/'
    | '/_app/jobs/'
    | '/_app/recruiter/'
    | '/_app/recruiter/jobs/new'
    | '/_app/recruiter/jobs/'
    | '/_app/recruiter/jobs/$jobId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terms': {
      id: '/_app/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AppTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signup': {
      id: '/_app/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AppSignupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup-from-admin': {
      id: '/_app/setup-from-admin'
      path: '/setup-from-admin'
      fullPath: '/setup-from-admin'
      preLoaderRoute: typeof AppSetupFromAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interviews': {
      id: '/_app/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof AppInterviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forgot-password': {
      id: '/_app/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AppForgotPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apply': {
      id: '/_app/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof AppApplyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications': {
      id: '/_app/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruiter/': {
      id: '/_app/recruiter/'
      path: '/recruiter'
      fullPath: '/recruiter/'
      preLoaderRoute: typeof AppRecruiterIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/': {
      id: '/_app/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/institutes/': {
      id: '/_app/institutes/'
      path: '/institutes'
      fullPath: '/institutes/'
      preLoaderRoute: typeof AppInstitutesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruiter/talent': {
      id: '/_app/recruiter/talent'
      path: '/recruiter/talent'
      fullPath: '/recruiter/talent'
      preLoaderRoute: typeof AppRecruiterTalentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruiter/applicants': {
      id: '/_app/recruiter/applicants'
      path: '/recruiter/applicants'
      fullPath: '/recruiter/applicants'
      preLoaderRoute: typeof AppRecruiterApplicantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/$jobId': {
      id: '/_app/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AppJobsJobIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/institutes/$instituteId': {
      id: '/_app/institutes/$instituteId'
      path: '/institutes/$instituteId'
      fullPath: '/institutes/$instituteId'
      preLoaderRoute: typeof AppInstitutesInstituteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications/$applicationId': {
      id: '/_app/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof AppApplicationsApplicationIdRouteImport
      parentRoute: typeof AppApplicationsRoute
    }
    '/_app/recruiter/jobs/': {
      id: '/_app/recruiter/jobs/'
      path: '/recruiter/jobs'
      fullPath: '/recruiter/jobs/'
      preLoaderRoute: typeof AppRecruiterJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruiter/jobs/new': {
      id: '/_app/recruiter/jobs/new'
      path: '/recruiter/jobs/new'
      fullPath: '/recruiter/jobs/new'
      preLoaderRoute: typeof AppRecruiterJobsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruiter/jobs/$jobId/edit': {
      id: '/_app/recruiter/jobs/$jobId/edit'
      path: '/recruiter/jobs/$jobId/edit'
      fullPath: '/recruiter/jobs/$jobId/edit'
      preLoaderRoute: typeof AppRecruiterJobsJobIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppApplicationsRouteChildren {
  AppApplicationsApplicationIdRoute: typeof AppApplicationsApplicationIdRoute
}

const AppApplicationsRouteChildren: AppApplicationsRouteChildren = {
  AppApplicationsApplicationIdRoute: AppApplicationsApplicationIdRoute,
}

const AppApplicationsRouteWithChildren = AppApplicationsRoute._addFileChildren(
  AppApplicationsRouteChildren,
)

interface AppRouteChildren {
  AppApplicationsRoute: typeof AppApplicationsRouteWithChildren
  AppApplyRoute: typeof AppApplyRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppForgotPasswordRoute: typeof AppForgotPasswordRoute
  AppInterviewsRoute: typeof AppInterviewsRoute
  AppLoginRoute: typeof AppLoginRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSavedRoute: typeof AppSavedRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSetupFromAdminRoute: typeof AppSetupFromAdminRoute
  AppSignupRoute: typeof AppSignupRoute
  AppTermsRoute: typeof AppTermsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInstitutesInstituteIdRoute: typeof AppInstitutesInstituteIdRoute
  AppJobsJobIdRoute: typeof AppJobsJobIdRoute
  AppRecruiterApplicantsRoute: typeof AppRecruiterApplicantsRoute
  AppRecruiterTalentRoute: typeof AppRecruiterTalentRoute
  AppInstitutesIndexRoute: typeof AppInstitutesIndexRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
  AppRecruiterIndexRoute: typeof AppRecruiterIndexRoute
  AppRecruiterJobsNewRoute: typeof AppRecruiterJobsNewRoute
  AppRecruiterJobsIndexRoute: typeof AppRecruiterJobsIndexRoute
  AppRecruiterJobsJobIdEditRoute: typeof AppRecruiterJobsJobIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApplicationsRoute: AppApplicationsRouteWithChildren,
  AppApplyRoute: AppApplyRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppForgotPasswordRoute: AppForgotPasswordRoute,
  AppInterviewsRoute: AppInterviewsRoute,
  AppLoginRoute: AppLoginRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppProfileRoute: AppProfileRoute,
  AppSavedRoute: AppSavedRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSetupFromAdminRoute: AppSetupFromAdminRoute,
  AppSignupRoute: AppSignupRoute,
  AppTermsRoute: AppTermsRoute,
  AppIndexRoute: AppIndexRoute,
  AppInstitutesInstituteIdRoute: AppInstitutesInstituteIdRoute,
  AppJobsJobIdRoute: AppJobsJobIdRoute,
  AppRecruiterApplicantsRoute: AppRecruiterApplicantsRoute,
  AppRecruiterTalentRoute: AppRecruiterTalentRoute,
  AppInstitutesIndexRoute: AppInstitutesIndexRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
  AppRecruiterIndexRoute: AppRecruiterIndexRoute,
  AppRecruiterJobsNewRoute: AppRecruiterJobsNewRoute,
  AppRecruiterJobsIndexRoute: AppRecruiterJobsIndexRoute,
  AppRecruiterJobsJobIdEditRoute: AppRecruiterJobsJobIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
