/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTermsRouteImport } from './routes/_app/terms'
import { Route as AppSignupRouteImport } from './routes/_app/signup'
import { Route as AppSetupFromAdminRouteImport } from './routes/_app/setup-from-admin'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProgramsRouteImport } from './routes/_app/programs'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPrivacyRouteImport } from './routes/_app/privacy'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppInstituteRouteImport } from './routes/_app/institute'
import { Route as AppInquiriesRouteImport } from './routes/_app/inquiries'
import { Route as AppForgotPasswordRouteImport } from './routes/_app/forgot-password'
import { Route as AppFaqRouteImport } from './routes/_app/faq'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCookiesRouteImport } from './routes/_app/cookies'
import { Route as AppContactRouteImport } from './routes/_app/contact'
import { Route as AppApplyRouteImport } from './routes/_app/apply'
import { Route as AppApplicationsRouteImport } from './routes/_app/applications'
import { Route as AppInstitutesIndexRouteImport } from './routes/_app/institutes/index'
import { Route as AppInstituteIndexRouteImport } from './routes/_app/institute/index'
import { Route as AppProgramsProgramIdRouteImport } from './routes/_app/programs/$programId'
import { Route as AppInstitutesInstituteIdRouteImport } from './routes/_app/institutes/$instituteId'
import { Route as AppInstituteSettingsRouteImport } from './routes/_app/institute/settings'
import { Route as AppInstituteProfileRouteImport } from './routes/_app/institute/profile'
import { Route as AppInstituteOpeningsRouteImport } from './routes/_app/institute/openings'
import { Route as AppInstituteFormRouteImport } from './routes/_app/institute/form'
import { Route as AppInstituteApplicationsRouteImport } from './routes/_app/institute/applications'
import { Route as AppApplicationsApplicationIdRouteImport } from './routes/_app/applications/$applicationId'
import { Route as AppInstituteApplicationsIndexRouteImport } from './routes/_app/institute/applications/index'
import { Route as AppInstituteApplicationsApplicationIdRouteImport } from './routes/_app/institute/applications/$applicationId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTermsRoute = AppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppRoute,
} as any)
const AppSignupRoute = AppSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupFromAdminRoute = AppSetupFromAdminRouteImport.update({
  id: '/setup-from-admin',
  path: '/setup-from-admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramsRoute = AppProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppInstituteRoute = AppInstituteRouteImport.update({
  id: '/institute',
  path: '/institute',
  getParentRoute: () => AppRoute,
} as any)
const AppInquiriesRoute = AppInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AppRoute,
} as any)
const AppForgotPasswordRoute = AppForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AppRoute,
} as any)
const AppFaqRoute = AppFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCookiesRoute = AppCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppApplyRoute = AppApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppInstitutesIndexRoute = AppInstitutesIndexRouteImport.update({
  id: '/institutes/',
  path: '/institutes/',
  getParentRoute: () => AppRoute,
} as any)
const AppInstituteIndexRoute = AppInstituteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInstituteRoute,
} as any)
const AppProgramsProgramIdRoute = AppProgramsProgramIdRouteImport.update({
  id: '/$programId',
  path: '/$programId',
  getParentRoute: () => AppProgramsRoute,
} as any)
const AppInstitutesInstituteIdRoute =
  AppInstitutesInstituteIdRouteImport.update({
    id: '/institutes/$instituteId',
    path: '/institutes/$instituteId',
    getParentRoute: () => AppRoute,
  } as any)
const AppInstituteSettingsRoute = AppInstituteSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppInstituteRoute,
} as any)
const AppInstituteProfileRoute = AppInstituteProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppInstituteRoute,
} as any)
const AppInstituteOpeningsRoute = AppInstituteOpeningsRouteImport.update({
  id: '/openings',
  path: '/openings',
  getParentRoute: () => AppInstituteRoute,
} as any)
const AppInstituteFormRoute = AppInstituteFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => AppInstituteRoute,
} as any)
const AppInstituteApplicationsRoute =
  AppInstituteApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AppInstituteRoute,
  } as any)
const AppApplicationsApplicationIdRoute =
  AppApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AppApplicationsRoute,
  } as any)
const AppInstituteApplicationsIndexRoute =
  AppInstituteApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppInstituteApplicationsRoute,
  } as any)
const AppInstituteApplicationsApplicationIdRoute =
  AppInstituteApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AppInstituteApplicationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/applications': typeof AppApplicationsRouteWithChildren
  '/apply': typeof AppApplyRoute
  '/contact': typeof AppContactRoute
  '/cookies': typeof AppCookiesRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/faq': typeof AppFaqRoute
  '/forgot-password': typeof AppForgotPasswordRoute
  '/inquiries': typeof AppInquiriesRoute
  '/institute': typeof AppInstituteRouteWithChildren
  '/login': typeof AppLoginRoute
  '/notifications': typeof AppNotificationsRoute
  '/privacy': typeof AppPrivacyRoute
  '/profile': typeof AppProfileRoute
  '/programs': typeof AppProgramsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/setup-from-admin': typeof AppSetupFromAdminRoute
  '/signup': typeof AppSignupRoute
  '/terms': typeof AppTermsRoute
  '/applications/$applicationId': typeof AppApplicationsApplicationIdRoute
  '/institute/applications': typeof AppInstituteApplicationsRouteWithChildren
  '/institute/form': typeof AppInstituteFormRoute
  '/institute/openings': typeof AppInstituteOpeningsRoute
  '/institute/profile': typeof AppInstituteProfileRoute
  '/institute/settings': typeof AppInstituteSettingsRoute
  '/institutes/$instituteId': typeof AppInstitutesInstituteIdRoute
  '/programs/$programId': typeof AppProgramsProgramIdRoute
  '/institute/': typeof AppInstituteIndexRoute
  '/institutes/': typeof AppInstitutesIndexRoute
  '/institute/applications/$applicationId': typeof AppInstituteApplicationsApplicationIdRoute
  '/institute/applications/': typeof AppInstituteApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/applications': typeof AppApplicationsRouteWithChildren
  '/apply': typeof AppApplyRoute
  '/contact': typeof AppContactRoute
  '/cookies': typeof AppCookiesRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/faq': typeof AppFaqRoute
  '/forgot-password': typeof AppForgotPasswordRoute
  '/inquiries': typeof AppInquiriesRoute
  '/login': typeof AppLoginRoute
  '/notifications': typeof AppNotificationsRoute
  '/privacy': typeof AppPrivacyRoute
  '/profile': typeof AppProfileRoute
  '/programs': typeof AppProgramsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/setup-from-admin': typeof AppSetupFromAdminRoute
  '/signup': typeof AppSignupRoute
  '/terms': typeof AppTermsRoute
  '/': typeof AppIndexRoute
  '/applications/$applicationId': typeof AppApplicationsApplicationIdRoute
  '/institute/form': typeof AppInstituteFormRoute
  '/institute/openings': typeof AppInstituteOpeningsRoute
  '/institute/profile': typeof AppInstituteProfileRoute
  '/institute/settings': typeof AppInstituteSettingsRoute
  '/institutes/$instituteId': typeof AppInstitutesInstituteIdRoute
  '/programs/$programId': typeof AppProgramsProgramIdRoute
  '/institute': typeof AppInstituteIndexRoute
  '/institutes': typeof AppInstitutesIndexRoute
  '/institute/applications/$applicationId': typeof AppInstituteApplicationsApplicationIdRoute
  '/institute/applications': typeof AppInstituteApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/applications': typeof AppApplicationsRouteWithChildren
  '/_app/apply': typeof AppApplyRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/cookies': typeof AppCookiesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/faq': typeof AppFaqRoute
  '/_app/forgot-password': typeof AppForgotPasswordRoute
  '/_app/inquiries': typeof AppInquiriesRoute
  '/_app/institute': typeof AppInstituteRouteWithChildren
  '/_app/login': typeof AppLoginRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/programs': typeof AppProgramsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/setup-from-admin': typeof AppSetupFromAdminRoute
  '/_app/signup': typeof AppSignupRoute
  '/_app/terms': typeof AppTermsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/applications/$applicationId': typeof AppApplicationsApplicationIdRoute
  '/_app/institute/applications': typeof AppInstituteApplicationsRouteWithChildren
  '/_app/institute/form': typeof AppInstituteFormRoute
  '/_app/institute/openings': typeof AppInstituteOpeningsRoute
  '/_app/institute/profile': typeof AppInstituteProfileRoute
  '/_app/institute/settings': typeof AppInstituteSettingsRoute
  '/_app/institutes/$instituteId': typeof AppInstitutesInstituteIdRoute
  '/_app/programs/$programId': typeof AppProgramsProgramIdRoute
  '/_app/institute/': typeof AppInstituteIndexRoute
  '/_app/institutes/': typeof AppInstitutesIndexRoute
  '/_app/institute/applications/$applicationId': typeof AppInstituteApplicationsApplicationIdRoute
  '/_app/institute/applications/': typeof AppInstituteApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/apply'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/documents'
    | '/faq'
    | '/forgot-password'
    | '/inquiries'
    | '/institute'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/programs'
    | '/settings'
    | '/setup-from-admin'
    | '/signup'
    | '/terms'
    | '/applications/$applicationId'
    | '/institute/applications'
    | '/institute/form'
    | '/institute/openings'
    | '/institute/profile'
    | '/institute/settings'
    | '/institutes/$instituteId'
    | '/programs/$programId'
    | '/institute/'
    | '/institutes/'
    | '/institute/applications/$applicationId'
    | '/institute/applications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/applications'
    | '/apply'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/documents'
    | '/faq'
    | '/forgot-password'
    | '/inquiries'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/programs'
    | '/settings'
    | '/setup-from-admin'
    | '/signup'
    | '/terms'
    | '/'
    | '/applications/$applicationId'
    | '/institute/form'
    | '/institute/openings'
    | '/institute/profile'
    | '/institute/settings'
    | '/institutes/$instituteId'
    | '/programs/$programId'
    | '/institute'
    | '/institutes'
    | '/institute/applications/$applicationId'
    | '/institute/applications'
  id:
    | '__root__'
    | '/_app'
    | '/_app/applications'
    | '/_app/apply'
    | '/_app/contact'
    | '/_app/cookies'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/faq'
    | '/_app/forgot-password'
    | '/_app/inquiries'
    | '/_app/institute'
    | '/_app/login'
    | '/_app/notifications'
    | '/_app/privacy'
    | '/_app/profile'
    | '/_app/programs'
    | '/_app/settings'
    | '/_app/setup-from-admin'
    | '/_app/signup'
    | '/_app/terms'
    | '/_app/'
    | '/_app/applications/$applicationId'
    | '/_app/institute/applications'
    | '/_app/institute/form'
    | '/_app/institute/openings'
    | '/_app/institute/profile'
    | '/_app/institute/settings'
    | '/_app/institutes/$instituteId'
    | '/_app/programs/$programId'
    | '/_app/institute/'
    | '/_app/institutes/'
    | '/_app/institute/applications/$applicationId'
    | '/_app/institute/applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terms': {
      id: '/_app/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AppTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signup': {
      id: '/_app/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AppSignupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup-from-admin': {
      id: '/_app/setup-from-admin'
      path: '/setup-from-admin'
      fullPath: '/setup-from-admin'
      preLoaderRoute: typeof AppSetupFromAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programs': {
      id: '/_app/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof AppProgramsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/institute': {
      id: '/_app/institute'
      path: '/institute'
      fullPath: '/institute'
      preLoaderRoute: typeof AppInstituteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inquiries': {
      id: '/_app/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof AppInquiriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forgot-password': {
      id: '/_app/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AppForgotPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/faq': {
      id: '/_app/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof AppFaqRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cookies': {
      id: '/_app/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof AppCookiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apply': {
      id: '/_app/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof AppApplyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications': {
      id: '/_app/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/institutes/': {
      id: '/_app/institutes/'
      path: '/institutes'
      fullPath: '/institutes/'
      preLoaderRoute: typeof AppInstitutesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/institute/': {
      id: '/_app/institute/'
      path: '/'
      fullPath: '/institute/'
      preLoaderRoute: typeof AppInstituteIndexRouteImport
      parentRoute: typeof AppInstituteRoute
    }
    '/_app/programs/$programId': {
      id: '/_app/programs/$programId'
      path: '/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof AppProgramsProgramIdRouteImport
      parentRoute: typeof AppProgramsRoute
    }
    '/_app/institutes/$instituteId': {
      id: '/_app/institutes/$instituteId'
      path: '/institutes/$instituteId'
      fullPath: '/institutes/$instituteId'
      preLoaderRoute: typeof AppInstitutesInstituteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/institute/settings': {
      id: '/_app/institute/settings'
      path: '/settings'
      fullPath: '/institute/settings'
      preLoaderRoute: typeof AppInstituteSettingsRouteImport
      parentRoute: typeof AppInstituteRoute
    }
    '/_app/institute/profile': {
      id: '/_app/institute/profile'
      path: '/profile'
      fullPath: '/institute/profile'
      preLoaderRoute: typeof AppInstituteProfileRouteImport
      parentRoute: typeof AppInstituteRoute
    }
    '/_app/institute/openings': {
      id: '/_app/institute/openings'
      path: '/openings'
      fullPath: '/institute/openings'
      preLoaderRoute: typeof AppInstituteOpeningsRouteImport
      parentRoute: typeof AppInstituteRoute
    }
    '/_app/institute/form': {
      id: '/_app/institute/form'
      path: '/form'
      fullPath: '/institute/form'
      preLoaderRoute: typeof AppInstituteFormRouteImport
      parentRoute: typeof AppInstituteRoute
    }
    '/_app/institute/applications': {
      id: '/_app/institute/applications'
      path: '/applications'
      fullPath: '/institute/applications'
      preLoaderRoute: typeof AppInstituteApplicationsRouteImport
      parentRoute: typeof AppInstituteRoute
    }
    '/_app/applications/$applicationId': {
      id: '/_app/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof AppApplicationsApplicationIdRouteImport
      parentRoute: typeof AppApplicationsRoute
    }
    '/_app/institute/applications/': {
      id: '/_app/institute/applications/'
      path: '/'
      fullPath: '/institute/applications/'
      preLoaderRoute: typeof AppInstituteApplicationsIndexRouteImport
      parentRoute: typeof AppInstituteApplicationsRoute
    }
    '/_app/institute/applications/$applicationId': {
      id: '/_app/institute/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/institute/applications/$applicationId'
      preLoaderRoute: typeof AppInstituteApplicationsApplicationIdRouteImport
      parentRoute: typeof AppInstituteApplicationsRoute
    }
  }
}

interface AppApplicationsRouteChildren {
  AppApplicationsApplicationIdRoute: typeof AppApplicationsApplicationIdRoute
}

const AppApplicationsRouteChildren: AppApplicationsRouteChildren = {
  AppApplicationsApplicationIdRoute: AppApplicationsApplicationIdRoute,
}

const AppApplicationsRouteWithChildren = AppApplicationsRoute._addFileChildren(
  AppApplicationsRouteChildren,
)

interface AppInstituteApplicationsRouteChildren {
  AppInstituteApplicationsApplicationIdRoute: typeof AppInstituteApplicationsApplicationIdRoute
  AppInstituteApplicationsIndexRoute: typeof AppInstituteApplicationsIndexRoute
}

const AppInstituteApplicationsRouteChildren: AppInstituteApplicationsRouteChildren =
  {
    AppInstituteApplicationsApplicationIdRoute:
      AppInstituteApplicationsApplicationIdRoute,
    AppInstituteApplicationsIndexRoute: AppInstituteApplicationsIndexRoute,
  }

const AppInstituteApplicationsRouteWithChildren =
  AppInstituteApplicationsRoute._addFileChildren(
    AppInstituteApplicationsRouteChildren,
  )

interface AppInstituteRouteChildren {
  AppInstituteApplicationsRoute: typeof AppInstituteApplicationsRouteWithChildren
  AppInstituteFormRoute: typeof AppInstituteFormRoute
  AppInstituteOpeningsRoute: typeof AppInstituteOpeningsRoute
  AppInstituteProfileRoute: typeof AppInstituteProfileRoute
  AppInstituteSettingsRoute: typeof AppInstituteSettingsRoute
  AppInstituteIndexRoute: typeof AppInstituteIndexRoute
}

const AppInstituteRouteChildren: AppInstituteRouteChildren = {
  AppInstituteApplicationsRoute: AppInstituteApplicationsRouteWithChildren,
  AppInstituteFormRoute: AppInstituteFormRoute,
  AppInstituteOpeningsRoute: AppInstituteOpeningsRoute,
  AppInstituteProfileRoute: AppInstituteProfileRoute,
  AppInstituteSettingsRoute: AppInstituteSettingsRoute,
  AppInstituteIndexRoute: AppInstituteIndexRoute,
}

const AppInstituteRouteWithChildren = AppInstituteRoute._addFileChildren(
  AppInstituteRouteChildren,
)

interface AppProgramsRouteChildren {
  AppProgramsProgramIdRoute: typeof AppProgramsProgramIdRoute
}

const AppProgramsRouteChildren: AppProgramsRouteChildren = {
  AppProgramsProgramIdRoute: AppProgramsProgramIdRoute,
}

const AppProgramsRouteWithChildren = AppProgramsRoute._addFileChildren(
  AppProgramsRouteChildren,
)

interface AppRouteChildren {
  AppApplicationsRoute: typeof AppApplicationsRouteWithChildren
  AppApplyRoute: typeof AppApplyRoute
  AppContactRoute: typeof AppContactRoute
  AppCookiesRoute: typeof AppCookiesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppFaqRoute: typeof AppFaqRoute
  AppForgotPasswordRoute: typeof AppForgotPasswordRoute
  AppInquiriesRoute: typeof AppInquiriesRoute
  AppInstituteRoute: typeof AppInstituteRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgramsRoute: typeof AppProgramsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppSetupFromAdminRoute: typeof AppSetupFromAdminRoute
  AppSignupRoute: typeof AppSignupRoute
  AppTermsRoute: typeof AppTermsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInstitutesInstituteIdRoute: typeof AppInstitutesInstituteIdRoute
  AppInstitutesIndexRoute: typeof AppInstitutesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApplicationsRoute: AppApplicationsRouteWithChildren,
  AppApplyRoute: AppApplyRoute,
  AppContactRoute: AppContactRoute,
  AppCookiesRoute: AppCookiesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppFaqRoute: AppFaqRoute,
  AppForgotPasswordRoute: AppForgotPasswordRoute,
  AppInquiriesRoute: AppInquiriesRoute,
  AppInstituteRoute: AppInstituteRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgramsRoute: AppProgramsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppSetupFromAdminRoute: AppSetupFromAdminRoute,
  AppSignupRoute: AppSignupRoute,
  AppTermsRoute: AppTermsRoute,
  AppIndexRoute: AppIndexRoute,
  AppInstitutesInstituteIdRoute: AppInstitutesInstituteIdRoute,
  AppInstitutesIndexRoute: AppInstitutesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
