/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as TeacherPerformanceRouteImport } from './routes/teacher-performance'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher-attendance'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as MarksRouteImport } from './routes/marks'
import { Route as LeaveRouteImport } from './routes/leave'
import { Route as InstituteRouteImport } from './routes/institute'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsIdRouteImport } from './routes/students.$id'

const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherPerformanceRoute = TeacherPerformanceRouteImport.update({
  id: '/teacher-performance',
  path: '/teacher-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/teacher-attendance',
  path: '/teacher-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const MarksRoute = MarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveRoute = LeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const InstituteRoute = InstituteRouteImport.update({
  id: '/institute',
  path: '/institute',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/admissions': typeof AdmissionsRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/calendar': typeof CalendarRoute
  '/careers': typeof CareersRoute
  '/classes': typeof ClassesRoute
  '/complaints': typeof ComplaintsRoute
  '/events': typeof EventsRoute
  '/exams': typeof ExamsRoute
  '/fees': typeof FeesRoute
  '/institute': typeof InstituteRoute
  '/leave': typeof LeaveRoute
  '/marks': typeof MarksRoute
  '/modules': typeof ModulesRoute
  '/notifications': typeof NotificationsRoute
  '/parents': typeof ParentsRoute
  '/permissions': typeof PermissionsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/students': typeof StudentsRouteWithChildren
  '/subjects': typeof SubjectsRoute
  '/teacher-attendance': typeof TeacherAttendanceRoute
  '/teacher-performance': typeof TeacherPerformanceRoute
  '/teachers': typeof TeachersRoute
  '/timetable': typeof TimetableRoute
  '/transport': typeof TransportRoute
  '/students/$id': typeof StudentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/admissions': typeof AdmissionsRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/calendar': typeof CalendarRoute
  '/careers': typeof CareersRoute
  '/classes': typeof ClassesRoute
  '/complaints': typeof ComplaintsRoute
  '/events': typeof EventsRoute
  '/exams': typeof ExamsRoute
  '/fees': typeof FeesRoute
  '/institute': typeof InstituteRoute
  '/leave': typeof LeaveRoute
  '/marks': typeof MarksRoute
  '/modules': typeof ModulesRoute
  '/notifications': typeof NotificationsRoute
  '/parents': typeof ParentsRoute
  '/permissions': typeof PermissionsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/students': typeof StudentsRouteWithChildren
  '/subjects': typeof SubjectsRoute
  '/teacher-attendance': typeof TeacherAttendanceRoute
  '/teacher-performance': typeof TeacherPerformanceRoute
  '/teachers': typeof TeachersRoute
  '/timetable': typeof TimetableRoute
  '/transport': typeof TransportRoute
  '/students/$id': typeof StudentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/admissions': typeof AdmissionsRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/calendar': typeof CalendarRoute
  '/careers': typeof CareersRoute
  '/classes': typeof ClassesRoute
  '/complaints': typeof ComplaintsRoute
  '/events': typeof EventsRoute
  '/exams': typeof ExamsRoute
  '/fees': typeof FeesRoute
  '/institute': typeof InstituteRoute
  '/leave': typeof LeaveRoute
  '/marks': typeof MarksRoute
  '/modules': typeof ModulesRoute
  '/notifications': typeof NotificationsRoute
  '/parents': typeof ParentsRoute
  '/permissions': typeof PermissionsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/students': typeof StudentsRouteWithChildren
  '/subjects': typeof SubjectsRoute
  '/teacher-attendance': typeof TeacherAttendanceRoute
  '/teacher-performance': typeof TeacherPerformanceRoute
  '/teachers': typeof TeachersRoute
  '/timetable': typeof TimetableRoute
  '/transport': typeof TransportRoute
  '/students/$id': typeof StudentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/admissions'
    | '/alerts'
    | '/analytics'
    | '/announcements'
    | '/attendance'
    | '/calendar'
    | '/careers'
    | '/classes'
    | '/complaints'
    | '/events'
    | '/exams'
    | '/fees'
    | '/institute'
    | '/leave'
    | '/marks'
    | '/modules'
    | '/notifications'
    | '/parents'
    | '/permissions'
    | '/reports'
    | '/settings'
    | '/storage'
    | '/students'
    | '/subjects'
    | '/teacher-attendance'
    | '/teacher-performance'
    | '/teachers'
    | '/timetable'
    | '/transport'
    | '/students/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/admissions'
    | '/alerts'
    | '/analytics'
    | '/announcements'
    | '/attendance'
    | '/calendar'
    | '/careers'
    | '/classes'
    | '/complaints'
    | '/events'
    | '/exams'
    | '/fees'
    | '/institute'
    | '/leave'
    | '/marks'
    | '/modules'
    | '/notifications'
    | '/parents'
    | '/permissions'
    | '/reports'
    | '/settings'
    | '/storage'
    | '/students'
    | '/subjects'
    | '/teacher-attendance'
    | '/teacher-performance'
    | '/teachers'
    | '/timetable'
    | '/transport'
    | '/students/$id'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/admissions'
    | '/alerts'
    | '/analytics'
    | '/announcements'
    | '/attendance'
    | '/calendar'
    | '/careers'
    | '/classes'
    | '/complaints'
    | '/events'
    | '/exams'
    | '/fees'
    | '/institute'
    | '/leave'
    | '/marks'
    | '/modules'
    | '/notifications'
    | '/parents'
    | '/permissions'
    | '/reports'
    | '/settings'
    | '/storage'
    | '/students'
    | '/subjects'
    | '/teacher-attendance'
    | '/teacher-performance'
    | '/teachers'
    | '/timetable'
    | '/transport'
    | '/students/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AttendanceRoute: typeof AttendanceRoute
  CalendarRoute: typeof CalendarRoute
  CareersRoute: typeof CareersRoute
  ClassesRoute: typeof ClassesRoute
  ComplaintsRoute: typeof ComplaintsRoute
  EventsRoute: typeof EventsRoute
  ExamsRoute: typeof ExamsRoute
  FeesRoute: typeof FeesRoute
  InstituteRoute: typeof InstituteRoute
  LeaveRoute: typeof LeaveRoute
  MarksRoute: typeof MarksRoute
  ModulesRoute: typeof ModulesRoute
  NotificationsRoute: typeof NotificationsRoute
  ParentsRoute: typeof ParentsRoute
  PermissionsRoute: typeof PermissionsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StorageRoute: typeof StorageRoute
  StudentsRoute: typeof StudentsRouteWithChildren
  SubjectsRoute: typeof SubjectsRoute
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherPerformanceRoute: typeof TeacherPerformanceRoute
  TeachersRoute: typeof TeachersRoute
  TimetableRoute: typeof TimetableRoute
  TransportRoute: typeof TransportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-performance': {
      id: '/teacher-performance'
      path: '/teacher-performance'
      fullPath: '/teacher-performance'
      preLoaderRoute: typeof TeacherPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-attendance': {
      id: '/teacher-attendance'
      path: '/teacher-attendance'
      fullPath: '/teacher-attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marks': {
      id: '/marks'
      path: '/marks'
      fullPath: '/marks'
      preLoaderRoute: typeof MarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave': {
      id: '/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof LeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institute': {
      id: '/institute'
      path: '/institute'
      fullPath: '/institute'
      preLoaderRoute: typeof InstituteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof StudentsRoute
    }
  }
}

interface StudentsRouteChildren {
  StudentsIdRoute: typeof StudentsIdRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsIdRoute: StudentsIdRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AdmissionsRoute: AdmissionsRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AttendanceRoute: AttendanceRoute,
  CalendarRoute: CalendarRoute,
  CareersRoute: CareersRoute,
  ClassesRoute: ClassesRoute,
  ComplaintsRoute: ComplaintsRoute,
  EventsRoute: EventsRoute,
  ExamsRoute: ExamsRoute,
  FeesRoute: FeesRoute,
  InstituteRoute: InstituteRoute,
  LeaveRoute: LeaveRoute,
  MarksRoute: MarksRoute,
  ModulesRoute: ModulesRoute,
  NotificationsRoute: NotificationsRoute,
  ParentsRoute: ParentsRoute,
  PermissionsRoute: PermissionsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StorageRoute: StorageRoute,
  StudentsRoute: StudentsRouteWithChildren,
  SubjectsRoute: SubjectsRoute,
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherPerformanceRoute: TeacherPerformanceRoute,
  TeachersRoute: TeachersRoute,
  TimetableRoute: TimetableRoute,
  TransportRoute: TransportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
