/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyCertificateRouteImport } from './routes/verify-certificate'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as VerifyStudentIdRouteImport } from './routes/verify.$studentId'
import { Route as CareersSplatRouteImport } from './routes/careers/$'
import { Route as AdmissionsSplatRouteImport } from './routes/admissions/$'
import { Route as AuthenticatedTransportRouteImport } from './routes/_authenticated/transport'
import { Route as AuthenticatedTimetableRouteImport } from './routes/_authenticated/timetable'
import { Route as AuthenticatedTeachersRouteImport } from './routes/_authenticated/teachers'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedRemarksRouteImport } from './routes/_authenticated/remarks'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMarksRouteImport } from './routes/_authenticated/marks'
import { Route as AuthenticatedLeaveRouteImport } from './routes/_authenticated/leave'
import { Route as AuthenticatedIdCardRouteImport } from './routes/_authenticated/id-card'
import { Route as AuthenticatedGrowthRouteImport } from './routes/_authenticated/growth'
import { Route as AuthenticatedFeesRouteImport } from './routes/_authenticated/fees'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedDiaryRouteImport } from './routes/_authenticated/diary'
import { Route as AuthenticatedComplaintsRouteImport } from './routes/_authenticated/complaints'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedActivitiesRouteImport } from './routes/_authenticated/activities'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedAcademicHistoryRouteImport } from './routes/_authenticated/academic-history'
import { Route as AuthenticatedActivityIndexRouteImport } from './routes/_authenticated/activity/index'
import { Route as AuthenticatedStudentsStudentIdRouteImport } from './routes/_authenticated/students.$studentId'
import { Route as AuthenticatedAnnouncementsIdRouteImport } from './routes/_authenticated/announcements.$id'
import { Route as AuthenticatedActivitySportsRouteImport } from './routes/_authenticated/activity/sports'
import { Route as AuthenticatedActivityProfileRouteImport } from './routes/_authenticated/activity/profile'
import { Route as AuthenticatedActivityPracticeRouteImport } from './routes/_authenticated/activity/practice'
import { Route as AuthenticatedActivityNotificationsRouteImport } from './routes/_authenticated/activity/notifications'
import { Route as AuthenticatedActivityMessagesRouteImport } from './routes/_authenticated/activity/messages'
import { Route as AuthenticatedActivityExtraCurricularRouteImport } from './routes/_authenticated/activity/extra-curricular'
import { Route as AuthenticatedActivityDiaryRouteImport } from './routes/_authenticated/activity/diary'
import { Route as AuthenticatedActivityCertificatesRouteImport } from './routes/_authenticated/activity/certificates'
import { Route as AuthenticatedActivityCalendarRouteImport } from './routes/_authenticated/activity/calendar'
import { Route as AuthenticatedActivityAttendanceRouteImport } from './routes/_authenticated/activity/attendance'
import { Route as AuthenticatedActivityAnnouncementsRouteImport } from './routes/_authenticated/activity/announcements'
import { Route as AuthenticatedActivityAchievementsRouteImport } from './routes/_authenticated/activity/achievements'

const VerifyCertificateRoute = VerifyCertificateRouteImport.update({
  id: '/verify-certificate',
  path: '/verify-certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const VerifyStudentIdRoute = VerifyStudentIdRouteImport.update({
  id: '/verify/$studentId',
  path: '/verify/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSplatRoute = CareersSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => CareersRoute,
} as any)
const AdmissionsSplatRoute = AdmissionsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdmissionsRoute,
} as any)
const AuthenticatedTransportRoute = AuthenticatedTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTimetableRoute = AuthenticatedTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeachersRoute = AuthenticatedTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRemarksRoute = AuthenticatedRemarksRouteImport.update({
  id: '/remarks',
  path: '/remarks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarksRoute = AuthenticatedMarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaveRoute = AuthenticatedLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIdCardRoute = AuthenticatedIdCardRouteImport.update({
  id: '/id-card',
  path: '/id-card',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGrowthRoute = AuthenticatedGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeesRoute = AuthenticatedFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiaryRoute = AuthenticatedDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComplaintsRoute = AuthenticatedComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivitiesRoute = AuthenticatedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAcademicHistoryRoute =
  AuthenticatedAcademicHistoryRouteImport.update({
    id: '/academic-history',
    path: '/academic-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedActivityIndexRoute =
  AuthenticatedActivityIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedActivityRoute,
  } as any)
const AuthenticatedStudentsStudentIdRoute =
  AuthenticatedStudentsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => AuthenticatedStudentsRoute,
  } as any)
const AuthenticatedAnnouncementsIdRoute =
  AuthenticatedAnnouncementsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAnnouncementsRoute,
  } as any)
const AuthenticatedActivitySportsRoute =
  AuthenticatedActivitySportsRouteImport.update({
    id: '/sports',
    path: '/sports',
    getParentRoute: () => AuthenticatedActivityRoute,
  } as any)
const AuthenticatedActivityProfileRoute =
  AuthenticatedActivityProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedActivityRoute,
  } as any)
const AuthenticatedActivityPracticeRoute =
  AuthenticatedActivityPracticeRouteImport.update({
    id: '/practice',
    path: '/practice',
    getParentRoute: () => AuthenticatedActivityRoute,
  } as any)
const AuthenticatedActivityNotificationsRoute =
  AuthenticatedActivityNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedActivityRoute,
  } as any)
const AuthenticatedActivityMessagesRoute =
  AuthenticatedActivityMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedActivityRoute,
  } as any)
const AuthenticatedActivityExtraCurricularRoute =
  AuthenticatedActivityExtraCurricularRouteImport.update({
    id: '/extra-curricular',
    path: '/extra-curricular',
    getParentRoute: () => AuthenticatedActivityRoute,
  } as any)
const AuthenticatedActivityDiaryRoute =
  AuthenticatedActivityDiaryRouteImport.update({
    id: '/diary',
    path: '/diary',
    getParentRoute: () => AuthenticatedActivityRoute,
  } as any)
const AuthenticatedActivityCertificatesRoute =
  AuthenticatedActivityCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedActivityRoute,
  } as any)
const AuthenticatedActivityCalendarRoute =
  AuthenticatedActivityCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedActivityRoute,
  } as any)
const AuthenticatedActivityAttendanceRoute =
  AuthenticatedActivityAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedActivityRoute,
  } as any)
const AuthenticatedActivityAnnouncementsRoute =
  AuthenticatedActivityAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedActivityRoute,
  } as any)
const AuthenticatedActivityAchievementsRoute =
  AuthenticatedActivityAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedActivityRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/admissions': typeof AdmissionsRouteWithChildren
  '/careers': typeof CareersRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sports': typeof SportsRoute
  '/terms': typeof TermsRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/academic-history': typeof AuthenticatedAcademicHistoryRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/activity': typeof AuthenticatedActivityRouteWithChildren
  '/alerts': typeof AuthenticatedAlertsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRouteWithChildren
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/diary': typeof AuthenticatedDiaryRoute
  '/events': typeof AuthenticatedEventsRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/growth': typeof AuthenticatedGrowthRoute
  '/id-card': typeof AuthenticatedIdCardRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/marks': typeof AuthenticatedMarksRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/remarks': typeof AuthenticatedRemarksRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/teachers': typeof AuthenticatedTeachersRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/transport': typeof AuthenticatedTransportRoute
  '/admissions/$': typeof AdmissionsSplatRoute
  '/careers/$': typeof CareersSplatRoute
  '/verify/$studentId': typeof VerifyStudentIdRoute
  '/activity/achievements': typeof AuthenticatedActivityAchievementsRoute
  '/activity/announcements': typeof AuthenticatedActivityAnnouncementsRoute
  '/activity/attendance': typeof AuthenticatedActivityAttendanceRoute
  '/activity/calendar': typeof AuthenticatedActivityCalendarRoute
  '/activity/certificates': typeof AuthenticatedActivityCertificatesRoute
  '/activity/diary': typeof AuthenticatedActivityDiaryRoute
  '/activity/extra-curricular': typeof AuthenticatedActivityExtraCurricularRoute
  '/activity/messages': typeof AuthenticatedActivityMessagesRoute
  '/activity/notifications': typeof AuthenticatedActivityNotificationsRoute
  '/activity/practice': typeof AuthenticatedActivityPracticeRoute
  '/activity/profile': typeof AuthenticatedActivityProfileRoute
  '/activity/sports': typeof AuthenticatedActivitySportsRoute
  '/announcements/$id': typeof AuthenticatedAnnouncementsIdRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/activity/': typeof AuthenticatedActivityIndexRoute
}
export interface FileRoutesByTo {
  '/admissions': typeof AdmissionsRouteWithChildren
  '/careers': typeof CareersRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sports': typeof SportsRoute
  '/terms': typeof TermsRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/academic-history': typeof AuthenticatedAcademicHistoryRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRouteWithChildren
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/diary': typeof AuthenticatedDiaryRoute
  '/events': typeof AuthenticatedEventsRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/growth': typeof AuthenticatedGrowthRoute
  '/id-card': typeof AuthenticatedIdCardRoute
  '/leave': typeof AuthenticatedLeaveRoute
  '/marks': typeof AuthenticatedMarksRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/remarks': typeof AuthenticatedRemarksRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/teachers': typeof AuthenticatedTeachersRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/transport': typeof AuthenticatedTransportRoute
  '/admissions/$': typeof AdmissionsSplatRoute
  '/careers/$': typeof CareersSplatRoute
  '/verify/$studentId': typeof VerifyStudentIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/activity/achievements': typeof AuthenticatedActivityAchievementsRoute
  '/activity/announcements': typeof AuthenticatedActivityAnnouncementsRoute
  '/activity/attendance': typeof AuthenticatedActivityAttendanceRoute
  '/activity/calendar': typeof AuthenticatedActivityCalendarRoute
  '/activity/certificates': typeof AuthenticatedActivityCertificatesRoute
  '/activity/diary': typeof AuthenticatedActivityDiaryRoute
  '/activity/extra-curricular': typeof AuthenticatedActivityExtraCurricularRoute
  '/activity/messages': typeof AuthenticatedActivityMessagesRoute
  '/activity/notifications': typeof AuthenticatedActivityNotificationsRoute
  '/activity/practice': typeof AuthenticatedActivityPracticeRoute
  '/activity/profile': typeof AuthenticatedActivityProfileRoute
  '/activity/sports': typeof AuthenticatedActivitySportsRoute
  '/announcements/$id': typeof AuthenticatedAnnouncementsIdRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/activity': typeof AuthenticatedActivityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admissions': typeof AdmissionsRouteWithChildren
  '/careers': typeof CareersRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sports': typeof SportsRoute
  '/terms': typeof TermsRoute
  '/verify-certificate': typeof VerifyCertificateRoute
  '/_authenticated/academic-history': typeof AuthenticatedAcademicHistoryRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/activities': typeof AuthenticatedActivitiesRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRouteWithChildren
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRouteWithChildren
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/complaints': typeof AuthenticatedComplaintsRoute
  '/_authenticated/diary': typeof AuthenticatedDiaryRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRoute
  '/_authenticated/fees': typeof AuthenticatedFeesRoute
  '/_authenticated/growth': typeof AuthenticatedGrowthRoute
  '/_authenticated/id-card': typeof AuthenticatedIdCardRoute
  '/_authenticated/leave': typeof AuthenticatedLeaveRoute
  '/_authenticated/marks': typeof AuthenticatedMarksRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/remarks': typeof AuthenticatedRemarksRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/_authenticated/teachers': typeof AuthenticatedTeachersRoute
  '/_authenticated/timetable': typeof AuthenticatedTimetableRoute
  '/_authenticated/transport': typeof AuthenticatedTransportRoute
  '/admissions/$': typeof AdmissionsSplatRoute
  '/careers/$': typeof CareersSplatRoute
  '/verify/$studentId': typeof VerifyStudentIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/activity/achievements': typeof AuthenticatedActivityAchievementsRoute
  '/_authenticated/activity/announcements': typeof AuthenticatedActivityAnnouncementsRoute
  '/_authenticated/activity/attendance': typeof AuthenticatedActivityAttendanceRoute
  '/_authenticated/activity/calendar': typeof AuthenticatedActivityCalendarRoute
  '/_authenticated/activity/certificates': typeof AuthenticatedActivityCertificatesRoute
  '/_authenticated/activity/diary': typeof AuthenticatedActivityDiaryRoute
  '/_authenticated/activity/extra-curricular': typeof AuthenticatedActivityExtraCurricularRoute
  '/_authenticated/activity/messages': typeof AuthenticatedActivityMessagesRoute
  '/_authenticated/activity/notifications': typeof AuthenticatedActivityNotificationsRoute
  '/_authenticated/activity/practice': typeof AuthenticatedActivityPracticeRoute
  '/_authenticated/activity/profile': typeof AuthenticatedActivityProfileRoute
  '/_authenticated/activity/sports': typeof AuthenticatedActivitySportsRoute
  '/_authenticated/announcements/$id': typeof AuthenticatedAnnouncementsIdRoute
  '/_authenticated/students/$studentId': typeof AuthenticatedStudentsStudentIdRoute
  '/_authenticated/activity/': typeof AuthenticatedActivityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admissions'
    | '/careers'
    | '/cookies'
    | '/login'
    | '/privacy'
    | '/sports'
    | '/terms'
    | '/verify-certificate'
    | '/academic-history'
    | '/achievements'
    | '/activities'
    | '/activity'
    | '/alerts'
    | '/announcements'
    | '/assignments'
    | '/attendance'
    | '/certificates'
    | '/classes'
    | '/complaints'
    | '/diary'
    | '/events'
    | '/exams'
    | '/fees'
    | '/growth'
    | '/id-card'
    | '/leave'
    | '/marks'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/remarks'
    | '/students'
    | '/teachers'
    | '/timetable'
    | '/transport'
    | '/admissions/$'
    | '/careers/$'
    | '/verify/$studentId'
    | '/activity/achievements'
    | '/activity/announcements'
    | '/activity/attendance'
    | '/activity/calendar'
    | '/activity/certificates'
    | '/activity/diary'
    | '/activity/extra-curricular'
    | '/activity/messages'
    | '/activity/notifications'
    | '/activity/practice'
    | '/activity/profile'
    | '/activity/sports'
    | '/announcements/$id'
    | '/students/$studentId'
    | '/activity/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admissions'
    | '/careers'
    | '/cookies'
    | '/login'
    | '/privacy'
    | '/sports'
    | '/terms'
    | '/verify-certificate'
    | '/academic-history'
    | '/achievements'
    | '/activities'
    | '/alerts'
    | '/announcements'
    | '/assignments'
    | '/attendance'
    | '/certificates'
    | '/classes'
    | '/complaints'
    | '/diary'
    | '/events'
    | '/exams'
    | '/fees'
    | '/growth'
    | '/id-card'
    | '/leave'
    | '/marks'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/remarks'
    | '/students'
    | '/teachers'
    | '/timetable'
    | '/transport'
    | '/admissions/$'
    | '/careers/$'
    | '/verify/$studentId'
    | '/'
    | '/activity/achievements'
    | '/activity/announcements'
    | '/activity/attendance'
    | '/activity/calendar'
    | '/activity/certificates'
    | '/activity/diary'
    | '/activity/extra-curricular'
    | '/activity/messages'
    | '/activity/notifications'
    | '/activity/practice'
    | '/activity/profile'
    | '/activity/sports'
    | '/announcements/$id'
    | '/students/$studentId'
    | '/activity'
  id:
    | '__root__'
    | '/_authenticated'
    | '/admissions'
    | '/careers'
    | '/cookies'
    | '/login'
    | '/privacy'
    | '/sports'
    | '/terms'
    | '/verify-certificate'
    | '/_authenticated/academic-history'
    | '/_authenticated/achievements'
    | '/_authenticated/activities'
    | '/_authenticated/activity'
    | '/_authenticated/alerts'
    | '/_authenticated/announcements'
    | '/_authenticated/assignments'
    | '/_authenticated/attendance'
    | '/_authenticated/certificates'
    | '/_authenticated/classes'
    | '/_authenticated/complaints'
    | '/_authenticated/diary'
    | '/_authenticated/events'
    | '/_authenticated/exams'
    | '/_authenticated/fees'
    | '/_authenticated/growth'
    | '/_authenticated/id-card'
    | '/_authenticated/leave'
    | '/_authenticated/marks'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/remarks'
    | '/_authenticated/students'
    | '/_authenticated/teachers'
    | '/_authenticated/timetable'
    | '/_authenticated/transport'
    | '/admissions/$'
    | '/careers/$'
    | '/verify/$studentId'
    | '/_authenticated/'
    | '/_authenticated/activity/achievements'
    | '/_authenticated/activity/announcements'
    | '/_authenticated/activity/attendance'
    | '/_authenticated/activity/calendar'
    | '/_authenticated/activity/certificates'
    | '/_authenticated/activity/diary'
    | '/_authenticated/activity/extra-curricular'
    | '/_authenticated/activity/messages'
    | '/_authenticated/activity/notifications'
    | '/_authenticated/activity/practice'
    | '/_authenticated/activity/profile'
    | '/_authenticated/activity/sports'
    | '/_authenticated/announcements/$id'
    | '/_authenticated/students/$studentId'
    | '/_authenticated/activity/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdmissionsRoute: typeof AdmissionsRouteWithChildren
  CareersRoute: typeof CareersRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SportsRoute: typeof SportsRoute
  TermsRoute: typeof TermsRoute
  VerifyCertificateRoute: typeof VerifyCertificateRoute
  VerifyStudentIdRoute: typeof VerifyStudentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-certificate': {
      id: '/verify-certificate'
      path: '/verify-certificate'
      fullPath: '/verify-certificate'
      preLoaderRoute: typeof VerifyCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/verify/$studentId': {
      id: '/verify/$studentId'
      path: '/verify/$studentId'
      fullPath: '/verify/$studentId'
      preLoaderRoute: typeof VerifyStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$': {
      id: '/careers/$'
      path: '/$'
      fullPath: '/careers/$'
      preLoaderRoute: typeof CareersSplatRouteImport
      parentRoute: typeof CareersRoute
    }
    '/admissions/$': {
      id: '/admissions/$'
      path: '/$'
      fullPath: '/admissions/$'
      preLoaderRoute: typeof AdmissionsSplatRouteImport
      parentRoute: typeof AdmissionsRoute
    }
    '/_authenticated/transport': {
      id: '/_authenticated/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof AuthenticatedTransportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/timetable': {
      id: '/_authenticated/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AuthenticatedTimetableRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teachers': {
      id: '/_authenticated/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AuthenticatedTeachersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/remarks': {
      id: '/_authenticated/remarks'
      path: '/remarks'
      fullPath: '/remarks'
      preLoaderRoute: typeof AuthenticatedRemarksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marks': {
      id: '/_authenticated/marks'
      path: '/marks'
      fullPath: '/marks'
      preLoaderRoute: typeof AuthenticatedMarksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leave': {
      id: '/_authenticated/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AuthenticatedLeaveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/id-card': {
      id: '/_authenticated/id-card'
      path: '/id-card'
      fullPath: '/id-card'
      preLoaderRoute: typeof AuthenticatedIdCardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/growth': {
      id: '/_authenticated/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof AuthenticatedGrowthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fees': {
      id: '/_authenticated/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AuthenticatedFeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diary': {
      id: '/_authenticated/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof AuthenticatedDiaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/complaints': {
      id: '/_authenticated/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AuthenticatedComplaintsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activities': {
      id: '/_authenticated/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/academic-history': {
      id: '/_authenticated/academic-history'
      path: '/academic-history'
      fullPath: '/academic-history'
      preLoaderRoute: typeof AuthenticatedAcademicHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity/': {
      id: '/_authenticated/activity/'
      path: '/'
      fullPath: '/activity/'
      preLoaderRoute: typeof AuthenticatedActivityIndexRouteImport
      parentRoute: typeof AuthenticatedActivityRoute
    }
    '/_authenticated/students/$studentId': {
      id: '/_authenticated/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
    '/_authenticated/announcements/$id': {
      id: '/_authenticated/announcements/$id'
      path: '/$id'
      fullPath: '/announcements/$id'
      preLoaderRoute: typeof AuthenticatedAnnouncementsIdRouteImport
      parentRoute: typeof AuthenticatedAnnouncementsRoute
    }
    '/_authenticated/activity/sports': {
      id: '/_authenticated/activity/sports'
      path: '/sports'
      fullPath: '/activity/sports'
      preLoaderRoute: typeof AuthenticatedActivitySportsRouteImport
      parentRoute: typeof AuthenticatedActivityRoute
    }
    '/_authenticated/activity/profile': {
      id: '/_authenticated/activity/profile'
      path: '/profile'
      fullPath: '/activity/profile'
      preLoaderRoute: typeof AuthenticatedActivityProfileRouteImport
      parentRoute: typeof AuthenticatedActivityRoute
    }
    '/_authenticated/activity/practice': {
      id: '/_authenticated/activity/practice'
      path: '/practice'
      fullPath: '/activity/practice'
      preLoaderRoute: typeof AuthenticatedActivityPracticeRouteImport
      parentRoute: typeof AuthenticatedActivityRoute
    }
    '/_authenticated/activity/notifications': {
      id: '/_authenticated/activity/notifications'
      path: '/notifications'
      fullPath: '/activity/notifications'
      preLoaderRoute: typeof AuthenticatedActivityNotificationsRouteImport
      parentRoute: typeof AuthenticatedActivityRoute
    }
    '/_authenticated/activity/messages': {
      id: '/_authenticated/activity/messages'
      path: '/messages'
      fullPath: '/activity/messages'
      preLoaderRoute: typeof AuthenticatedActivityMessagesRouteImport
      parentRoute: typeof AuthenticatedActivityRoute
    }
    '/_authenticated/activity/extra-curricular': {
      id: '/_authenticated/activity/extra-curricular'
      path: '/extra-curricular'
      fullPath: '/activity/extra-curricular'
      preLoaderRoute: typeof AuthenticatedActivityExtraCurricularRouteImport
      parentRoute: typeof AuthenticatedActivityRoute
    }
    '/_authenticated/activity/diary': {
      id: '/_authenticated/activity/diary'
      path: '/diary'
      fullPath: '/activity/diary'
      preLoaderRoute: typeof AuthenticatedActivityDiaryRouteImport
      parentRoute: typeof AuthenticatedActivityRoute
    }
    '/_authenticated/activity/certificates': {
      id: '/_authenticated/activity/certificates'
      path: '/certificates'
      fullPath: '/activity/certificates'
      preLoaderRoute: typeof AuthenticatedActivityCertificatesRouteImport
      parentRoute: typeof AuthenticatedActivityRoute
    }
    '/_authenticated/activity/calendar': {
      id: '/_authenticated/activity/calendar'
      path: '/calendar'
      fullPath: '/activity/calendar'
      preLoaderRoute: typeof AuthenticatedActivityCalendarRouteImport
      parentRoute: typeof AuthenticatedActivityRoute
    }
    '/_authenticated/activity/attendance': {
      id: '/_authenticated/activity/attendance'
      path: '/attendance'
      fullPath: '/activity/attendance'
      preLoaderRoute: typeof AuthenticatedActivityAttendanceRouteImport
      parentRoute: typeof AuthenticatedActivityRoute
    }
    '/_authenticated/activity/announcements': {
      id: '/_authenticated/activity/announcements'
      path: '/announcements'
      fullPath: '/activity/announcements'
      preLoaderRoute: typeof AuthenticatedActivityAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedActivityRoute
    }
    '/_authenticated/activity/achievements': {
      id: '/_authenticated/activity/achievements'
      path: '/achievements'
      fullPath: '/activity/achievements'
      preLoaderRoute: typeof AuthenticatedActivityAchievementsRouteImport
      parentRoute: typeof AuthenticatedActivityRoute
    }
  }
}

interface AuthenticatedActivityRouteChildren {
  AuthenticatedActivityAchievementsRoute: typeof AuthenticatedActivityAchievementsRoute
  AuthenticatedActivityAnnouncementsRoute: typeof AuthenticatedActivityAnnouncementsRoute
  AuthenticatedActivityAttendanceRoute: typeof AuthenticatedActivityAttendanceRoute
  AuthenticatedActivityCalendarRoute: typeof AuthenticatedActivityCalendarRoute
  AuthenticatedActivityCertificatesRoute: typeof AuthenticatedActivityCertificatesRoute
  AuthenticatedActivityDiaryRoute: typeof AuthenticatedActivityDiaryRoute
  AuthenticatedActivityExtraCurricularRoute: typeof AuthenticatedActivityExtraCurricularRoute
  AuthenticatedActivityMessagesRoute: typeof AuthenticatedActivityMessagesRoute
  AuthenticatedActivityNotificationsRoute: typeof AuthenticatedActivityNotificationsRoute
  AuthenticatedActivityPracticeRoute: typeof AuthenticatedActivityPracticeRoute
  AuthenticatedActivityProfileRoute: typeof AuthenticatedActivityProfileRoute
  AuthenticatedActivitySportsRoute: typeof AuthenticatedActivitySportsRoute
  AuthenticatedActivityIndexRoute: typeof AuthenticatedActivityIndexRoute
}

const AuthenticatedActivityRouteChildren: AuthenticatedActivityRouteChildren = {
  AuthenticatedActivityAchievementsRoute:
    AuthenticatedActivityAchievementsRoute,
  AuthenticatedActivityAnnouncementsRoute:
    AuthenticatedActivityAnnouncementsRoute,
  AuthenticatedActivityAttendanceRoute: AuthenticatedActivityAttendanceRoute,
  AuthenticatedActivityCalendarRoute: AuthenticatedActivityCalendarRoute,
  AuthenticatedActivityCertificatesRoute:
    AuthenticatedActivityCertificatesRoute,
  AuthenticatedActivityDiaryRoute: AuthenticatedActivityDiaryRoute,
  AuthenticatedActivityExtraCurricularRoute:
    AuthenticatedActivityExtraCurricularRoute,
  AuthenticatedActivityMessagesRoute: AuthenticatedActivityMessagesRoute,
  AuthenticatedActivityNotificationsRoute:
    AuthenticatedActivityNotificationsRoute,
  AuthenticatedActivityPracticeRoute: AuthenticatedActivityPracticeRoute,
  AuthenticatedActivityProfileRoute: AuthenticatedActivityProfileRoute,
  AuthenticatedActivitySportsRoute: AuthenticatedActivitySportsRoute,
  AuthenticatedActivityIndexRoute: AuthenticatedActivityIndexRoute,
}

const AuthenticatedActivityRouteWithChildren =
  AuthenticatedActivityRoute._addFileChildren(
    AuthenticatedActivityRouteChildren,
  )

interface AuthenticatedAnnouncementsRouteChildren {
  AuthenticatedAnnouncementsIdRoute: typeof AuthenticatedAnnouncementsIdRoute
}

const AuthenticatedAnnouncementsRouteChildren: AuthenticatedAnnouncementsRouteChildren =
  {
    AuthenticatedAnnouncementsIdRoute: AuthenticatedAnnouncementsIdRoute,
  }

const AuthenticatedAnnouncementsRouteWithChildren =
  AuthenticatedAnnouncementsRoute._addFileChildren(
    AuthenticatedAnnouncementsRouteChildren,
  )

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsStudentIdRoute: typeof AuthenticatedStudentsStudentIdRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsStudentIdRoute: AuthenticatedStudentsStudentIdRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAcademicHistoryRoute: typeof AuthenticatedAcademicHistoryRoute
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedActivitiesRoute: typeof AuthenticatedActivitiesRoute
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRouteWithChildren
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRouteWithChildren
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedComplaintsRoute: typeof AuthenticatedComplaintsRoute
  AuthenticatedDiaryRoute: typeof AuthenticatedDiaryRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRoute
  AuthenticatedFeesRoute: typeof AuthenticatedFeesRoute
  AuthenticatedGrowthRoute: typeof AuthenticatedGrowthRoute
  AuthenticatedIdCardRoute: typeof AuthenticatedIdCardRoute
  AuthenticatedLeaveRoute: typeof AuthenticatedLeaveRoute
  AuthenticatedMarksRoute: typeof AuthenticatedMarksRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRemarksRoute: typeof AuthenticatedRemarksRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
  AuthenticatedTeachersRoute: typeof AuthenticatedTeachersRoute
  AuthenticatedTimetableRoute: typeof AuthenticatedTimetableRoute
  AuthenticatedTransportRoute: typeof AuthenticatedTransportRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAcademicHistoryRoute: AuthenticatedAcademicHistoryRoute,
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedActivitiesRoute: AuthenticatedActivitiesRoute,
  AuthenticatedActivityRoute: AuthenticatedActivityRouteWithChildren,
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRouteWithChildren,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedComplaintsRoute: AuthenticatedComplaintsRoute,
  AuthenticatedDiaryRoute: AuthenticatedDiaryRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRoute,
  AuthenticatedFeesRoute: AuthenticatedFeesRoute,
  AuthenticatedGrowthRoute: AuthenticatedGrowthRoute,
  AuthenticatedIdCardRoute: AuthenticatedIdCardRoute,
  AuthenticatedLeaveRoute: AuthenticatedLeaveRoute,
  AuthenticatedMarksRoute: AuthenticatedMarksRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRemarksRoute: AuthenticatedRemarksRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
  AuthenticatedTeachersRoute: AuthenticatedTeachersRoute,
  AuthenticatedTimetableRoute: AuthenticatedTimetableRoute,
  AuthenticatedTransportRoute: AuthenticatedTransportRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdmissionsRouteChildren {
  AdmissionsSplatRoute: typeof AdmissionsSplatRoute
}

const AdmissionsRouteChildren: AdmissionsRouteChildren = {
  AdmissionsSplatRoute: AdmissionsSplatRoute,
}

const AdmissionsRouteWithChildren = AdmissionsRoute._addFileChildren(
  AdmissionsRouteChildren,
)

interface CareersRouteChildren {
  CareersSplatRoute: typeof CareersSplatRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersSplatRoute: CareersSplatRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdmissionsRoute: AdmissionsRouteWithChildren,
  CareersRoute: CareersRouteWithChildren,
  CookiesRoute: CookiesRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SportsRoute: SportsRoute,
  TermsRoute: TermsRoute,
  VerifyCertificateRoute: VerifyCertificateRoute,
  VerifyStudentIdRoute: VerifyStudentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
