export { renderErrorPage } from "./error-page";
export { consumeLastCapturedError } from "./error-capture";
export {
  formatCurrency,
  formatDate,
  formatInr,
  formatInrOrDash,
  formatLabel,
  formatPercent,
  getAvatarInitials,
  getInitials,
} from "./format";
export {
  addLocalDays,
  formatDateTimeEnIn,
  formatDisplayDate,
  formatMonthYear,
  inferAcademicYearLabel,
  todayLocalIso,
  todayUtcIso,
  toLocalIsoDate,
} from "./date";
export {
  isTenDigitPhone,
  looksLikeEmail,
  normalizeEmail,
  normalizePhoneDigits,
  normalizePhoneLast10,
} from "./phone";
export { matchesSearchQuery, sortLocaleNumeric, uniqueSortedStrings } from "./search";
export { clamp, percentOf, roundTo } from "./math";
export { coerceSelectValue, parseSelectValue } from "./select";
export {
  LEARNER_PUBLISHED_MARKS_KEY,
  loadLearnerPublishedReports,
  saveLearnerPublishedReports,
  syncPublishedMarksToLearners,
  learnerReportsForStudent,
  normalizeMarksClass,
  type LearnerPublishedReport,
  type LearnerPublishedSubjectMark,
} from "./learner-published-marks";
export {
  PRINCIPAL_MARK_ALERTS_KEY,
  loadPrincipalMarkAlerts,
  pushPrincipalMarkAlert,
  principalMarkAlertsForTeacher,
  pendingCountForTeacherInAlert,
  type PrincipalMarkAlert,
  type MarkAlertRecipient,
} from "./principal-mark-alerts";
export {
  PRINCIPAL_ATTENDANCE_ALERTS_KEY,
  loadPrincipalAttendanceAlerts,
  pushPrincipalAttendanceAlert,
  principalAttendanceAlertsForTeacher,
  pendingCountForTeacherInAttendanceAlert,
  removeTeacherFromPrincipalAttendanceAlerts,
  type PrincipalAttendanceAlert,
  type AttendanceAlertRecipient,
} from "./principal-attendance-alerts";
export {
  ATTENDANCE_PENDING_KEY,
  ensureAttendancePendingSeed,
  loadAttendancePending,
  markAttendanceSubmitted,
  setAttendancePendingForDate,
  summarizeAttendancePendingByTeacher,
  type AttendancePendingClass,
} from "./attendance-pending-bridge";
export {
  HOMEWORK_LOGS_KEY,
  DIARY_SUBMISSIONS_KEY,
  loadHomeworkActivityLogs,
  pushHomeworkActivityLog,
  loadDiarySubmissionLogs,
  pushDiarySubmissionLog,
  ensureHomeworkDiaryDemoSeed,
  type HomeworkActivityLog,
  type HomeworkLogAction,
  type DiarySubmissionLog,
} from "./homework-diary-bridge";
export {
  CERTIFICATE_RECOMMENDATIONS_KEY,
  loadCertificateRecommendations,
  pushCertificateRecommendation,
  markCertificateRecommendationIssued,
  dismissCertificateRecommendation,
  pendingCertificateRecommendations,
  type CertificateRecommendation,
  type CertificateRecommendationStatus,
} from "./certificate-recommendations";
export {
  OFFLINE_SYNC_QUEUE_KEY,
  OFFLINE_SYNC_META_KEY,
  OFFLINE_SYNC_EVENT,
  OFFLINE_SYNC_SERVER_SNAPSHOT,
  loadOfflineSyncMeta,
  saveOfflineSyncMeta,
  setAutoSync,
  getOfflineQueue,
  getPendingSyncCount,
  getFailedSyncCount,
  getLastSyncedAt,
  isOnline,
  getOfflineSyncSnapshot,
  subscribeOfflineSync,
  enqueueOfflineOp,
  runOrQueueOffline,
  recordLocalChangeForSync,
  flushOfflineQueue,
  retryFailedOfflineSync,
  ensureOfflineQueueDemoSeed,
  startAutomaticOfflineSync,
  type OfflineQueueItem,
  type OfflineQueueItemStatus,
  type OfflineQueueOp,
  type OfflineSyncApp,
  type OfflineSyncMeta,
  type OfflineSyncPhase,
  type OfflineSyncSnapshot,
} from "./offline-sync-queue";
export {
  LUMENX_DEMO_SYNC,
  LUMENX_DEMO_SYNC_PING_KEY,
  postDemoSync,
  listenDemoSync,
  type DemoSyncKind,
} from "./demo-cross-port";
export {
  loadLeaveDecisions,
  saveLeaveDecision,
  loadDemoComplaints,
  appendDemoComplaint,
  saveDemoComplaints,
  loadBroadcastInbox,
  appendBroadcastInbox,
  saveTeacherLeaveSnapshot,
  loadTeacherLeaveSnapshot,
  type DemoLeaveDecision,
  type DemoComplaint,
  type DemoBroadcast,
} from "./demo-shared-records";
export {
  RECYCLE_BIN_KEY,
  RECYCLE_BIN_RETENTION_DAYS,
  softDeleteToRecycleBin,
  purgeExpiredRecycleBin,
  loadRecycleBin,
  restoreFromRecycleBin,
  permanentlyDeleteFromRecycleBin,
  daysLeftInRecycleBin,
  ensureRecycleBinDemoSeed,
  type RecycleBinItem,
  type RecycleBinModule,
} from "./soft-delete-recycle";
export {
  NOTIFICATION_RETENTION_DAYS,
  NOTIFICATION_RECYCLE_BIN_DAYS,
  NOTIFICATION_STATE_KEY,
  isNotificationStarred,
  setNotificationStarred,
  applyStarredFlags,
  applyNotificationRetention,
  softDeleteNotification,
  loadNotificationRecycleBin,
  restoreNotificationFromBin,
  purgeNotificationRecycleBin,
  notificationRetentionSummary,
  type RecycledNotification,
  type RetentionAwareNotification,
  type NotificationLifecycleState,
} from "./notification-retention";
export {
  PLATFORM_READONLY_KEY,
  PLATFORM_READONLY_COPY,
  loadPlatformReadOnlyState,
  savePlatformReadOnlyState,
  getActiveReadOnlyReasons,
  isPlatformReadOnly,
  syncSubscriptionExpiredFromBilling,
  syncSubscriptionReadOnlyFromLifecycle,
  syncAcademicYearLocked,
  type PlatformReadOnlyReason,
  type PlatformReadOnlyState,
} from "./platform-readonly";
export {
  SHARED_INSTITUTE_PROFILE_KEY,
  INSTITUTE_PROFILE_MESSAGE,
  INSTITUTE_PROFILE_READY,
  INSTITUTE_PROFILE_CHANGED_EVENT,
  normalizeInstituteProfile,
  admissionsInstituteIdForDemoProfile,
  admissionsInstituteIdForAdminInstitute,
  loadSharedInstituteProfile,
  saveSharedInstituteProfile,
  publishSharedInstituteProfile,
  isInstituteProfileSyncMessage,
  applyInstituteProfileSyncMessage,
  type SharedInstituteProfileBag,
  type InstituteProfileSyncMessage,
} from "./shared-institute-profile";
export {
  INSTITUTE_PUBLIC_PROFILE_KEY,
  emptyPublicProfile,
  extractPublicProfileFromSettings,
  instituteDtoToDemoProfile,
  mergePublicProfileIntoSettings,
  publicProfileFromRegistrationSeed,
  type InstituteRegistrationProfileSeed,
} from "./institute-public-profile";
export {
  INSTITUTE_REGISTRATION_STORAGE_KEY,
  INSTITUTE_REGISTRATION_CHANGED_EVENT,
  listInstituteRegistrations,
  listPendingInstituteRegistrations,
  getInstituteRegistration,
  findInstituteRegistrationByEmail,
  submitInstituteRegistration,
  approveInstituteRegistration,
  rejectInstituteRegistration,
  subscribeInstituteRegistrations,
  ensureDemoPendingRegistration,
  type InstituteRegistrationStatus,
  type InstituteRegistrationPayload,
  type InstituteRegistrationApplication,
} from "./institute-registration-store";
export {
  compressInstituteLogoDataUrl,
  buildInstituteMonogramLogoUrl,
  type CompressLogoOptions,
} from "./institute-logo";
export * from "./subscription";
export {
  TRANSPORT_OPS_STORAGE_KEY,
  TRANSPORT_OPS_CHANGED_EVENT,
  loadTransportOps,
  saveTransportOps,
  seedTransportOps,
  upsertBusEnrollment,
  deleteBusEnrollment,
  enrollmentsForVehicle,
  newEnrollmentsForVehicle,
  existingEnrollmentsForVehicle,
  syncDriverStopAssignment,
  syncRouteLockFromAdmin,
  normalizeTransportPhoneDigits,
  listDriverAccounts,
  findDriverAccountByPhone,
  findDriverAccountByAdminDriverId,
  findDriverAccountByVehicleId,
  TRANSPORT_ROUTE_DISPLAY,
  upsertDriverAccountFromAdmin,
  setDriverAccountStatus,
  deleteDriverAccount,
  CONNECT_LEARNER_TO_STUDENT_ID,
  CANONICAL_TRANSPORT_STUDENTS,
  resolveCanonicalStudentId,
  enrollmentForStudent,
  enrollmentsForRoute,
  DRIVER_SESSION_TO_ADMIN,
  projectConnectTransport,
  type TransportBusEnrollment,
  type TransportDriverStopSync,
  type TransportRouteLock,
  type TransportDriverAccount,
  type TransportOpsSnapshot,
  type ConnectTransportProjection,
} from "./transport-ops-bridge";
export {
  TRANSPORT_EMERGENCY_STORAGE_KEY,
  TRANSPORT_EMERGENCY_CHANGED_EVENT,
  loadTransportEmergencies,
  saveTransportEmergencies,
  listTransportEmergencies,
  listActiveTransportEmergencies,
  listResolvedTransportEmergencies,
  getTransportEmergencyById,
  getActiveTransportEmergencyCount,
  findOpenEmergencyForDriver,
  findOpenEmergencyForVehicle,
  createTransportEmergency,
  acknowledgeTransportEmergency,
  resolveTransportEmergency,
  resetTransportEmergencies,
  subscribeTransportEmergencies,
  transportEmergencyTypeLabel,
  transportEmergencyStatusLabel,
  isEmergencyOpen,
  type TransportEmergencyStatus,
  type TransportEmergencyType,
  type TransportEmergencyTimelineEvent,
  type TransportEmergency,
  type TransportEmergencySnapshot,
  type CreateTransportEmergencyInput,
  type CreateTransportEmergencyResult,
} from "./transport-emergency";
export {
  TRANSPORT_ATTENDANCE_STORAGE_KEY,
  TRANSPORT_ATTENDANCE_CHANGED_EVENT,
  loadTransportAttendance,
  saveTransportAttendance,
  listTransportAttendanceMarks,
  listTransportAttendanceTrips,
  findTripMetaForVehicle,
  isSharedTripActive,
  listMarksForTrip,
  listActiveTripAttendanceMarks,
  getMarkForStudent,
  syncSharedTripMeta,
  finalizeTripAttendance,
  clearTripAttendance,
  upsertBoardingMark,
  upsertDroppingMark,
  projectConnectAttendanceForStudent,
  resetTransportAttendance,
  subscribeTransportAttendance,
  type SharedBoardingStatus,
  type SharedDroppingStatus,
  type SharedTripAttendanceMark,
  type SharedTripAttendanceMeta,
  type TransportAttendanceSnapshot,
  type UpsertBoardingInput,
  type UpsertDroppingInput,
  type AttendanceMarkResult,
  type AttendanceRuleCode,
} from "./transport-attendance-bridge";
export {
  TRANSPORT_NOTIFICATION_STORAGE_KEY,
  TRANSPORT_NOTIFICATION_CHANGED_EVENT,
  loadTransportNotifications,
  listTransportNotifications,
  pushTransportNotification,
  markTransportNotificationRead,
  markAllTransportNotificationsRead,
  resetTransportNotifications,
  subscribeTransportNotifications,
  notifyDriverStopApproved,
  notifyDriverStopDeclined,
  notifyDriverRouteLocked,
  notifyDriverRouteUnlocked,
  notifyAdminStopRequest,
  notifyAdminTripStarted,
  notifyAdminTripEnded,
  notifyAdminSos,
  notifyAdminEmergency,
  notifyDriverSosAcknowledged,
  notifyDriverSosResolved,
  notifyConnectTripStarted,
  notifyConnectTripEnded,
  notifyConnectSos,
  notifyConnectEmergency,
  notifyConnectStopAssigned,
  notifyConnectBusApproach,
  notifyConnectStudentBoarded,
  notifyConnectStudentNotBoarded,
  notifyConnectReachedSchool,
  notifyConnectBoardingStarted,
  notifyConnectStudentDropped,
  notifyAdminTransportAttendancePending,
  type TransportNotifAudience,
  type TransportNotifCategory,
  type TransportNotifPriority,
  type TransportWorkflowNotification,
  type TransportNotificationSnapshot,
  type PushTransportNotificationInput,
} from "./transport-notification-bridge";
export {
  subscribeTransportRealtime,
  type TransportRealtimeEvent,
  type TransportRealtimeTable,
  type SubscribeTransportRealtimeOptions,
} from "./transport-realtime";
export {
  loadDashboardLayout,
  saveDashboardLayout,
  resetDashboardLayout,
  visibleDashboardOrder,
  moveDashboardWidget,
  moveDashboardWidgetByDelta,
  hideDashboardWidget,
  showDashboardWidget,
  type DashboardLayoutState,
} from "./dashboard-layout";
export {
  SIMPLE_UPLOAD_LIMITS,
  compressImageToDataUrl,
  processSimpleUpload,
  simpleUploadAccept,
  simpleUploadExtensions,
  simpleUploadLimitLabel,
  isAllowedSimpleUploadName,
  isPdfFile,
  isImageFile,
  type SimpleUploadKind,
  type SimpleUploadValue,
} from "./simple-upload";
export {
  downloadToDevice,
  downloadTextToDevice,
  downloadBlobToDevice,
  downloadDataUrlToDevice,
  type DeviceDownloadInput,
} from "./device-download";
export {
  LUMENX_FEEDBACK_STORAGE_KEY,
  LUMENX_FEEDBACK_CHANGED_EVENT,
  LUMENX_FEEDBACK_KINDS,
  loadLumenXFeedback,
  submitLumenXFeedback,
  lumenXFeedbackKindLabel,
  type LumenXFeedbackKind,
  type LumenXFeedbackSource,
  type LumenXFeedbackEntry,
  type CreateLumenXFeedbackInput,
} from "./lumenx-feedback";
