/**
 * Standardized transport realtime / notification event kinds.
 * Payloads must be authenticated, institute-scoped, and idempotent via dedupeKey.
 */
export const TRANSPORT_EVENT = {
  TRIP_STARTED: "TRIP_STARTED",
  TRIP_PHASE_CHANGED: "TRIP_PHASE_CHANGED",
  GPS_UPDATED: "GPS_UPDATED",
  STOP_APPROACHING: "STOP_APPROACHING",
  STOP_ARRIVED: "STOP_ARRIVED",
  STUDENT_BOARDED: "STUDENT_BOARDED",
  STUDENT_NOT_BOARDED: "STUDENT_NOT_BOARDED",
  STUDENT_DROPPED: "STUDENT_DROPPED",
  TRIP_COMPLETED: "TRIP_COMPLETED",
  TRIP_DELAYED: "TRIP_DELAYED",
  EMERGENCY_CREATED: "EMERGENCY_CREATED",
  EMERGENCY_RESOLVED: "EMERGENCY_RESOLVED",
  NOT_RIDING_CREATED: "NOT_RIDING_CREATED",
  NOT_RIDING_CANCELLED: "NOT_RIDING_CANCELLED",
  SCHOOL_ARRIVED: "SCHOOL_ARRIVED",
  GPS_STALE: "GPS_STALE",
  GPS_OFFLINE: "GPS_OFFLINE",
  GPS_RECOVERED: "GPS_RECOVERED",
  TRIP_NOT_STARTED: "TRIP_NOT_STARTED",
  STOP_MISSED: "STOP_MISSED",
  TRANSPORT_ISSUE: "TRANSPORT_ISSUE",
  SERVICE_REMINDER: "SERVICE_REMINDER",
  PICKUP_REMINDER: "PICKUP_REMINDER",
} as const;

export type TransportEventKind =
  (typeof TRANSPORT_EVENT)[keyof typeof TRANSPORT_EVENT];
