#!/usr/bin/env node
/**
 * Production build — bundle API entry to dist/index.js (Node ESM).
 * Uses esbuild so packaging is not blocked by pre-existing tsc soft errors;
 * runtime behavior is covered by vitest.
 */
import * as esbuild from "esbuild";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const outdir = join(root, "dist");
const outfile = join(outdir, "index.js");

rmSync(outdir, { recursive: true, force: true });
mkdirSync(outdir, { recursive: true });

await esbuild.build({
  entryPoints: [join(root, "src", "index.ts")],
  bundle: true,
  platform: "node",
  target: "node20",
  format: "esm",
  outfile,
  packages: "external",
  sourcemap: true,
  logLevel: "info",
  banner: {
    js: "// LumenX API production bundle — generated by scripts/build.mjs",
  },
});

writeFileSync(
  join(outdir, "package.json"),
  JSON.stringify({ type: "module" }, null, 2) + "\n",
);

console.log(`Built ${outfile}`);
