/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegistrationsRouteImport } from './routes/registrations'
import { Route as RecycleRouteImport } from './routes/recycle'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PlatformUsersRouteImport } from './routes/platform-users'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NotificationTemplatesRouteImport } from './routes/notification-templates'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as InstitutesRouteImport } from './routes/institutes'
import { Route as HealthRisksRouteImport } from './routes/health-risks'
import { Route as GuardianLinksRouteImport } from './routes/guardian-links'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstitutesIndexRouteImport } from './routes/institutes.index'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as InstitutesIdRouteImport } from './routes/institutes.$id'

const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationsRoute = RegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const RecycleRoute = RecycleRouteImport.update({
  id: '/recycle',
  path: '/recycle',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformUsersRoute = PlatformUsersRouteImport.update({
  id: '/platform-users',
  path: '/platform-users',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationTemplatesRoute = NotificationTemplatesRouteImport.update({
  id: '/notification-templates',
  path: '/notification-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutesRoute = InstitutesRouteImport.update({
  id: '/institutes',
  path: '/institutes',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRisksRoute = HealthRisksRouteImport.update({
  id: '/health-risks',
  path: '/health-risks',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianLinksRoute = GuardianLinksRouteImport.update({
  id: '/guardian-links',
  path: '/guardian-links',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutesIndexRoute = InstitutesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstitutesRoute,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentsRoute,
} as any)
const InstitutesIdRoute = InstitutesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InstitutesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/accounts': typeof AccountsRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/audit': typeof AuditRoute
  '/billing': typeof BillingRoute
  '/certificates': typeof CertificatesRoute
  '/classes': typeof ClassesRoute
  '/complaints': typeof ComplaintsRoute
  '/events': typeof EventsRoute
  '/exams': typeof ExamsRoute
  '/guardian-links': typeof GuardianLinksRoute
  '/health-risks': typeof HealthRisksRoute
  '/institutes': typeof InstitutesRouteWithChildren
  '/modules': typeof ModulesRoute
  '/notification-templates': typeof NotificationTemplatesRoute
  '/notifications': typeof NotificationsRoute
  '/parents': typeof ParentsRoute
  '/permissions': typeof PermissionsRoute
  '/platform-users': typeof PlatformUsersRoute
  '/policies': typeof PoliciesRoute
  '/recycle': typeof RecycleRoute
  '/registrations': typeof RegistrationsRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/students': typeof StudentsRouteWithChildren
  '/support': typeof SupportRoute
  '/teachers': typeof TeachersRoute
  '/templates': typeof TemplatesRoute
  '/timetable': typeof TimetableRoute
  '/institutes/$id': typeof InstitutesIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/institutes/': typeof InstitutesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/accounts': typeof AccountsRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/audit': typeof AuditRoute
  '/billing': typeof BillingRoute
  '/certificates': typeof CertificatesRoute
  '/classes': typeof ClassesRoute
  '/complaints': typeof ComplaintsRoute
  '/events': typeof EventsRoute
  '/exams': typeof ExamsRoute
  '/guardian-links': typeof GuardianLinksRoute
  '/health-risks': typeof HealthRisksRoute
  '/modules': typeof ModulesRoute
  '/notification-templates': typeof NotificationTemplatesRoute
  '/notifications': typeof NotificationsRoute
  '/parents': typeof ParentsRoute
  '/permissions': typeof PermissionsRoute
  '/platform-users': typeof PlatformUsersRoute
  '/policies': typeof PoliciesRoute
  '/recycle': typeof RecycleRoute
  '/registrations': typeof RegistrationsRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/students': typeof StudentsRouteWithChildren
  '/support': typeof SupportRoute
  '/teachers': typeof TeachersRoute
  '/templates': typeof TemplatesRoute
  '/timetable': typeof TimetableRoute
  '/institutes/$id': typeof InstitutesIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/institutes': typeof InstitutesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/accounts': typeof AccountsRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/attendance': typeof AttendanceRoute
  '/audit': typeof AuditRoute
  '/billing': typeof BillingRoute
  '/certificates': typeof CertificatesRoute
  '/classes': typeof ClassesRoute
  '/complaints': typeof ComplaintsRoute
  '/events': typeof EventsRoute
  '/exams': typeof ExamsRoute
  '/guardian-links': typeof GuardianLinksRoute
  '/health-risks': typeof HealthRisksRoute
  '/institutes': typeof InstitutesRouteWithChildren
  '/modules': typeof ModulesRoute
  '/notification-templates': typeof NotificationTemplatesRoute
  '/notifications': typeof NotificationsRoute
  '/parents': typeof ParentsRoute
  '/permissions': typeof PermissionsRoute
  '/platform-users': typeof PlatformUsersRoute
  '/policies': typeof PoliciesRoute
  '/recycle': typeof RecycleRoute
  '/registrations': typeof RegistrationsRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/students': typeof StudentsRouteWithChildren
  '/support': typeof SupportRoute
  '/teachers': typeof TeachersRoute
  '/templates': typeof TemplatesRoute
  '/timetable': typeof TimetableRoute
  '/institutes/$id': typeof InstitutesIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/institutes/': typeof InstitutesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/accounts'
    | '/alerts'
    | '/analytics'
    | '/announcements'
    | '/attendance'
    | '/audit'
    | '/billing'
    | '/certificates'
    | '/classes'
    | '/complaints'
    | '/events'
    | '/exams'
    | '/guardian-links'
    | '/health-risks'
    | '/institutes'
    | '/modules'
    | '/notification-templates'
    | '/notifications'
    | '/parents'
    | '/permissions'
    | '/platform-users'
    | '/policies'
    | '/recycle'
    | '/registrations'
    | '/settings'
    | '/storage'
    | '/students'
    | '/support'
    | '/teachers'
    | '/templates'
    | '/timetable'
    | '/institutes/$id'
    | '/students/$id'
    | '/institutes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/accounts'
    | '/alerts'
    | '/analytics'
    | '/announcements'
    | '/attendance'
    | '/audit'
    | '/billing'
    | '/certificates'
    | '/classes'
    | '/complaints'
    | '/events'
    | '/exams'
    | '/guardian-links'
    | '/health-risks'
    | '/modules'
    | '/notification-templates'
    | '/notifications'
    | '/parents'
    | '/permissions'
    | '/platform-users'
    | '/policies'
    | '/recycle'
    | '/registrations'
    | '/settings'
    | '/storage'
    | '/students'
    | '/support'
    | '/teachers'
    | '/templates'
    | '/timetable'
    | '/institutes/$id'
    | '/students/$id'
    | '/institutes'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/accounts'
    | '/alerts'
    | '/analytics'
    | '/announcements'
    | '/attendance'
    | '/audit'
    | '/billing'
    | '/certificates'
    | '/classes'
    | '/complaints'
    | '/events'
    | '/exams'
    | '/guardian-links'
    | '/health-risks'
    | '/institutes'
    | '/modules'
    | '/notification-templates'
    | '/notifications'
    | '/parents'
    | '/permissions'
    | '/platform-users'
    | '/policies'
    | '/recycle'
    | '/registrations'
    | '/settings'
    | '/storage'
    | '/students'
    | '/support'
    | '/teachers'
    | '/templates'
    | '/timetable'
    | '/institutes/$id'
    | '/students/$id'
    | '/institutes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AccountsRoute: typeof AccountsRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AttendanceRoute: typeof AttendanceRoute
  AuditRoute: typeof AuditRoute
  BillingRoute: typeof BillingRoute
  CertificatesRoute: typeof CertificatesRoute
  ClassesRoute: typeof ClassesRoute
  ComplaintsRoute: typeof ComplaintsRoute
  EventsRoute: typeof EventsRoute
  ExamsRoute: typeof ExamsRoute
  GuardianLinksRoute: typeof GuardianLinksRoute
  HealthRisksRoute: typeof HealthRisksRoute
  InstitutesRoute: typeof InstitutesRouteWithChildren
  ModulesRoute: typeof ModulesRoute
  NotificationTemplatesRoute: typeof NotificationTemplatesRoute
  NotificationsRoute: typeof NotificationsRoute
  ParentsRoute: typeof ParentsRoute
  PermissionsRoute: typeof PermissionsRoute
  PlatformUsersRoute: typeof PlatformUsersRoute
  PoliciesRoute: typeof PoliciesRoute
  RecycleRoute: typeof RecycleRoute
  RegistrationsRoute: typeof RegistrationsRoute
  SettingsRoute: typeof SettingsRoute
  StorageRoute: typeof StorageRoute
  StudentsRoute: typeof StudentsRouteWithChildren
  SupportRoute: typeof SupportRoute
  TeachersRoute: typeof TeachersRoute
  TemplatesRoute: typeof TemplatesRoute
  TimetableRoute: typeof TimetableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrations': {
      id: '/registrations'
      path: '/registrations'
      fullPath: '/registrations'
      preLoaderRoute: typeof RegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recycle': {
      id: '/recycle'
      path: '/recycle'
      fullPath: '/recycle'
      preLoaderRoute: typeof RecycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-users': {
      id: '/platform-users'
      path: '/platform-users'
      fullPath: '/platform-users'
      preLoaderRoute: typeof PlatformUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification-templates': {
      id: '/notification-templates'
      path: '/notification-templates'
      fullPath: '/notification-templates'
      preLoaderRoute: typeof NotificationTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutes': {
      id: '/institutes'
      path: '/institutes'
      fullPath: '/institutes'
      preLoaderRoute: typeof InstitutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-risks': {
      id: '/health-risks'
      path: '/health-risks'
      fullPath: '/health-risks'
      preLoaderRoute: typeof HealthRisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian-links': {
      id: '/guardian-links'
      path: '/guardian-links'
      fullPath: '/guardian-links'
      preLoaderRoute: typeof GuardianLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutes/': {
      id: '/institutes/'
      path: '/'
      fullPath: '/institutes/'
      preLoaderRoute: typeof InstitutesIndexRouteImport
      parentRoute: typeof InstitutesRoute
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/institutes/$id': {
      id: '/institutes/$id'
      path: '/$id'
      fullPath: '/institutes/$id'
      preLoaderRoute: typeof InstitutesIdRouteImport
      parentRoute: typeof InstitutesRoute
    }
  }
}

interface InstitutesRouteChildren {
  InstitutesIdRoute: typeof InstitutesIdRoute
  InstitutesIndexRoute: typeof InstitutesIndexRoute
}

const InstitutesRouteChildren: InstitutesRouteChildren = {
  InstitutesIdRoute: InstitutesIdRoute,
  InstitutesIndexRoute: InstitutesIndexRoute,
}

const InstitutesRouteWithChildren = InstitutesRoute._addFileChildren(
  InstitutesRouteChildren,
)

interface StudentsRouteChildren {
  StudentsIdRoute: typeof StudentsIdRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsIdRoute: StudentsIdRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AccountsRoute: AccountsRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AttendanceRoute: AttendanceRoute,
  AuditRoute: AuditRoute,
  BillingRoute: BillingRoute,
  CertificatesRoute: CertificatesRoute,
  ClassesRoute: ClassesRoute,
  ComplaintsRoute: ComplaintsRoute,
  EventsRoute: EventsRoute,
  ExamsRoute: ExamsRoute,
  GuardianLinksRoute: GuardianLinksRoute,
  HealthRisksRoute: HealthRisksRoute,
  InstitutesRoute: InstitutesRouteWithChildren,
  ModulesRoute: ModulesRoute,
  NotificationTemplatesRoute: NotificationTemplatesRoute,
  NotificationsRoute: NotificationsRoute,
  ParentsRoute: ParentsRoute,
  PermissionsRoute: PermissionsRoute,
  PlatformUsersRoute: PlatformUsersRoute,
  PoliciesRoute: PoliciesRoute,
  RecycleRoute: RecycleRoute,
  RegistrationsRoute: RegistrationsRoute,
  SettingsRoute: SettingsRoute,
  StorageRoute: StorageRoute,
  StudentsRoute: StudentsRouteWithChildren,
  SupportRoute: SupportRoute,
  TeachersRoute: TeachersRoute,
  TemplatesRoute: TemplatesRoute,
  TimetableRoute: TimetableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
