import type { SportsArchiveRecord } from "./types";

/** Records archived only via the Archive module (no native archive status in source). */
export const manualArchiveRecordsSeed: SportsArchiveRecord[] = [
  {
    id: "arc-att-1",
    sourceModule: "attendance",
    sourceId: "att-arch-1",
    title: "Football Practice Attendance — 12 Mar",
    subtitle: "Senior Football Team · 22 students",
    academicYear: "2025–26",
    teamId: "team-football",
    teamName: "Senior Football Team",
    sportType: "football",
    archivedAt: "2025-05-20",
    archivedBy: "Coach Vikram Singh",
    reason: "Session records consolidated into annual report.",
    status: "archived",
    summary: "Present: 20 · Absent: 2",
  },
  {
    id: "arc-cn-1",
    sourceModule: "coach_notes",
    sourceId: "cnote-arch-1",
    title: "Coach Note — Priya Nair",
    subtitle: "Swimming · Class 9-B",
    academicYear: "2025–26",
    teamId: "team-swimming",
    teamName: "Swimming Team",
    sportType: "swimming",
    archivedAt: "2025-04-10",
    archivedBy: "Coach Meera Iyer",
    reason: "Student transferred — notes archived.",
    status: "archived",
    summary: "Performance: excellent · Follow-up completed",
  },
  {
    id: "arc-mr-1",
    sourceModule: "match_results",
    sourceId: "mres-arch-1",
    title: "Cricket Invitational Final Result",
    subtitle: "Cricket Team vs Senior Football Team",
    academicYear: "2024–25",
    teamId: "team-cricket",
    teamName: "Cricket Team",
    sportType: "cricket",
    archivedAt: "2025-11-20",
    archivedBy: "Sports Coordinator",
    reason: "Season results filed to archive.",
    status: "archived",
    summary: "Winner: Cricket Team",
  },
  {
    id: "arc-ach-1",
    sourceModule: "achievements",
    sourceId: "ach-arch-1",
    title: "District Football MVP — Arjun Mehta",
    subtitle: "Duplicate recognition record",
    academicYear: "2025–26",
    teamId: "team-football",
    teamName: "Senior Football Team",
    sportType: "football",
    archivedAt: "2025-03-15",
    archivedBy: "Sports Coordinator",
    reason: "Duplicate entry removed — original retained.",
    status: "archived",
  },
  {
    id: "arc-cert-1",
    sourceModule: "certificates",
    sourceId: "cert-arch-1",
    title: "Certificate LX-2024-0892 — Sneha Patel",
    subtitle: "Participation certificate (superseded)",
    academicYear: "2024–25",
    teamId: "team-athletics",
    teamName: "Athletics Team",
    sportType: "athletics",
    archivedAt: "2025-02-28",
    archivedBy: "Admin Office",
    reason: "Certificate reissued — old version archived.",
    status: "archived",
  },
];
