import type {
  GeneratedDocument,
  TemplateActivity,
  TemplateBlock,
  TemplateRecord,
} from "./types";
import { defaultVisualFields, themeForCategory } from "./visual-themes";

function blocks(...items: TemplateBlock[]): TemplateBlock[] {
  return items;
}

function withVisual(
  template: Omit<TemplateRecord, "layoutMode" | "visualTheme" | "visualFields"> &
    Partial<Pick<TemplateRecord, "visualTheme" | "visualFields">>,
): TemplateRecord {
  const theme = template.visualTheme ?? themeForCategory(template.categoryId);
  return {
    ...template,
    layoutMode: "visual",
    visualTheme: theme,
    visualFields:
      template.visualFields ??
      defaultVisualFields(theme, "LumenX International School", "Dr. Alistair Vance"),
  };
}

const bonafideBlocks = blocks(
  { id: "b1", type: "logo", label: "Institute logo" },
  { id: "b2", type: "header", label: "Header", content: "BONAFIDE CERTIFICATE" },
  {
    id: "b3",
    type: "text",
    label: "Body",
    content:
      "This is to certify that {{StudentName}}, admission no. {{AdmissionNumber}}, is a bonafide student of {{InstituteName}}, studying in Class {{Class}}-{{Section}} for the academic year {{AcademicYear}}.",
  },
  { id: "b4", type: "signature", label: "Principal signature" },
  { id: "b5", type: "variable", label: "Certificate no.", variable: "CertificateNumber" },
  { id: "b6", type: "qr", label: "Verification QR" },
);

export const SYSTEM_TEMPLATES: TemplateRecord[] = [
  withVisual({
    id: "tpl-sys-bonafide",
    name: "Bonafide Certificate — Ornate",
    kind: "certificate",
    categoryId: "bonafide_certificate",
    source: "system",
    status: "active",
    tags: ["official", "bonafide"],
    favorite: true,
    usageCount: 842,
    version: 3,
    updatedAt: "2026-05-12",
    createdAt: "2024-01-10",
    description: "Standard bonafide layout with institute branding and QR verification.",
    blocks: bonafideBlocks,
    previewAspect: "a4",
  }),
  withVisual({
    id: "tpl-sys-conduct",
    name: "Conduct Certificate",
    kind: "certificate",
    categoryId: "conduct_certificate",
    source: "system",
    status: "active",
    tags: ["conduct", "character"],
    favorite: false,
    usageCount: 312,
    version: 2,
    updatedAt: "2026-04-02",
    createdAt: "2024-03-15",
    description: "Character and conduct certificate for students.",
    blocks: blocks(
      { id: "c1", type: "header", label: "Header", content: "CERTIFICATE OF CONDUCT" },
      {
        id: "c2",
        type: "text",
        label: "Body",
        content:
          "{{StudentName}} of Class {{Class}}-{{Section}} has exhibited exemplary conduct during {{AcademicYear}}.",
      },
      { id: "c3", type: "signature", label: "Principal signature" },
    ),
    previewAspect: "a4",
  }),
  withVisual({
    id: "tpl-sys-achievement",
    name: "Certificate of Achievement — Elegant",
    kind: "certificate",
    categoryId: "academic_excellence",
    source: "system",
    status: "active",
    tags: ["achievement", "award", "elegant"],
    favorite: true,
    usageCount: 524,
    version: 1,
    updatedAt: "2026-06-20",
    createdAt: "2026-01-01",
    description:
      "Decorative award certificate with script name, gold seal, and signature blocks — like formal achievement certificates.",
    blocks: bonafideBlocks,
    previewAspect: "a4",
    visualTheme: "achievement_elegant",
  }),
  withVisual({
    id: "tpl-sys-progress",
    name: "Progress Report — Term",
    kind: "report",
    categoryId: "progress_reports",
    source: "system",
    status: "active",
    tags: ["academic", "term"],
    favorite: true,
    usageCount: 1204,
    version: 5,
    updatedAt: "2026-06-01",
    createdAt: "2023-08-01",
    description: "Term-wise progress report with subject table and remarks.",
    blocks: blocks(
      { id: "r1", type: "header", label: "Header", content: "PROGRESS REPORT" },
      { id: "r2", type: "table", label: "Marks table" },
      { id: "r3", type: "section", label: "Teacher remarks" },
      { id: "r4", type: "signature", label: "Class teacher signature" },
    ),
    previewAspect: "a4",
  }),
  withVisual({
    id: "tpl-sys-annual",
    name: "Annual Report Card",
    kind: "report",
    categoryId: "annual_reports",
    source: "system",
    status: "active",
    tags: ["annual", "report card"],
    favorite: false,
    usageCount: 980,
    version: 4,
    updatedAt: "2026-05-28",
    createdAt: "2023-08-01",
    description: "Full-year academic summary with co-scholastic grades.",
    blocks: blocks(
      { id: "a1", type: "header", label: "Header", content: "ANNUAL REPORT CARD" },
      { id: "a2", type: "table", label: "Subject performance" },
      { id: "a3", type: "section", label: "Attendance summary" },
    ),
    previewAspect: "a4",
  }),
  withVisual({
    id: "tpl-sys-student-id",
    name: "Student ID — Standard",
    kind: "id_card",
    categoryId: "student_id",
    source: "system",
    status: "active",
    tags: ["id", "student", "qr"],
    favorite: true,
    usageCount: 2842,
    version: 6,
    updatedAt: "2026-06-10",
    createdAt: "2023-06-01",
    description: "Front and back student ID with photo, barcode, and QR.",
    blocks: blocks(
      { id: "i1", type: "logo", label: "Institute logo" },
      { id: "i2", type: "image", label: "Student photo" },
      { id: "i3", type: "variable", label: "Name", variable: "StudentName" },
      { id: "i4", type: "barcode", label: "Barcode" },
      { id: "i5", type: "qr", label: "QR code" },
    ),
    previewAspect: "id_card",
  }),
  withVisual({
    id: "tpl-sys-teacher-id",
    name: "Teacher ID — Professional",
    kind: "id_card",
    categoryId: "teacher_id",
    source: "system",
    status: "active",
    tags: ["id", "teacher"],
    favorite: false,
    usageCount: 186,
    version: 2,
    updatedAt: "2026-03-20",
    createdAt: "2024-02-01",
    description: "Staff identification card for faculty.",
    blocks: blocks(
      { id: "t1", type: "logo", label: "Institute logo" },
      { id: "t2", type: "variable", label: "Name", variable: "TeacherName" },
      { id: "t3", type: "qr", label: "QR code" },
    ),
    previewAspect: "id_card",
  }),
  withVisual({
    id: "tpl-sys-sports-winner",
    name: "Sports Winner Certificate",
    kind: "certificate",
    categoryId: "sports_winner",
    source: "system",
    status: "active",
    tags: ["sports", "winner"],
    favorite: false,
    usageCount: 156,
    version: 1,
    updatedAt: "2026-02-14",
    createdAt: "2025-01-01",
    description: "Winner certificate for sports events.",
    blocks: blocks(
      { id: "s1", type: "header", label: "Header", content: "CERTIFICATE OF EXCELLENCE" },
      {
        id: "s2",
        type: "text",
        label: "Body",
        content:
          "{{StudentName}} is awarded for outstanding performance in {{EventName}} — {{Achievement}}.",
      },
      { id: "s3", type: "seal", label: "Institute seal" },
    ),
    previewAspect: "a4",
  }),
  withVisual({
    id: "tpl-sys-science-fair",
    name: "Science Fair Participation",
    kind: "certificate",
    categoryId: "science_fair",
    source: "system",
    status: "active",
    tags: ["extra-curricular", "science"],
    favorite: false,
    usageCount: 89,
    version: 1,
    updatedAt: "2026-01-08",
    createdAt: "2025-06-01",
    description: "Participation certificate for science fair projects.",
    blocks: blocks(
      { id: "e1", type: "header", label: "Header", content: "PARTICIPATION CERTIFICATE" },
      { id: "e2", type: "text", label: "Body", content: "{{StudentName}} participated in {{EventName}}." },
    ),
    previewAspect: "a4",
  }),
  withVisual({
    id: "tpl-sys-transfer",
    name: "Transfer Certificate — Board Format",
    kind: "document",
    categoryId: "transfer_certificate",
    source: "system",
    status: "active",
    tags: ["tc", "official"],
    favorite: true,
    usageCount: 421,
    version: 3,
    updatedAt: "2026-05-01",
    createdAt: "2023-09-01",
    description: "Transfer certificate aligned to regional board layout.",
    blocks: blocks(
      { id: "d1", type: "header", label: "Header", content: "TRANSFER CERTIFICATE" },
      { id: "d2", type: "table", label: "Academic record" },
      { id: "d3", type: "watermark", label: "Official watermark" },
    ),
    previewAspect: "a4",
  }),
  withVisual({
    id: "tpl-sys-marksheet",
    name: "Mark Sheet — Semester",
    kind: "document",
    categoryId: "mark_sheets",
    source: "system",
    status: "active",
    tags: ["marks", "semester"],
    favorite: false,
    usageCount: 670,
    version: 2,
    updatedAt: "2026-04-18",
    createdAt: "2024-01-01",
    description: "Semester mark sheet with grade breakdown.",
    blocks: blocks(
      { id: "m1", type: "header", label: "Header", content: "STATEMENT OF MARKS" },
      { id: "m2", type: "table", label: "Marks grid" },
    ),
    previewAspect: "a4",
  }),

  // ── Additional system templates ───────────────────────────────────────────

  withVisual({
    id: "tpl-sys-character",
    name: "Character Certificate",
    kind: "certificate",
    categoryId: "conduct_certificate",
    source: "system",
    status: "active",
    tags: ["character", "official"],
    favorite: false,
    usageCount: 198,
    version: 2,
    updatedAt: "2026-03-10",
    createdAt: "2024-04-01",
    description: "Official character certificate with principal endorsement and school seal.",
    blocks: blocks(
      { id: "ch1", type: "logo", label: "Institute logo" },
      { id: "ch2", type: "header", label: "Header", content: "CHARACTER CERTIFICATE" },
      { id: "ch3", type: "text", label: "Body", content: "This is to certify that {{StudentName}} of Class {{Class}}-{{Section}} has been of good character and conduct during {{AcademicYear}}." },
      { id: "ch4", type: "seal", label: "Institute seal" },
      { id: "ch5", type: "signature", label: "Principal signature" },
    ),
    previewAspect: "a4",
  }),

  withVisual({
    id: "tpl-sys-study",
    name: "Study Certificate",
    kind: "certificate",
    categoryId: "study_certificate",
    source: "system",
    status: "active",
    tags: ["study", "enrollment"],
    favorite: false,
    usageCount: 302,
    version: 1,
    updatedAt: "2026-02-20",
    createdAt: "2024-05-01",
    description: "Confirms student enrollment and study status for the current academic year.",
    blocks: blocks(
      { id: "st1", type: "logo", label: "Institute logo" },
      { id: "st2", type: "header", label: "Header", content: "STUDY CERTIFICATE" },
      { id: "st3", type: "text", label: "Body", content: "Certified that {{StudentName}}, Roll No. {{RollNumber}}, is presently studying in Class {{Class}}-{{Section}} of {{InstituteName}} during {{AcademicYear}}." },
      { id: "st4", type: "signature", label: "Principal signature" },
      { id: "st5", type: "qr", label: "Verification QR" },
    ),
    previewAspect: "a4",
  }),

  withVisual({
    id: "tpl-sys-attendance-cert",
    name: "Attendance Excellence Certificate",
    kind: "certificate",
    categoryId: "attendance_excellence",
    source: "system",
    status: "active",
    tags: ["attendance", "achievement", "annual"],
    favorite: false,
    usageCount: 241,
    version: 1,
    updatedAt: "2026-04-15",
    createdAt: "2025-01-15",
    description: "Awarded to students who maintained 95%+ attendance throughout the academic year.",
    blocks: blocks(
      { id: "at1", type: "header", label: "Header", content: "CERTIFICATE OF ATTENDANCE EXCELLENCE" },
      { id: "at2", type: "text", label: "Body", content: "This certificate is awarded to {{StudentName}} for maintaining exemplary attendance of 95% or above during {{AcademicYear}}." },
      { id: "at3", type: "seal", label: "Institute seal" },
      { id: "at4", type: "signature", label: "Principal signature" },
    ),
    previewAspect: "a4",
    visualTheme: "achievement_elegant",
  }),

  withVisual({
    id: "tpl-sys-sports-participation",
    name: "Sports Participation Certificate",
    kind: "certificate",
    categoryId: "sports_participation",
    source: "system",
    status: "active",
    tags: ["sports", "participation"],
    favorite: false,
    usageCount: 378,
    version: 2,
    updatedAt: "2026-01-20",
    createdAt: "2024-08-01",
    description: "Standard participation certificate for sports events, competitions, and tournaments.",
    blocks: blocks(
      { id: "sp1", type: "header", label: "Header", content: "CERTIFICATE OF PARTICIPATION" },
      { id: "sp2", type: "text", label: "Body", content: "This is to certify that {{StudentName}} of Class {{Class}}-{{Section}} participated in {{EventName}} held on {{IssueDate}}." },
      { id: "sp3", type: "seal", label: "Institute seal" },
      { id: "sp4", type: "signature", label: "Sports Director" },
    ),
    previewAspect: "a4",
    visualTheme: "sports_medal",
  }),

  withVisual({
    id: "tpl-sys-semester-report",
    name: "Semester Report Card",
    kind: "report",
    categoryId: "semester_reports",
    source: "system",
    status: "active",
    tags: ["semester", "mid-term", "grades"],
    favorite: true,
    usageCount: 726,
    version: 3,
    updatedAt: "2026-05-15",
    createdAt: "2023-09-01",
    description: "Semester-end report with subject-wise marks, grades, and class teacher remarks.",
    blocks: blocks(
      { id: "sr1", type: "logo", label: "Institute logo" },
      { id: "sr2", type: "header", label: "Header", content: "SEMESTER REPORT CARD" },
      { id: "sr3", type: "table", label: "Subject marks & grades" },
      { id: "sr4", type: "section", label: "Attendance summary" },
      { id: "sr5", type: "section", label: "Teacher remarks" },
      { id: "sr6", type: "signature", label: "Class teacher & principal" },
    ),
    previewAspect: "a4",
    visualTheme: "report_card_modern",
  }),

  withVisual({
    id: "tpl-sys-staff-id",
    name: "Staff ID Card — Standard",
    kind: "id_card",
    categoryId: "staff_id",
    source: "system",
    status: "active",
    tags: ["id", "staff", "admin"],
    favorite: false,
    usageCount: 92,
    version: 1,
    updatedAt: "2026-03-05",
    createdAt: "2025-01-01",
    description: "Administrative staff ID card with department and contact info.",
    blocks: blocks(
      { id: "sf1", type: "logo", label: "Institute logo" },
      { id: "sf2", type: "image", label: "Staff photo" },
      { id: "sf3", type: "variable", label: "Name", variable: "TeacherName" },
      { id: "sf4", type: "barcode", label: "Barcode" },
    ),
    previewAspect: "id_card",
    visualTheme: "teacher_id_professional",
  }),

  withVisual({
    id: "tpl-sys-visitor-pass",
    name: "Visitor Pass",
    kind: "id_card",
    categoryId: "visitor_pass",
    source: "system",
    status: "active",
    tags: ["visitor", "guest", "pass"],
    favorite: false,
    usageCount: 44,
    version: 1,
    updatedAt: "2026-02-01",
    createdAt: "2025-02-01",
    description: "Temporary visitor pass for campus guests with visit purpose and date.",
    blocks: blocks(
      { id: "vp1", type: "logo", label: "Institute logo" },
      { id: "vp2", type: "header", label: "Header", content: "VISITOR PASS" },
      { id: "vp3", type: "variable", label: "Visitor name", variable: "StudentName" },
      { id: "vp4", type: "variable", label: "Visit date", variable: "IssueDate" },
      { id: "vp5", type: "qr", label: "Check-in QR" },
    ),
    previewAspect: "id_card",
  }),

  withVisual({
    id: "tpl-sys-migration",
    name: "Migration Certificate",
    kind: "document",
    categoryId: "migration_certificate",
    source: "system",
    status: "active",
    tags: ["migration", "board transfer"],
    favorite: false,
    usageCount: 58,
    version: 1,
    updatedAt: "2026-04-10",
    createdAt: "2025-01-01",
    description: "Board-level migration certificate for students switching examination boards.",
    blocks: blocks(
      { id: "mg1", type: "logo", label: "Institute logo" },
      { id: "mg2", type: "header", label: "Header", content: "MIGRATION CERTIFICATE" },
      { id: "mg3", type: "text", label: "Body", content: "Certified that {{StudentName}} has completed studies up to Class {{Class}} at {{InstituteName}} and is hereby granted this migration certificate." },
      { id: "mg4", type: "watermark", label: "Official watermark" },
      { id: "mg5", type: "signature", label: "Principal signature" },
    ),
    previewAspect: "a4",
    visualTheme: "transfer_official",
  }),

  withVisual({
    id: "tpl-sys-toppers-cert",
    name: "Subject Topper Certificate",
    kind: "certificate",
    categoryId: "top_performer",
    source: "system",
    status: "active",
    tags: ["academic", "topper", "merit"],
    favorite: false,
    usageCount: 134,
    version: 1,
    updatedAt: "2026-06-01",
    createdAt: "2025-03-01",
    description: "Recognises the top scorer in a subject for the academic term or year.",
    blocks: blocks(
      { id: "tp1", type: "header", label: "Header", content: "CERTIFICATE OF ACADEMIC MERIT" },
      { id: "tp2", type: "text", label: "Body", content: "This certificate is awarded to {{StudentName}} for securing the highest marks in {{EventName}} during {{AcademicYear}}." },
      { id: "tp3", type: "seal", label: "Institute seal" },
      { id: "tp4", type: "signature", label: "Principal signature" },
    ),
    previewAspect: "a4",
    visualTheme: "achievement_elegant",
  }),

  withVisual({
    id: "tpl-sys-dance-cert",
    name: "Dance & Performing Arts Certificate",
    kind: "certificate",
    categoryId: "dance",
    source: "system",
    status: "active",
    tags: ["dance", "arts", "extra-curricular"],
    favorite: false,
    usageCount: 67,
    version: 1,
    updatedAt: "2025-12-10",
    createdAt: "2025-06-01",
    description: "Appreciation certificate for dance and performing arts competitions.",
    blocks: blocks(
      { id: "dc1", type: "header", label: "Header", content: "CERTIFICATE OF APPRECIATION" },
      { id: "dc2", type: "text", label: "Body", content: "{{StudentName}} is recognized for outstanding performance in {{EventName}} at {{InstituteName}}." },
      { id: "dc3", type: "signature", label: "Principal & Director of Arts" },
    ),
    previewAspect: "a4",
    visualTheme: "participation_colorful",
  }),

  // ── Imported templates ────────────────────────────────────────────────────

  withVisual({
    id: "tpl-imp-cbse-tc",
    name: "CBSE Transfer Certificate — Board Standard",
    kind: "document",
    categoryId: "transfer_certificate",
    source: "imported",
    status: "active",
    tags: ["cbse", "tc", "board", "official"],
    favorite: false,
    usageCount: 88,
    version: 1,
    updatedAt: "2026-04-01",
    createdAt: "2026-01-15",
    description: "Official CBSE transfer certificate format imported from the Board portal. Includes all mandatory fields per CBSE circular 2024.",
    blocks: blocks(
      { id: "ci1", type: "header", label: "Header", content: "TRANSFER CERTIFICATE" },
      { id: "ci2", type: "text", label: "Body", content: "Certified that {{StudentName}}, Adm. No. {{AdmissionNumber}}, attended {{InstituteName}} from {{AcademicYear}} and is hereby transferred." },
      { id: "ci3", type: "table", label: "Academic record" },
      { id: "ci4", type: "watermark", label: "Official CBSE watermark" },
      { id: "ci5", type: "signature", label: "Principal signature + school stamp" },
    ),
    previewAspect: "a4",
  }),

  withVisual({
    id: "tpl-imp-cbse-progress",
    name: "CBSE Progress Report — Standard Format",
    kind: "report",
    categoryId: "progress_reports",
    source: "imported",
    status: "active",
    tags: ["cbse", "report card", "board format"],
    favorite: false,
    usageCount: 156,
    version: 2,
    updatedAt: "2026-05-10",
    createdAt: "2025-09-01",
    description: "CBSE-prescribed progress report format with scholastic and co-scholastic areas, as per the CCE guidelines.",
    blocks: blocks(
      { id: "cr1", type: "logo", label: "Institute logo" },
      { id: "cr2", type: "header", label: "Header", content: "PROGRESS REPORT — CCE FORMAT" },
      { id: "cr3", type: "table", label: "Scholastic areas" },
      { id: "cr4", type: "table", label: "Co-scholastic activities" },
      { id: "cr5", type: "section", label: "Health & physical education" },
      { id: "cr6", type: "signature", label: "Class teacher & principal" },
    ),
    previewAspect: "a4",
    visualTheme: "report_card_modern",
  }),

  withVisual({
    id: "tpl-imp-state-id",
    name: "State Education Dept — Student ID",
    kind: "id_card",
    categoryId: "student_id",
    source: "imported",
    status: "active",
    tags: ["state", "government", "id", "official"],
    favorite: false,
    usageCount: 312,
    version: 1,
    updatedAt: "2026-03-15",
    createdAt: "2026-01-01",
    description: "Student ID template as prescribed by the State Education Department, with government emblem and unique student UDISE+ ID.",
    blocks: blocks(
      { id: "si1", type: "logo", label: "State emblem + school logo" },
      { id: "si2", type: "image", label: "Student photo" },
      { id: "si3", type: "variable", label: "UDISE+ ID", variable: "AdmissionNumber" },
      { id: "si4", type: "variable", label: "Student name", variable: "StudentName" },
      { id: "si5", type: "qr", label: "Verification QR — UDISE+" },
    ),
    previewAspect: "id_card",
    visualTheme: "student_id_blue",
  }),

  withVisual({
    id: "tpl-imp-kvs-bonafide",
    name: "KVS Bonafide Format",
    kind: "certificate",
    categoryId: "bonafide_certificate",
    source: "imported",
    status: "active",
    tags: ["kvs", "bonafide", "central school"],
    favorite: false,
    usageCount: 42,
    version: 1,
    updatedAt: "2026-02-10",
    createdAt: "2025-11-01",
    description: "Bonafide certificate template imported from Kendriya Vidyalaya Sangathan format. Suitable for KVS-affiliated institutes.",
    blocks: blocks(
      { id: "kb1", type: "logo", label: "KVS logo + institute logo" },
      { id: "kb2", type: "header", label: "Header", content: "BONAFIDE CERTIFICATE" },
      { id: "kb3", type: "text", label: "Body", content: "This is to certify that {{StudentName}}, S/D/O of {{ParentName}}, is a bona-fide student of {{InstituteName}}." },
      { id: "kb4", type: "signature", label: "Principal with office stamp" },
    ),
    previewAspect: "a4",
    visualTheme: "bonafide_ornate",
  }),

  withVisual({
    id: "tpl-imp-regional-marksheet",
    name: "Regional Board — Mark Statement",
    kind: "document",
    categoryId: "mark_sheets",
    source: "imported",
    status: "active",
    tags: ["board", "marksheet", "regional", "official"],
    favorite: false,
    usageCount: 74,
    version: 1,
    updatedAt: "2026-01-25",
    createdAt: "2025-10-01",
    description: "Official mark statement template from the Regional Board of Secondary Education. Pre-formatted with required authentication fields.",
    blocks: blocks(
      { id: "rm1", type: "header", label: "Header", content: "STATEMENT OF MARKS — REGIONAL BOARD" },
      { id: "rm2", type: "table", label: "Subject-wise marks" },
      { id: "rm3", type: "variable", label: "Certificate no.", variable: "CertificateNumber" },
      { id: "rm4", type: "barcode", label: "Board barcode" },
      { id: "rm5", type: "watermark", label: "Board watermark" },
    ),
    previewAspect: "a4",
    visualTheme: "marksheet_grid",
  }),

  withVisual({
    id: "tpl-imp-navodaya-cert",
    name: "Navodaya — Achievement Certificate",
    kind: "certificate",
    categoryId: "academic_excellence",
    source: "imported",
    status: "active",
    tags: ["navodaya", "achievement", "government"],
    favorite: false,
    usageCount: 29,
    version: 1,
    updatedAt: "2026-01-10",
    createdAt: "2025-08-01",
    description: "Achievement certificate template imported from Navodaya Vidyalaya Samiti. Formal award design with NVS emblem.",
    blocks: blocks(
      { id: "na1", type: "logo", label: "NVS emblem + school logo" },
      { id: "na2", type: "header", label: "Header", content: "CERTIFICATE OF ACADEMIC ACHIEVEMENT" },
      { id: "na3", type: "text", label: "Body", content: "This certificate is proudly awarded to {{StudentName}} in recognition of outstanding academic performance during {{AcademicYear}}." },
      { id: "na4", type: "seal", label: "Official seal" },
      { id: "na5", type: "signature", label: "Principal and Regional Director" },
    ),
    previewAspect: "a4",
    visualTheme: "achievement_elegant",
  }),
];

// Helper: default empty workflow fields for draft docs
function draft(base: Omit<GeneratedDocument, "workflowState" | "workflowHistory" | "publishedAt" | "portalVisibility" | "notificationsSent" | "notificationCount" | "rejectionReason" | "notifications" | "documentGroupId" | "versionNumber" | "isCurrentVersion" | "versionChanges" | "versionNote">): GeneratedDocument {
  return {
    ...base,
    workflowState: "draft",
    workflowHistory: [{ state: "draft", actor: base.generatedBy, at: base.generatedAt }],
    publishedAt: null,
    portalVisibility: { student: false, parent: false, teacher: false },
    notificationsSent: false,
    notificationCount: 0,
    rejectionReason: null,
    notifications: [],
    documentGroupId: base.id,
    versionNumber: 1,
    isCurrentVersion: true,
    versionChanges: "",
    versionNote: "",
  };
}

export const SEED_GENERATED: GeneratedDocument[] = [
  // ══════════════════════════════════════════════════════════════════════════════
  // GROUP: grp-bonafide-aanya  (3 versions — v1 rejected, v2 old, v3 current)
  // ══════════════════════════════════════════════════════════════════════════════

  // v1 — Rejected: incorrect name spelling
  {
    id: "gen-v1-bonafide-aanya",
    templateId: "tpl-sys-bonafide",
    templateName: "Bonafide Certificate — Classic",
    kind: "certificate",
    recipientName: "Anya Sharma",
    recipientRef: "STU-1042",
    generatedAt: "2026-06-08T09:00:00",
    generatedBy: "Admin User",
    batchId: "batch-870",
    status: "ready",
    certificateNumber: "LXA/CERT/2026/0098",
    workflowState: "rejected",
    workflowHistory: [
      { state: "draft", actor: "Admin User", at: "2026-06-08T09:00:00" },
      { state: "published", actor: "Admin User", at: "2026-06-08T09:10:00" },
      { state: "rejected", actor: "Mrs. Priya Nair", at: "2026-06-10T08:00:00", comment: "Name misspelled — should be 'Aanya' not 'Anya'. Please regenerate." },
    ],
    publishedAt: "2026-06-08T09:10:00",
    portalVisibility: { student: false, parent: false, teacher: false },
    notificationsSent: false,
    notificationCount: 0,
    rejectionReason: "Name misspelled — should be 'Aanya' not 'Anya'. Please regenerate.",
    notifications: [],
    documentGroupId: "grp-bonafide-aanya",
    versionNumber: 1,
    isCurrentVersion: false,
    versionChanges: "Initial issue",
    versionNote: "Rejected: student name was entered incorrectly",
  },

  // v2 — Superseded: wrong class section (XII-A should be XII-B)
  {
    id: "gen-v2-bonafide-aanya",
    templateId: "tpl-sys-bonafide",
    templateName: "Bonafide Certificate — Classic",
    kind: "certificate",
    recipientName: "Aanya Sharma",
    recipientRef: "STU-1042",
    generatedAt: "2026-06-10T11:00:00",
    generatedBy: "Admin User",
    batchId: "batch-874",
    status: "ready",
    certificateNumber: "LXA/CERT/2026/0112",
    workflowState: "published",
    workflowHistory: [
      { state: "draft", actor: "Admin User", at: "2026-06-10T11:00:00" },
      { state: "published", actor: "Mrs. Priya Nair", at: "2026-06-10T12:00:00", comment: "Name corrected. Published." },
    ],
    publishedAt: "2026-06-10T12:00:00",
    portalVisibility: { student: false, parent: false, teacher: false },
    notificationsSent: false,
    notificationCount: 0,
    rejectionReason: null,
    notifications: [],
    documentGroupId: "grp-bonafide-aanya",
    versionNumber: 2,
    isCurrentVersion: false,
    versionChanges: "Name corrected: 'Anya' → 'Aanya Sharma'",
    versionNote: "Superseded: class section XII-A was incorrect",
  },

  // v3 — Current published version
  {
    id: "gen-1001",
    templateId: "tpl-sys-bonafide",
    templateName: "Bonafide Certificate — Classic",
    kind: "certificate",
    recipientName: "Aanya Sharma",
    recipientRef: "STU-1042",
    generatedAt: "2026-06-18T10:24:00",
    generatedBy: "Admin User",
    batchId: "batch-882",
    status: "ready",
    certificateNumber: "LXA/CERT/2026/0142",
    workflowState: "published",
    workflowHistory: [
      { state: "draft", actor: "Admin User", at: "2026-06-18T10:24:00" },
      { state: "published", actor: "Mrs. Priya Nair", at: "2026-06-18T11:00:00", comment: "Class section corrected. Final version approved." },
    ],
    publishedAt: "2026-06-18T11:00:00",
    portalVisibility: { student: true, parent: true, teacher: false },
    notificationsSent: true,
    notificationCount: 2,
    rejectionReason: null,
    notifications: [
      { id: "notif-g1001-s", documentId: "gen-1001", documentName: "Bonafide Certificate — Classic", recipientName: "Aanya Sharma", recipientPortal: "student", channel: "in_app", sentAt: "2026-06-18T11:01:00", readAt: "2026-06-18T14:32:00" },
      { id: "notif-g1001-p", documentId: "gen-1001", documentName: "Bonafide Certificate — Classic", recipientName: "Rajiv Sharma (Parent)", recipientPortal: "parent", channel: "email", sentAt: "2026-06-18T11:01:00", readAt: null },
    ],
    documentGroupId: "grp-bonafide-aanya",
    versionNumber: 3,
    isCurrentVersion: true,
    versionChanges: "Class section updated from XII-A to XII-B",
    versionNote: "Current version — final and approved",
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // GROUP: grp-report-aarav  (2 versions — v1 old, v2 current)
  // ══════════════════════════════════════════════════════════════════════════════

  // v1 — Superseded: Mathematics marks were incorrect
  {
    id: "gen-v1-report-aarav",
    templateId: "tpl-sys-progress",
    templateName: "Progress Report — Term",
    kind: "report",
    recipientName: "Ethan Wright",
    recipientRef: "STU-1044",
    generatedAt: "2026-06-10T08:00:00",
    generatedBy: "Dr. Priya Menon",
    batchId: "batch-report-12a-v1",
    status: "ready",
    workflowState: "published",
    workflowHistory: [
      { state: "draft", actor: "Dr. Priya Menon", at: "2026-06-10T08:00:00" },
      { state: "teacher_review", actor: "Dr. Priya Menon", at: "2026-06-10T08:10:00" },
      { state: "admin_review", actor: "Mr. Ajay Sharma", at: "2026-06-10T09:00:00" },
      { state: "published", actor: "Mrs. Priya Nair", at: "2026-06-10T10:00:00" },
    ],
    publishedAt: "2026-06-10T10:00:00",
    portalVisibility: { student: false, parent: false, teacher: false },
    notificationsSent: false,
    notificationCount: 0,
    rejectionReason: null,
    notifications: [],
    documentGroupId: "grp-report-aarav",
    versionNumber: 1,
    isCurrentVersion: false,
    versionChanges: "Initial publication",
    versionNote: "Superseded: Mathematics marks were entered as 78, should be 85",
  },

  // v2 — Current published version
  {
    id: "gen-1008",
    templateId: "tpl-sys-progress",
    templateName: "Progress Report — Term",
    kind: "report",
    recipientName: "Ethan Wright",
    recipientRef: "STU-1044",
    generatedAt: "2026-06-13T08:00:00",
    generatedBy: "Dr. Priya Menon",
    batchId: "batch-report-12a",
    status: "ready",
    workflowState: "published",
    workflowHistory: [
      { state: "draft", actor: "Dr. Priya Menon", at: "2026-06-13T08:00:00" },
      { state: "teacher_review", actor: "Dr. Priya Menon", at: "2026-06-13T08:05:00" },
      { state: "admin_review", actor: "Mr. Ajay Sharma", at: "2026-06-13T10:00:00", comment: "Corrected marks verified" },
      { state: "published", actor: "Mrs. Priya Nair", at: "2026-06-13T11:30:00", comment: "Published to all portals" },
    ],
    publishedAt: "2026-06-13T11:30:00",
    portalVisibility: { student: true, parent: true, teacher: true },
    notificationsSent: true,
    notificationCount: 3,
    rejectionReason: null,
    notifications: [
      { id: "notif-g1008-s", documentId: "gen-1008", documentName: "Progress Report — Term", recipientName: "Ethan Wright", recipientPortal: "student", channel: "in_app", sentAt: "2026-06-13T11:30:00", readAt: "2026-06-13T14:00:00" },
      { id: "notif-g1008-p", documentId: "gen-1008", documentName: "Progress Report — Term", recipientName: "S. Wright (Parent)", recipientPortal: "parent", channel: "email", sentAt: "2026-06-13T11:30:00", readAt: "2026-06-13T18:22:00" },
      { id: "notif-g1008-t", documentId: "gen-1008", documentName: "Progress Report — Term", recipientName: "Mr. Ajay Sharma (Teacher)", recipientPortal: "teacher", channel: "in_app", sentAt: "2026-06-13T11:30:00", readAt: "2026-06-13T12:05:00" },
    ],
    documentGroupId: "grp-report-aarav",
    versionNumber: 2,
    isCurrentVersion: true,
    versionChanges: "Mathematics marks corrected from 78 to 85; re-verified by class teacher",
    versionNote: "Final corrected version — approved by VP",
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // SINGLE-VERSION DOCUMENTS
  // ══════════════════════════════════════════════════════════════════════════════

  // Admin Review: Progress Report (Priya Patel) — in workflow, no version yet
  {
    id: "gen-1002",
    templateId: "tpl-sys-progress",
    templateName: "Progress Report — Term",
    kind: "report",
    recipientName: "Priya Patel",
    recipientRef: "STU-1048",
    generatedAt: "2026-06-17T14:00:00",
    generatedBy: "Dr. Priya Menon",
    batchId: "batch-881",
    status: "ready",
    workflowState: "admin_review",
    workflowHistory: [
      { state: "draft", actor: "Dr. Priya Menon", at: "2026-06-17T14:00:00" },
      { state: "teacher_review", actor: "Dr. Priya Menon", at: "2026-06-17T14:05:00", comment: "Sent for teacher review" },
      { state: "admin_review", actor: "Mr. Vikram Tiwari", at: "2026-06-17T16:30:00", comment: "Teacher approved — forwarding for admin review" },
    ],
    publishedAt: null,
    portalVisibility: { student: false, parent: false, teacher: false },
    notificationsSent: false,
    notificationCount: 0,
    rejectionReason: null,
    notifications: [],
    documentGroupId: "gen-1002",
    versionNumber: 1,
    isCurrentVersion: false,
    versionChanges: "",
    versionNote: "",
  },

  // Published: Student ID (Marcus Lee) — single version
  {
    id: "gen-1003",
    templateId: "tpl-sys-student-id",
    templateName: "Student ID — Standard",
    kind: "id_card",
    recipientName: "Marcus Lee",
    recipientRef: "STU-1047",
    generatedAt: "2026-06-16T09:12:00",
    generatedBy: "Admin User",
    status: "ready",
    workflowState: "published",
    workflowHistory: [
      { state: "draft", actor: "Admin User", at: "2026-06-16T09:12:00" },
      { state: "published", actor: "Admin User", at: "2026-06-16T09:15:00" },
    ],
    publishedAt: "2026-06-16T09:15:00",
    portalVisibility: { student: true, parent: false, teacher: false },
    notificationsSent: true,
    notificationCount: 1,
    rejectionReason: null,
    notifications: [
      { id: "notif-g1003-s", documentId: "gen-1003", documentName: "Student ID — Standard", recipientName: "Marcus Lee", recipientPortal: "student", channel: "in_app", sentAt: "2026-06-16T09:15:00", readAt: "2026-06-16T10:02:00" },
    ],
    documentGroupId: "gen-1003",
    versionNumber: 1,
    isCurrentVersion: true,
    versionChanges: "",
    versionNote: "Single version — no corrections needed",
  },

  // Draft: Sports Winner Certificate (Julian Draxler)
  {
    id: "gen-1004",
    templateId: "tpl-sys-sports-winner",
    templateName: "Sports Winner Certificate",
    kind: "certificate",
    recipientName: "Julian Draxler",
    recipientRef: "STU-1043",
    generatedAt: "2026-06-15T16:45:00",
    generatedBy: "Sports Dept",
    batchId: "batch-sports-12",
    status: "ready",
    certificateNumber: "LXA/SPT/2026/0088",
    workflowState: "draft",
    workflowHistory: [
      { state: "draft", actor: "Sports Dept", at: "2026-06-15T16:45:00" },
    ],
    publishedAt: null,
    portalVisibility: { student: false, parent: false, teacher: false },
    notificationsSent: false,
    notificationCount: 0,
    rejectionReason: null,
    notifications: [],
    documentGroupId: "gen-1004",
    versionNumber: 1,
    isCurrentVersion: false,
    versionChanges: "",
    versionNote: "",
  },

  // Draft: Transfer Certificate (Alina Moreno)
  draft({
    id: "gen-1005",
    templateId: "tpl-sys-transfer",
    templateName: "Transfer Certificate — Board Format",
    kind: "document",
    recipientName: "Alina Moreno",
    recipientRef: "STU-1046",
    generatedAt: "2026-06-19T09:00:00",
    generatedBy: "Mr. Vikram Tiwari",
    batchId: "batch-tc-06",
    status: "ready",
    certificateNumber: "LXA/TC/2026/0031",
  }),

  // Teacher Review: Annual Report (Omar Haddad)
  {
    id: "gen-1006",
    templateId: "tpl-sys-annual",
    templateName: "Annual Report Card",
    kind: "report",
    recipientName: "Omar Haddad",
    recipientRef: "STU-1049",
    generatedAt: "2026-06-18T15:00:00",
    generatedBy: "Admin User",
    batchId: "batch-annual-11",
    status: "ready",
    workflowState: "teacher_review",
    workflowHistory: [
      { state: "draft", actor: "Admin User", at: "2026-06-18T15:00:00" },
      { state: "teacher_review", actor: "Admin User", at: "2026-06-18T15:05:00", comment: "Submitted for teacher review" },
    ],
    publishedAt: null,
    portalVisibility: { student: false, parent: false, teacher: false },
    notificationsSent: false,
    notificationCount: 0,
    rejectionReason: null,
    notifications: [],
    documentGroupId: "gen-1006",
    versionNumber: 1,
    isCurrentVersion: false,
    versionChanges: "",
    versionNote: "",
  },

  // Published: Conduct Certificate (Sana Khan) — single version
  {
    id: "gen-1007",
    templateId: "tpl-sys-conduct",
    templateName: "Conduct Certificate",
    kind: "certificate",
    recipientName: "Sana Khan",
    recipientRef: "STU-1045",
    generatedAt: "2026-06-14T11:20:00",
    generatedBy: "Mrs. Priya Nair",
    status: "ready",
    certificateNumber: "LXA/COND/2026/0019",
    workflowState: "published",
    workflowHistory: [
      { state: "draft", actor: "Mrs. Priya Nair", at: "2026-06-14T11:20:00" },
      { state: "published", actor: "Dr. Ramesh Kumar", at: "2026-06-14T12:00:00", comment: "Signed and published" },
    ],
    publishedAt: "2026-06-14T12:00:00",
    portalVisibility: { student: true, parent: true, teacher: false },
    notificationsSent: true,
    notificationCount: 2,
    rejectionReason: null,
    notifications: [
      { id: "notif-g1007-s", documentId: "gen-1007", documentName: "Conduct Certificate", recipientName: "Sana Khan", recipientPortal: "student", channel: "in_app", sentAt: "2026-06-14T12:00:00", readAt: "2026-06-14T13:14:00" },
      { id: "notif-g1007-p", documentId: "gen-1007", documentName: "Conduct Certificate", recipientName: "I. Khan (Parent)", recipientPortal: "parent", channel: "sms", sentAt: "2026-06-14T12:00:00", readAt: null },
    ],
    documentGroupId: "gen-1007",
    versionNumber: 1,
    isCurrentVersion: true,
    versionChanges: "",
    versionNote: "Single version — no corrections",
  },

  // Published: Academic Excellence (Marcus Lee)
  {
    id: "gen-1009",
    templateId: "tpl-sys-achievement",
    templateName: "Academic Excellence Award",
    kind: "certificate",
    recipientName: "Marcus Lee",
    recipientRef: "STU-1047",
    generatedAt: "2026-06-12T10:00:00",
    generatedBy: "Admin User",
    status: "ready",
    certificateNumber: "LXA/EXC/2026/0044",
    workflowState: "published",
    workflowHistory: [
      { state: "draft", actor: "Admin User", at: "2026-06-12T10:00:00" },
      { state: "published", actor: "Mrs. Priya Nair", at: "2026-06-12T11:00:00" },
    ],
    publishedAt: "2026-06-12T11:00:00",
    portalVisibility: { student: true, parent: true, teacher: false },
    notificationsSent: true,
    notificationCount: 1,
    rejectionReason: null,
    notifications: [],
    documentGroupId: "gen-1009",
    versionNumber: 1,
    isCurrentVersion: true,
    versionChanges: "",
    versionNote: "Single version",
  },

  // Published: Study Certificate (Priya Patel)
  {
    id: "gen-1010",
    templateId: "tpl-sys-study",
    templateName: "Study Certificate",
    kind: "certificate",
    recipientName: "Priya Patel",
    recipientRef: "STU-1048",
    generatedAt: "2026-06-11T09:30:00",
    generatedBy: "Admin User",
    status: "ready",
    certificateNumber: "LXA/STD/2026/0021",
    workflowState: "published",
    workflowHistory: [
      { state: "draft", actor: "Admin User", at: "2026-06-11T09:30:00" },
      { state: "published", actor: "Admin User", at: "2026-06-11T10:00:00" },
    ],
    publishedAt: "2026-06-11T10:00:00",
    portalVisibility: { student: true, parent: true, teacher: false },
    notificationsSent: false,
    notificationCount: 0,
    rejectionReason: null,
    notifications: [],
    documentGroupId: "gen-1010",
    versionNumber: 1,
    isCurrentVersion: true,
    versionChanges: "",
    versionNote: "Single version",
  },
];

export const SEED_ACTIVITY: TemplateActivity[] = [
  {
    id: "act-1",
    action: "generated",
    templateName: "Bonafide Certificate — Classic",
    detail: "Batch · 42 students",
    at: "2026-06-18T10:24:00",
    actor: "Admin User",
  },
  {
    id: "act-2",
    action: "duplicated",
    templateName: "Progress Report — Term",
    detail: "Custom variant for Term 2",
    at: "2026-06-17T11:00:00",
    actor: "Dr. Priya Menon",
  },
  {
    id: "act-3",
    action: "imported",
    templateName: "Regional TC Format",
    detail: "From board_tc_2026.docx",
    at: "2026-06-16T15:30:00",
    actor: "Admin User",
  },
  {
    id: "act-4",
    action: "edited",
    templateName: "Student ID — Standard",
    detail: "Version 6 · QR layout",
    at: "2026-06-10T09:00:00",
    actor: "IT Admin",
  },
];
