/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppMoreRouteImport } from './routes/_app/more'
import { Route as AppEmergencyRouteImport } from './routes/_app/emergency'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppMoreIndexRouteImport } from './routes/_app/more/index'
import { Route as AppMoreSupportRouteImport } from './routes/_app/more/support'
import { Route as AppMoreSettingsRouteImport } from './routes/_app/more/settings'
import { Route as AppMoreRouteSetupRouteImport } from './routes/_app/more/route-setup'
import { Route as AppMoreProfileRouteImport } from './routes/_app/more/profile'
import { Route as AppMoreBusInformationRouteImport } from './routes/_app/more/bus-information'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppEmergencyRoute = AppEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreIndexRoute = AppMoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMoreRoute,
} as any)
const AppMoreSupportRoute = AppMoreSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppMoreRoute,
} as any)
const AppMoreSettingsRoute = AppMoreSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppMoreRoute,
} as any)
const AppMoreRouteSetupRoute = AppMoreRouteSetupRouteImport.update({
  id: '/route-setup',
  path: '/route-setup',
  getParentRoute: () => AppMoreRoute,
} as any)
const AppMoreProfileRoute = AppMoreProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppMoreRoute,
} as any)
const AppMoreBusInformationRoute = AppMoreBusInformationRouteImport.update({
  id: '/bus-information',
  path: '/bus-information',
  getParentRoute: () => AppMoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/attendance': typeof AppAttendanceRoute
  '/emergency': typeof AppEmergencyRoute
  '/more': typeof AppMoreRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/more/bus-information': typeof AppMoreBusInformationRoute
  '/more/profile': typeof AppMoreProfileRoute
  '/more/route-setup': typeof AppMoreRouteSetupRoute
  '/more/settings': typeof AppMoreSettingsRoute
  '/more/support': typeof AppMoreSupportRoute
  '/more/': typeof AppMoreIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/attendance': typeof AppAttendanceRoute
  '/emergency': typeof AppEmergencyRoute
  '/notifications': typeof AppNotificationsRoute
  '/': typeof AppIndexRoute
  '/more/bus-information': typeof AppMoreBusInformationRoute
  '/more/profile': typeof AppMoreProfileRoute
  '/more/route-setup': typeof AppMoreRouteSetupRoute
  '/more/settings': typeof AppMoreSettingsRoute
  '/more/support': typeof AppMoreSupportRoute
  '/more': typeof AppMoreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/emergency': typeof AppEmergencyRoute
  '/_app/more': typeof AppMoreRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/more/bus-information': typeof AppMoreBusInformationRoute
  '/_app/more/profile': typeof AppMoreProfileRoute
  '/_app/more/route-setup': typeof AppMoreRouteSetupRoute
  '/_app/more/settings': typeof AppMoreSettingsRoute
  '/_app/more/support': typeof AppMoreSupportRoute
  '/_app/more/': typeof AppMoreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/attendance'
    | '/emergency'
    | '/more'
    | '/notifications'
    | '/more/bus-information'
    | '/more/profile'
    | '/more/route-setup'
    | '/more/settings'
    | '/more/support'
    | '/more/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/attendance'
    | '/emergency'
    | '/notifications'
    | '/'
    | '/more/bus-information'
    | '/more/profile'
    | '/more/route-setup'
    | '/more/settings'
    | '/more/support'
    | '/more'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/attendance'
    | '/_app/emergency'
    | '/_app/more'
    | '/_app/notifications'
    | '/_app/'
    | '/_app/more/bus-information'
    | '/_app/more/profile'
    | '/_app/more/route-setup'
    | '/_app/more/settings'
    | '/_app/more/support'
    | '/_app/more/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/emergency': {
      id: '/_app/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AppEmergencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more/': {
      id: '/_app/more/'
      path: '/'
      fullPath: '/more/'
      preLoaderRoute: typeof AppMoreIndexRouteImport
      parentRoute: typeof AppMoreRoute
    }
    '/_app/more/support': {
      id: '/_app/more/support'
      path: '/support'
      fullPath: '/more/support'
      preLoaderRoute: typeof AppMoreSupportRouteImport
      parentRoute: typeof AppMoreRoute
    }
    '/_app/more/settings': {
      id: '/_app/more/settings'
      path: '/settings'
      fullPath: '/more/settings'
      preLoaderRoute: typeof AppMoreSettingsRouteImport
      parentRoute: typeof AppMoreRoute
    }
    '/_app/more/route-setup': {
      id: '/_app/more/route-setup'
      path: '/route-setup'
      fullPath: '/more/route-setup'
      preLoaderRoute: typeof AppMoreRouteSetupRouteImport
      parentRoute: typeof AppMoreRoute
    }
    '/_app/more/profile': {
      id: '/_app/more/profile'
      path: '/profile'
      fullPath: '/more/profile'
      preLoaderRoute: typeof AppMoreProfileRouteImport
      parentRoute: typeof AppMoreRoute
    }
    '/_app/more/bus-information': {
      id: '/_app/more/bus-information'
      path: '/bus-information'
      fullPath: '/more/bus-information'
      preLoaderRoute: typeof AppMoreBusInformationRouteImport
      parentRoute: typeof AppMoreRoute
    }
  }
}

interface AppMoreRouteChildren {
  AppMoreBusInformationRoute: typeof AppMoreBusInformationRoute
  AppMoreProfileRoute: typeof AppMoreProfileRoute
  AppMoreRouteSetupRoute: typeof AppMoreRouteSetupRoute
  AppMoreSettingsRoute: typeof AppMoreSettingsRoute
  AppMoreSupportRoute: typeof AppMoreSupportRoute
  AppMoreIndexRoute: typeof AppMoreIndexRoute
}

const AppMoreRouteChildren: AppMoreRouteChildren = {
  AppMoreBusInformationRoute: AppMoreBusInformationRoute,
  AppMoreProfileRoute: AppMoreProfileRoute,
  AppMoreRouteSetupRoute: AppMoreRouteSetupRoute,
  AppMoreSettingsRoute: AppMoreSettingsRoute,
  AppMoreSupportRoute: AppMoreSupportRoute,
  AppMoreIndexRoute: AppMoreIndexRoute,
}

const AppMoreRouteWithChildren =
  AppMoreRoute._addFileChildren(AppMoreRouteChildren)

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppEmergencyRoute: typeof AppEmergencyRoute
  AppMoreRoute: typeof AppMoreRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppEmergencyRoute: AppEmergencyRoute,
  AppMoreRoute: AppMoreRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
