import { MODULE_IDS } from "@lumenx/config/module-ids";

export const MODULE_ID = MODULE_IDS.notifications;
export const MIN_PLAN = "core" as const;
export const OWNER_APP = "admin" as const;
export const MODULE_NAME = "Notifications";

export * from "./templates";

/** Phase 5–6 notification helpers (re-exported from foundation). */
export {
  notifyAdmissionsLifecycle,
  admissionsStageToLifecycle,
  notifyCareersLifecycle,
  careersStatusToLifecycle,
  publishBroadcastNotification,
  notifyDirectMessage,
  notifyHomeworkAssigned,
  notifyHomeworkReminder,
  notifyHomeworkSubmitted,
  notifyHomeworkNotSubmitted,
  notifyHomeworkDuePassed,
  cancelHomeworkReminders,
  notifyFeeAdded,
  notifyFeeDue,
  notifyFeeDueReminder,
  notifyFeeOverdue,
  notifyFeePaymentReceived,
  notifyFeeReceiptAvailable,
  listFeesParentInbox,
  pushFeesParentInbox,
  notifyTeacherOfStudentLeave,
  notifyParentLeavePending,
  notifyParentLeaveDecision,
  notifyAdminOfTeacherLeave,
  notifyTeacherLeavePending,
  notifyTeacherLeaveDecision,
  notifyDiaryReminderDemo,
  notifyExamTimetablePublished,
  notifyExamReminder,
  notifyExamScheduleChange,
  notifyExamResultsPublished,
  notifyTeacherMarksPending,
  notifyTeacherMarksDeadline,
  notifyTeacherMarksPublishPending,
  notifyAdminMarksPending,
  notifyAdminResultsReady,
  scheduleExamPaperReminders,
  notifyEventPublished,
  notifyEventChanged,
  notifyEventCancelled,
  scheduleEventReminders,
  notifyTimetablePublished,
  notifyTimetableChanged,
  listPhase7Inbox,
  cancelPhase7Reminders,
  notifyComplaintLifecycle,
  notifyComplaintSubmitted,
  notifyDocumentRequestReceived,
  notifyDocumentRequestApproved,
  notifyDocumentRequestRejected,
  notifyDocumentGenerated,
  notifyDocumentReady,
  notifyCertificateIssued,
  notifyCertificatePublished,
  notifySystemOpsCritical,
  notifySecurityEvent,
  notifyAccountSecurityChange,
  notifyMaintenance,
  notifySystemWarning,
  listPhase8Inbox,
  dedupeNotificationsById,
  ensureNotificationHref,
  isImportantNotification,
} from "@lumenx/notifications";
