import type {
  CommunicationAnnouncementInput,
  SportsCommunicationAnnouncement,
} from "./types";
import { defaultCommunicationNotificationPrefs } from "./types";

export function cloneAnnouncement(
  a: SportsCommunicationAnnouncement,
): SportsCommunicationAnnouncement {
  return {
    ...a,
    audience: { ...a.audience } as SportsCommunicationAnnouncement["audience"],
    notifications: { ...a.notifications },
  };
}

export function createAnnouncementFromInput(
  input: CommunicationAnnouncementInput,
  id?: string,
  status: SportsCommunicationAnnouncement["status"] = "draft",
): SportsCommunicationAnnouncement {
  const now = new Date().toISOString().slice(0, 10);
  return {
    id: id ?? `comm-${Date.now()}`,
    title: input.title.trim(),
    body: input.body.trim(),
    category: input.category,
    messageType: input.messageType,
    status,
    audience: input.audience,
    notifications: { ...input.notifications },
    scheduledDate: input.scheduledDate,
    scheduledTime: input.scheduledTime,
    createdBy: input.createdBy.trim(),
    createdAt: now,
    updatedAt: now,
  };
}

export const announcementsSeed: SportsCommunicationAnnouncement[] = [
  {
    id: "comm-1",
    title: "Senior Football — Saturday Practice Reminder",
    body: "Practice session at Main Football Ground, 7:00 AM. Bring studs and water bottles.",
    category: "practice_reminder",
    messageType: "reminder",
    status: "sent",
    audience: {
      type: "teams",
      teamIds: ["team-football"],
      teamLabels: ["Senior Football Team"],
    },
    notifications: {
      notifyAudience: true,
      notifyParents: true,
      notifyTeachers: false,
      notifyCoaches: true,
    },
    sentAt: "2026-03-08T07:00:00",
    createdBy: "Coach Vikram Singh",
    createdAt: "2026-03-07",
    updatedAt: "2026-03-08",
  },
  {
    id: "comm-2",
    title: "District Basketball Match — Transport Details",
    body: "Bus departs at 1:30 PM from main gate. Students must carry institute ID.",
    category: "match_reminder",
    messageType: "information",
    status: "scheduled",
    audience: {
      type: "teams",
      teamIds: ["team-basketball"],
      teamLabels: ["Basketball Team"],
    },
    notifications: {
      notifyAudience: true,
      notifyParents: true,
      notifyTeachers: true,
      notifyCoaches: true,
    },
    scheduledDate: "2026-03-14",
    scheduledTime: "12:00",
    createdBy: "Sports Coordinator",
    createdAt: "2026-03-06",
    updatedAt: "2026-03-06",
  },
  {
    id: "comm-3",
    title: "Inter-House Tournament — Opening Ceremony",
    body: "All sports teams assemble at the main ground at 8:30 AM on 20 March.",
    category: "tournament_announcement",
    messageType: "general_announcement",
    status: "scheduled",
    audience: { type: "entire_institute" },
    notifications: {
      notifyAudience: true,
      notifyParents: false,
      notifyTeachers: true,
      notifyCoaches: true,
    },
    scheduledDate: "2026-03-19",
    scheduledTime: "18:00",
    createdBy: "Principal Office",
    createdAt: "2026-03-05",
    updatedAt: "2026-03-05",
  },
  {
    id: "comm-4",
    title: "Congratulations — State Swimming Champions",
    body: "Priya Nair and the swimming team won gold at the state meet. Assembly honour on Monday.",
    category: "student_notification",
    messageType: "congratulations",
    status: "sent",
    audience: {
      type: "teams",
      teamIds: ["team-swimming"],
      teamLabels: ["Swimming Team"],
    },
    notifications: {
      notifyAudience: true,
      notifyParents: true,
      notifyTeachers: true,
      notifyCoaches: false,
    },
    sentAt: "2026-03-04T10:30:00",
    createdBy: "Coach Meera Iyer",
    createdAt: "2026-03-04",
    updatedAt: "2026-03-04",
  },
  {
    id: "comm-5",
    title: "Emergency — Pool Maintenance Closure",
    body: "Olympic Swimming Pool closed until 12 March due to filtration repair. No aquatic sessions.",
    category: "emergency_notice",
    messageType: "emergency",
    status: "sent",
    audience: { type: "entire_institute" },
    notifications: {
      notifyAudience: true,
      notifyParents: true,
      notifyTeachers: true,
      notifyCoaches: true,
    },
    sentAt: "2026-03-03T09:00:00",
    createdBy: "Facilities Manager",
    createdAt: "2026-03-03",
    updatedAt: "2026-03-03",
  },
  {
    id: "comm-6",
    title: "Coach Meeting — Season Planning",
    body: "All sports coaches meet in Conference Room B, Friday 4 PM.",
    category: "coach_notification",
    messageType: "information",
    status: "sent",
    audience: { type: "entire_institute" },
    notifications: {
      notifyAudience: false,
      notifyParents: false,
      notifyTeachers: false,
      notifyCoaches: true,
    },
    sentAt: "2026-03-02T14:00:00",
    createdBy: "Sports Coordinator",
    createdAt: "2026-03-01",
    updatedAt: "2026-03-02",
  },
  {
    id: "comm-7",
    title: "Parent-Teacher Sports Review — Class 10",
    body: "Review of student sports participation for Class 10 parents on 25 March.",
    category: "parent_notification",
    messageType: "information",
    status: "cancelled",
    audience: { type: "classes", classNames: ["10"] },
    notifications: {
      notifyAudience: false,
      notifyParents: true,
      notifyTeachers: true,
      notifyCoaches: false,
    },
    scheduledDate: "2026-03-24",
    scheduledTime: "17:00",
    cancelledAt: "2026-03-05",
    createdBy: "Sports Coordinator",
    createdAt: "2026-02-28",
    updatedAt: "2026-03-05",
  },
  {
    id: "comm-8",
    title: "Cricket Selection Trials — Registration Open",
    body: "U-19 cricket trials on 28 Feb. Register with the sports office by 25 Feb.",
    category: "team_announcement",
    messageType: "general_announcement",
    status: "draft",
    audience: {
      type: "individual_students",
      studentIds: ["stu-1", "stu-11"],
    },
    notifications: defaultCommunicationNotificationPrefs(),
    createdBy: "Coach Ramesh Pillai",
    createdAt: "2026-02-20",
    updatedAt: "2026-02-20",
  },
];
