import type { RegisteredNotificationTemplate } from "../shared/registry/types";
import { NOTIFICATION_TEMPLATE_IDS as IDS } from "../shared/registry/ids";
import { extractAllowedVariables } from "../shared/registry/variables";
import { DEFAULT_DEEP_LINK } from "../shared/registry/legacy-map";

function daysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

function tpl(
  partial: Omit<RegisteredNotificationTemplate, "allowedVariables" | "deepLink"> & {
    allowedVariables?: readonly string[];
    deepLink?: string;
  },
): RegisteredNotificationTemplate {
  return {
    ...partial,
    allowedVariables:
      partial.allowedVariables ?? extractAllowedVariables(partial.title, partial.message),
    deepLink: partial.deepLink ?? DEFAULT_DEEP_LINK[partial.category],
  };
}

export const EXAMS_TEMPLATES: RegisteredNotificationTemplate[] = [
  tpl({
    templateId: IDS.exams.parent.marksPublished,
    category: "exams",
    audience: "parent",
    title: "Marks available",
    message: "{{examName}} marks for {{studentName}} are now available.",
    priority: "important",
    status: "published",
    version: "2.0.1",
    deepLink: "/exams",
    whereUsed: ["Admin Marks", "Connect parent"],
    updatedAt: daysAgo(7),
  }),
  tpl({
    templateId: IDS.exams.student.marksPublished,
    category: "exams",
    audience: "student",
    title: "Your marks are ready",
    message: "{{examName}} results have been published.",
    priority: "important",
    status: "published",
    version: "2.0.0",
    deepLink: "/exams",
    whereUsed: ["Connect student"],
    updatedAt: daysAgo(7),
  }),
  tpl({
    templateId: IDS.exams.parent.resultUpdated,
    category: "exams",
    audience: "parent",
    title: "Result updated",
    message: "{{examName}} · {{subject}} results were updated for {{studentName}}.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/exams",
    whereUsed: ["Admin Marks"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.student.resultUpdated,
    category: "exams",
    audience: "student",
    title: "Result updated",
    message: "{{examName}} · {{subject}} results were updated.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/exams",
    whereUsed: ["Admin Marks"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.parent.timetablePublished,
    category: "exams",
    audience: "parent",
    title: "Exam timetable published",
    message: "{{examName}} timetable is now available ({{dateRange}}).",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/exams",
    whereUsed: ["Admin Exams"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.student.timetablePublished,
    category: "exams",
    audience: "student",
    title: "Exam timetable published",
    message: "{{examName}} timetable is now available ({{dateRange}}).",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/exams",
    whereUsed: ["Admin Exams"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.teacher.timetablePublished,
    category: "exams",
    audience: "teacher",
    title: "Exam timetable published",
    message: "{{examName}} timetable published for {{classLabel}}.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/exams",
    whereUsed: ["Admin Exams"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.parent.reminder1d,
    category: "exams",
    audience: "parent",
    title: "Exam tomorrow",
    message: "{{examName}} · {{subject}} is tomorrow at {{time}} ({{venue}}).",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/exams",
    whereUsed: ["Admin Exams"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.student.reminder1d,
    category: "exams",
    audience: "student",
    title: "Exam tomorrow",
    message: "{{examName}} · {{subject}} is tomorrow at {{time}} ({{venue}}).",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/exams",
    whereUsed: ["Admin Exams"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.parent.reminder1h,
    category: "exams",
    audience: "parent",
    title: "Exam in 1 hour",
    message: "{{examName}} · {{subject}} starts at {{time}} ({{venue}}).",
    priority: "critical",
    status: "published",
    version: "1.0.0",
    deepLink: "/exams",
    whereUsed: ["Admin Exams"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.student.reminder1h,
    category: "exams",
    audience: "student",
    title: "Exam in 1 hour",
    message: "{{examName}} · {{subject}} starts at {{time}} ({{venue}}).",
    priority: "critical",
    status: "published",
    version: "1.0.0",
    deepLink: "/exams",
    whereUsed: ["Admin Exams"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.parent.dateChanged,
    category: "exams",
    audience: "parent",
    title: "Exam date changed",
    message: "{{examName}} · {{subject}}: new date {{newValue}}.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/exams",
    whereUsed: ["Admin Exams"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.student.dateChanged,
    category: "exams",
    audience: "student",
    title: "Exam date changed",
    message: "{{examName}} · {{subject}}: new date {{newValue}}.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/exams",
    whereUsed: ["Admin Exams"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.parent.timeChanged,
    category: "exams",
    audience: "parent",
    title: "Exam time changed",
    message: "{{examName}} · {{subject}}: new time {{newValue}}.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/exams",
    whereUsed: ["Admin Exams"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.student.timeChanged,
    category: "exams",
    audience: "student",
    title: "Exam time changed",
    message: "{{examName}} · {{subject}}: new time {{newValue}}.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/exams",
    whereUsed: ["Admin Exams"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.parent.venueChanged,
    category: "exams",
    audience: "parent",
    title: "Exam venue changed",
    message: "{{examName}} · {{subject}}: new venue {{newValue}}.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/exams",
    whereUsed: ["Admin Exams"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.student.venueChanged,
    category: "exams",
    audience: "student",
    title: "Exam venue changed",
    message: "{{examName}} · {{subject}}: new venue {{newValue}}.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/exams",
    whereUsed: ["Admin Exams"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.parent.postponed,
    category: "exams",
    audience: "parent",
    title: "Exam postponed",
    message: "{{examName}} · {{subject}} has been postponed. {{detail}}",
    priority: "critical",
    status: "published",
    version: "1.0.0",
    deepLink: "/exams",
    whereUsed: ["Admin Exams"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.student.postponed,
    category: "exams",
    audience: "student",
    title: "Exam postponed",
    message: "{{examName}} · {{subject}} has been postponed. {{detail}}",
    priority: "critical",
    status: "published",
    version: "1.0.0",
    deepLink: "/exams",
    whereUsed: ["Admin Exams"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.parent.cancelled,
    category: "exams",
    audience: "parent",
    title: "Exam cancelled",
    message: "{{examName}} · {{subject}} has been cancelled. {{detail}}",
    priority: "critical",
    status: "published",
    version: "1.0.0",
    deepLink: "/exams",
    whereUsed: ["Admin Exams"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.student.cancelled,
    category: "exams",
    audience: "student",
    title: "Exam cancelled",
    message: "{{examName}} · {{subject}} has been cancelled. {{detail}}",
    priority: "critical",
    status: "published",
    version: "1.0.0",
    deepLink: "/exams",
    whereUsed: ["Admin Exams"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.teacher.marksEntryDeadline,
    category: "exams",
    audience: "teacher",
    title: "Marks entry due",
    message: "Enter marks for {{examName}} by {{deadline}}.",
    priority: "important",
    status: "published",
    version: "1.1.0",
    deepLink: "/marks",
    whereUsed: ["Admin Marks", "Teacher portal"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.teacher.marksPending,
    category: "exams",
    audience: "teacher",
    title: "Marks entry pending",
    message: "Pending marks entry for {{examName}} · {{subject}} ({{classLabel}}).",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/marks",
    whereUsed: ["Admin Marks"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.teacher.deadlineApproaching,
    category: "exams",
    audience: "teacher",
    title: "Marks deadline approaching",
    message: "{{examName}} marks deadline {{deadline}} is approaching.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/marks",
    whereUsed: ["Admin Marks"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.teacher.marksPublishPending,
    category: "exams",
    audience: "teacher",
    title: "Marks awaiting publish",
    message: "{{examName}} · {{subject}} is submitted and waiting for Admin publish.",
    priority: "normal",
    status: "published",
    version: "1.0.0",
    deepLink: "/marks",
    whereUsed: ["Teacher portal"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.admin.marksPending,
    category: "exams",
    audience: "admin",
    title: "Marks pending",
    message: "{{pendingCount}} teacher(s) still have pending marks for {{examName}}.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/marks",
    whereUsed: ["Admin Marks"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.exams.admin.resultsReady,
    category: "exams",
    audience: "admin",
    title: "Results ready",
    message: "{{examName}} results are ready to publish ({{readyCount}} sheet(s)).",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/marks",
    whereUsed: ["Admin Marks"],
    updatedAt: daysAgo(1),
  }),
];
