import '../models/notification_item.dart';

/// Demo notifications — aligned with transport mock data (1 Jun 2026).
final mockNotifications = <NotificationItem>[
  NotificationItem(
    id: 'NT-01',
    title: 'Admin changed route assignment',
    body: 'Route update: Route 01 stop order revised for Ramesh Kumar on AP16AB1234.',
    type: NotificationType.routeUpdate,
    createdAt: DateTime(2026, 6, 1, 7, 22),
    read: false,
  ),
  NotificationItem(
    id: 'NT-02',
    title: 'Admin changed vehicle assignment',
    body: 'Vehicle changed to AP16AB5678 for Route 01 due to maintenance rotation.',
    type: NotificationType.systemAlert,
    createdAt: DateTime(2026, 6, 1, 8, 10),
    read: false,
  ),
  NotificationItem(
    id: 'NT-03',
    title: 'Attendance variance alert',
    body: 'Attendance alert: Route 01 has 4 unmarked students from the morning trip.',
    type: NotificationType.attendanceAlert,
    createdAt: DateTime(2026, 5, 31, 9, 30),
    read: false,
  ),
  NotificationItem(
    id: 'NT-04',
    title: 'Admin changed trip time',
    body: 'Trip update: Morning pickup start moved from 6:45 AM to 6:55 AM on Route 01.',
    type: NotificationType.tripUpdate,
    createdAt: DateTime(2026, 6, 1, 6, 55),
    read: false,
  ),
  NotificationItem(
    id: 'NT-05',
    title: 'Admin changed assigned students',
    body: 'Students update: 2 new students added to Route 01 at Lake View stop.',
    type: NotificationType.systemAlert,
    createdAt: DateTime(2026, 5, 31, 7, 42),
    read: true,
  ),
  NotificationItem(
    id: 'NT-06',
    title: 'Trip completed confirmation',
    body: 'Trip update: Afternoon drop for Route 01 marked completed at 3:45 PM.',
    type: NotificationType.tripUpdate,
    createdAt: DateTime(2026, 5, 31, 15, 45),
    read: true,
  ),
  NotificationItem(
    id: 'NT-07',
    title: 'Attendance submission reminder',
    body: 'Attendance alert: Please submit final attendance before trip close.',
    type: NotificationType.attendanceAlert,
    createdAt: DateTime(2026, 5, 29, 17, 0),
    read: true,
  ),
  NotificationItem(
    id: 'NT-08',
    title: 'Route map version updated',
    body: 'System alert: Route 01 map updated by admin with revised turn sequence.',
    type: NotificationType.systemAlert,
    createdAt: DateTime(2026, 5, 31, 16, 0),
    read: true,
  ),
  NotificationItem(
    id: 'NT-09',
    title: 'Trip delayed by traffic',
    body: 'Trip update: Route 01 delayed by 8 minutes near RTC Complex.',
    type: NotificationType.tripUpdate,
    createdAt: DateTime(2026, 5, 30, 11, 0),
    read: true,
  ),
  NotificationItem(
    id: 'NT-10',
    title: 'Admin changed route timing',
    body: 'Route update: Housing Board pickup shifted to 7:52 AM from 7:55 AM.',
    type: NotificationType.routeUpdate,
    createdAt: DateTime(2026, 5, 30, 14, 20),
    read: true,
  ),
  NotificationItem(
    id: 'NT-11',
    title: 'Incomplete attendance submission',
    body: 'Route 01 morning attendance not submitted by 8:00 AM on 31 May.',
    type: NotificationType.attendanceAlert,
    createdAt: DateTime(2026, 5, 31, 8, 15),
    read: false,
  ),
  NotificationItem(
    id: 'NT-12',
    title: 'System maintenance notice',
    body: 'System alert: Notification service maintenance window at 11:30 PM.',
    type: NotificationType.systemAlert,
    createdAt: DateTime(2026, 5, 28, 10, 0),
    read: true,
  ),
];
