import type { SportsCalendarEvent } from "./types";

/** Supplemental mock events — training plans & holidays (Screen 16 not in repo). */
export const supplementalCalendarEvents: SportsCalendarEvent[] = [
  {
    id: "tp-1",
    title: "Pre-season Conditioning Block",
    date: "2026-03-11",
    startTime: "06:30",
    endTime: "08:00",
    category: "training_plan",
    sportType: "football",
    teamId: "team-football",
    teamName: "Senior Football Team",
    coach: "Rahul Menon",
    venue: "Main Football Ground",
    description: "Week 2 — aerobic base and agility drills.",
    sourceModule: "training-plans",
    sourceId: "plan-football-preseason",
  },
  {
    id: "tp-2",
    title: "Swimming Endurance Plan — Session 4",
    date: "2026-03-13",
    startTime: "07:00",
    endTime: "08:30",
    category: "training_plan",
    sportType: "swimming",
    teamId: "team-swimming",
    teamName: "Swimming Team",
    coach: "Meera Iyer",
    venue: "Olympic Swimming Pool",
    description: "400m freestyle progression set.",
    sourceModule: "training-plans",
    sourceId: "plan-swim-endurance",
  },
  {
    id: "tp-3",
    title: "Basketball Strength & Conditioning",
    date: "2026-03-17",
    startTime: "16:00",
    endTime: "17:30",
    category: "training_plan",
    sportType: "basketball",
    teamId: "team-basketball",
    teamName: "Basketball Team",
    coach: "Ananya Rao",
    venue: "Indoor Sports Hall",
    description: "Lower-body strength and plyometrics.",
    sourceModule: "training-plans",
    sourceId: "plan-basketball-strength",
  },
  {
    id: "hol-1",
    title: "Holi — Institute Holiday",
    date: "2026-03-14",
    category: "holiday",
    description: "No sports sessions or matches scheduled.",
    sourceModule: "institute-calendar",
    sourceId: "hol-holi-2026",
    allDay: true,
  },
  {
    id: "hol-2",
    title: "Sports Department Planning Day",
    date: "2026-03-21",
    category: "holiday",
    description: "Internal planning — no student-facing sports events.",
    sourceModule: "institute-calendar",
    sourceId: "hol-planning-day",
    allDay: true,
  },
];
