import type { DemoComplaint } from "@lumenx/utils";

/** Demo seed — merged with localStorage in loadDemoComplaints(). */
export const DEMO_COMPLAINTS_SEED: DemoComplaint[] = [
  {
    id: "CMP-201",
    title: "Broken HVAC in Block B",
    from: "Prof. Sterling",
    role: "Teacher",
    destination: "principal_admin",
    priority: "High",
    status: "pending",
    time: "2m ago",
    body: "AC unit in classroom 204 has failed for the third day. Affecting exam preparation.",
  },
  {
    id: "CMP-200",
    title: "Bullying incident — Grade 9-B",
    from: "Anonymous Parent",
    role: "Parent",
    destination: "class_teacher",
    priority: "High",
    status: "review",
    time: "1h ago",
    body: "Repeated incidents reported by multiple parents. Evidence attached.",
  },
  {
    id: "CMP-199",
    title: "Cafeteria food quality",
    from: "Student Council",
    role: "Student",
    destination: "principal_admin",
    priority: "Medium",
    status: "pending",
    time: "3h ago",
    body: "Quality has deteriorated over the past week. Petition signed by 80 students.",
  },
  {
    id: "CMP-198",
    title: "Transport delays — Route 7",
    from: "K. Patel (parent)",
    role: "Parent",
    destination: "principal_admin",
    priority: "Medium",
    status: "review",
    time: "Yesterday",
    body: "Bus consistently 25+ minutes late. Children waiting in extreme weather.",
  },
  {
    id: "CMP-197",
    title: "Library access request",
    from: "External Research",
    role: "External",
    destination: "principal_admin",
    priority: "Low",
    status: "resolved",
    time: "2d ago",
    body: "Resolved — access approved through Director's office.",
  },
];
