// ─── Types ────────────────────────────────────────────────────────────────────

export type StudioRequestType = "single" | "multiple" | "package";
export type StudioRequestStatus =
  | "pending"
  | "approved"
  | "rejected"
  | "draft_generated"
  | "published";

export type StudioDocItem = {
  documentKind: string;
  categoryLabel: string;
  quantity: number;
};

export type StudioTimelineEntry = {
  date: string;
  time: string;
  action: string;
  by: string;
  note: string;
};

export type StudioRequest = {
  id: string;
  requestType: StudioRequestType;
  status: StudioRequestStatus;
  urgency: "normal" | "urgent";

  studentName: string;
  studentClass: string;
  studentSection: string;
  studentRollNo: string;
  parentName: string;
  parentPhone: string;

  documents: StudioDocItem[];
  packageId?: string;
  packageName?: string;

  purpose: string;
  purposeDetails: string;
  requestedBy: "student" | "parent" | "staff";

  requestedOn: string;
  requiredBy: string;
  approvedOn?: string;
  generatedOn?: string;
  publishedOn?: string;

  assignedTo: string | null;
  remarks: string;
  rejectionReason?: string;

  timeline: StudioTimelineEntry[];
};

// ─── Demo Data ────────────────────────────────────────────────────────────────

export const STUDIO_REQUESTS: StudioRequest[] = [
  {
    id: "REQ-2025-001",
    requestType: "single",
    status: "approved",
    urgency: "normal",
    studentName: "Aarav Sharma",
    studentClass: "XII",
    studentSection: "A",
    studentRollNo: "2025001",
    parentName: "Ramesh Sharma",
    parentPhone: "+91 98765 43210",
    documents: [{ documentKind: "bonafide", categoryLabel: "Bonafide Certificate", quantity: 1 }],
    purpose: "Passport application",
    purposeDetails: "Needed for minor passport application. Original bonafide certificate required with school seal.",
    requestedBy: "parent",
    requestedOn: "2025-06-10",
    requiredBy: "2025-06-22",
    approvedOn: "2025-06-11",
    assignedTo: "Mrs. Priya Nair",
    remarks: "Parent verified, fee cleared.",
    timeline: [
      { date: "2025-06-10", time: "10:15 AM", action: "Request submitted", by: "Parent (Ramesh Sharma)", note: "Via Connect portal" },
      { date: "2025-06-11", time: "09:00 AM", action: "Request approved", by: "Mrs. Priya Nair", note: "Fee dues checked, cleared" },
    ],
  },
  {
    id: "REQ-2025-002",
    requestType: "single",
    status: "pending",
    urgency: "urgent",
    studentName: "Ananya Patel",
    studentClass: "X",
    studentSection: "B",
    studentRollNo: "2025002",
    parentName: "Suresh Patel",
    parentPhone: "+91 87654 32109",
    documents: [{ documentKind: "transfer", categoryLabel: "Transfer Certificate", quantity: 1 }],
    purpose: "School transfer to Delhi",
    purposeDetails: "Family relocating to Delhi in July. TC needed before board exam result. Urgently required for enrollment in new school.",
    requestedBy: "parent",
    requestedOn: "2025-06-12",
    requiredBy: "2025-06-20",
    assignedTo: null,
    remarks: "",
    timeline: [
      { date: "2025-06-12", time: "02:30 PM", action: "Request submitted", by: "Parent (Suresh Patel)", note: "Via front desk" },
    ],
  },
  {
    id: "REQ-2025-003",
    requestType: "multiple",
    status: "draft_generated",
    urgency: "normal",
    studentName: "Rohan Mehta",
    studentClass: "XI",
    studentSection: "C",
    studentRollNo: "2025003",
    parentName: "Amit Mehta",
    parentPhone: "+91 76543 21098",
    documents: [
      { documentKind: "bonafide", categoryLabel: "Bonafide Certificate", quantity: 2 },
      { documentKind: "marksheet", categoryLabel: "Marksheet", quantity: 1 },
    ],
    purpose: "Engineering college admission",
    purposeDetails: "Rohan is applying to 3 engineering colleges. Each college requires a bonafide and marksheet. Two copies of bonafide requested.",
    requestedBy: "student",
    requestedOn: "2025-06-14",
    requiredBy: "2025-07-05",
    approvedOn: "2025-06-15",
    generatedOn: "2025-06-16",
    assignedTo: "Mr. Vikram Tiwari",
    remarks: "Drafts ready, pending principal review.",
    timeline: [
      { date: "2025-06-14", time: "11:00 AM", action: "Request submitted", by: "Rohan Mehta", note: "Via Connect portal" },
      { date: "2025-06-15", time: "10:00 AM", action: "Request approved", by: "Mr. Vikram Tiwari", note: "All docs validated" },
      { date: "2025-06-16", time: "03:00 PM", action: "Draft generated", by: "System", note: "PDF drafts ready" },
    ],
  },
  {
    id: "REQ-2025-004",
    requestType: "single",
    status: "published",
    urgency: "normal",
    studentName: "Priya Singh",
    studentClass: "IX",
    studentSection: "A",
    studentRollNo: "2025004",
    parentName: "Mohan Singh",
    parentPhone: "+91 65432 10987",
    documents: [{ documentKind: "conduct", categoryLabel: "Conduct Certificate", quantity: 1 }],
    purpose: "NCC enrollment",
    purposeDetails: "Conduct certificate required for NCC battalion enrollment. Must be signed and stamped.",
    requestedBy: "student",
    requestedOn: "2025-06-05",
    requiredBy: "2025-06-15",
    approvedOn: "2025-06-06",
    generatedOn: "2025-06-07",
    publishedOn: "2025-06-08",
    assignedTo: "Mrs. Priya Nair",
    remarks: "Issued and delivered to student.",
    timeline: [
      { date: "2025-06-05", time: "09:30 AM", action: "Request submitted", by: "Priya Singh", note: "Via Connect portal" },
      { date: "2025-06-06", time: "10:00 AM", action: "Request approved", by: "Mrs. Priya Nair", note: "" },
      { date: "2025-06-07", time: "11:00 AM", action: "Draft generated", by: "System", note: "" },
      { date: "2025-06-08", time: "02:00 PM", action: "Published & issued", by: "Mrs. Priya Nair", note: "Hard copy collected by student" },
    ],
  },
  {
    id: "REQ-2025-005",
    requestType: "single",
    status: "rejected",
    urgency: "normal",
    studentName: "Kabir Verma",
    studentClass: "VIII",
    studentSection: "B",
    studentRollNo: "2025005",
    parentName: "Rajesh Verma",
    parentPhone: "+91 54321 09876",
    documents: [{ documentKind: "character", categoryLabel: "Character Certificate", quantity: 1 }],
    purpose: "Scholarship application",
    purposeDetails: "Character certificate required for state merit scholarship application portal.",
    requestedBy: "parent",
    requestedOn: "2025-06-08",
    requiredBy: "2025-06-18",
    assignedTo: "Ms. Sunita Rao",
    remarks: "",
    rejectionReason: "Outstanding fee dues of ₹12,500 for Q1. Please clear dues before requesting documents.",
    timeline: [
      { date: "2025-06-08", time: "01:00 PM", action: "Request submitted", by: "Parent (Rajesh Verma)", note: "" },
      { date: "2025-06-09", time: "10:00 AM", action: "Request rejected", by: "Ms. Sunita Rao", note: "Fee dues pending ₹12,500" },
    ],
  },
  {
    id: "REQ-2025-006",
    requestType: "package",
    status: "approved",
    urgency: "normal",
    studentName: "Diya Iyer",
    studentClass: "XII",
    studentSection: "B",
    studentRollNo: "2025006",
    parentName: "Subramaniam Iyer",
    parentPhone: "+91 43210 98765",
    documents: [
      { documentKind: "transfer", categoryLabel: "Transfer Certificate", quantity: 1 },
      { documentKind: "character", categoryLabel: "Character Certificate", quantity: 1 },
      { documentKind: "migration", categoryLabel: "Migration Certificate", quantity: 1 },
      { documentKind: "marksheet", categoryLabel: "Marksheet (Class X–XII)", quantity: 1 },
    ],
    packageId: "PKG-001",
    packageName: "Class XII School Leaving Bundle",
    purpose: "Leaving school after Class XII",
    purposeDetails: "Complete documentation set required for university admission and school leaving formalities.",
    requestedBy: "parent",
    requestedOn: "2025-06-11",
    requiredBy: "2025-06-30",
    approvedOn: "2025-06-12",
    assignedTo: "Mr. Vikram Tiwari",
    remarks: "Boarding/leaving formalities confirmed.",
    timeline: [
      { date: "2025-06-11", time: "11:00 AM", action: "Package request submitted", by: "Parent (Subramaniam Iyer)", note: "Package: Class XII School Leaving Bundle" },
      { date: "2025-06-12", time: "09:30 AM", action: "Package request approved", by: "Mr. Vikram Tiwari", note: "All 4 documents approved" },
    ],
  },
  {
    id: "REQ-2025-007",
    requestType: "single",
    status: "pending",
    urgency: "normal",
    studentName: "Arjun Nair",
    studentClass: "VII",
    studentSection: "A",
    studentRollNo: "2025007",
    parentName: "Krishnakumar Nair",
    parentPhone: "+91 32109 87654",
    documents: [{ documentKind: "bonafide", categoryLabel: "Bonafide Certificate", quantity: 1 }],
    purpose: "Bank account opening",
    purposeDetails: "Minor savings account at SBI. Bank requires school bonafide for account opening.",
    requestedBy: "parent",
    requestedOn: "2025-06-16",
    requiredBy: "2025-06-25",
    assignedTo: null,
    remarks: "",
    timeline: [
      { date: "2025-06-16", time: "12:00 PM", action: "Request submitted", by: "Parent (Krishnakumar Nair)", note: "Front desk" },
    ],
  },
  {
    id: "REQ-2025-008",
    requestType: "multiple",
    status: "approved",
    urgency: "urgent",
    studentName: "Sneha Gupta",
    studentClass: "XI",
    studentSection: "A",
    studentRollNo: "2025008",
    parentName: "Deepak Gupta",
    parentPhone: "+91 21098 76543",
    documents: [
      { documentKind: "marksheet", categoryLabel: "Marksheet (Class X)", quantity: 1 },
      { documentKind: "bonafide", categoryLabel: "Bonafide Certificate", quantity: 1 },
      { documentKind: "conduct", categoryLabel: "Conduct Certificate", quantity: 1 },
    ],
    purpose: "IIT JEE counseling registration",
    purposeDetails: "JOSAA counseling requires all three documents. Deadline is June 25. Urgent processing required.",
    requestedBy: "student",
    requestedOn: "2025-06-15",
    requiredBy: "2025-06-24",
    approvedOn: "2025-06-15",
    assignedTo: "Mr. Vikram Tiwari",
    remarks: "Expedited approval. Counseling deadline June 25.",
    timeline: [
      { date: "2025-06-15", time: "04:00 PM", action: "Request submitted", by: "Sneha Gupta", note: "Marked urgent — JOSAA counseling" },
      { date: "2025-06-15", time: "05:30 PM", action: "Request approved", by: "Mr. Vikram Tiwari", note: "Expedited due to deadline" },
    ],
  },
  {
    id: "REQ-2025-009",
    requestType: "single",
    status: "pending",
    urgency: "normal",
    studentName: "Vivek Rajan",
    studentClass: "X",
    studentSection: "A",
    studentRollNo: "2025009",
    parentName: "Gopal Rajan",
    parentPhone: "+91 10987 65432",
    documents: [{ documentKind: "custom", categoryLabel: "Sports NOC", quantity: 1 }],
    purpose: "State-level basketball tournament",
    purposeDetails: "No objection certificate from school required for state-level inter-school basketball tournament.",
    requestedBy: "student",
    requestedOn: "2025-06-17",
    requiredBy: "2025-06-28",
    assignedTo: null,
    remarks: "",
    timeline: [
      { date: "2025-06-17", time: "10:00 AM", action: "Request submitted", by: "Vivek Rajan", note: "" },
    ],
  },
  {
    id: "REQ-2025-010",
    requestType: "single",
    status: "published",
    urgency: "normal",
    studentName: "Meera Krishnan",
    studentClass: "VI",
    studentSection: "C",
    studentRollNo: "2025010",
    parentName: "Padma Krishnan",
    parentPhone: "+91 09876 54321",
    documents: [{ documentKind: "bonafide", categoryLabel: "Bonafide Certificate", quantity: 1 }],
    purpose: "Scholarship application",
    purposeDetails: "National Means cum Merit Scholarship (NMMS) application. School bonafide required.",
    requestedBy: "parent",
    requestedOn: "2025-05-28",
    requiredBy: "2025-06-10",
    approvedOn: "2025-05-29",
    generatedOn: "2025-05-30",
    publishedOn: "2025-06-01",
    assignedTo: "Mrs. Priya Nair",
    remarks: "Issued on time. Hard copy given.",
    timeline: [
      { date: "2025-05-28", time: "09:00 AM", action: "Request submitted", by: "Parent (Padma Krishnan)", note: "" },
      { date: "2025-05-29", time: "10:00 AM", action: "Request approved", by: "Mrs. Priya Nair", note: "" },
      { date: "2025-05-30", time: "11:30 AM", action: "Draft generated", by: "System", note: "" },
      { date: "2025-06-01", time: "09:00 AM", action: "Published & issued", by: "Mrs. Priya Nair", note: "" },
    ],
  },
  {
    id: "REQ-2025-011",
    requestType: "single",
    status: "pending",
    urgency: "normal",
    studentName: "Aditya Kumar",
    studentClass: "XI",
    studentSection: "B",
    studentRollNo: "2025011",
    parentName: "Sunil Kumar",
    parentPhone: "+91 98765 12345",
    documents: [{ documentKind: "migration", categoryLabel: "Migration Certificate", quantity: 1 }],
    purpose: "Board migration — CBSE to ISC",
    purposeDetails: "Student switching to ISC board for Class XII. Migration certificate from current board required.",
    requestedBy: "parent",
    requestedOn: "2025-06-18",
    requiredBy: "2025-07-10",
    assignedTo: null,
    remarks: "",
    timeline: [
      { date: "2025-06-18", time: "03:00 PM", action: "Request submitted", by: "Parent (Sunil Kumar)", note: "" },
    ],
  },
  {
    id: "REQ-2025-012",
    requestType: "multiple",
    status: "draft_generated",
    urgency: "normal",
    studentName: "Kavya Sharma",
    studentClass: "IX",
    studentSection: "B",
    studentRollNo: "2025012",
    parentName: "Rakesh Sharma",
    parentPhone: "+91 87654 12345",
    documents: [
      { documentKind: "conduct", categoryLabel: "Conduct Certificate", quantity: 1 },
      { documentKind: "character", categoryLabel: "Character Certificate", quantity: 1 },
    ],
    purpose: "College interview documentation",
    purposeDetails: "Lateral entry college interview requires both conduct and character certificates.",
    requestedBy: "student",
    requestedOn: "2025-06-13",
    requiredBy: "2025-06-22",
    approvedOn: "2025-06-14",
    generatedOn: "2025-06-15",
    assignedTo: "Ms. Sunita Rao",
    remarks: "Awaiting principal signature.",
    timeline: [
      { date: "2025-06-13", time: "01:00 PM", action: "Request submitted", by: "Kavya Sharma", note: "" },
      { date: "2025-06-14", time: "10:00 AM", action: "Request approved", by: "Ms. Sunita Rao", note: "" },
      { date: "2025-06-15", time: "02:00 PM", action: "Draft generated", by: "System", note: "2 PDFs generated" },
    ],
  },
  {
    id: "REQ-2025-013",
    requestType: "package",
    status: "approved",
    urgency: "urgent",
    studentName: "Ishaan Malhotra",
    studentClass: "VIII",
    studentSection: "A",
    studentRollNo: "2025013",
    parentName: "Vikas Malhotra",
    parentPhone: "+91 76543 12345",
    documents: [
      { documentKind: "bonafide", categoryLabel: "Bonafide Certificate", quantity: 1 },
      { documentKind: "character", categoryLabel: "Character Certificate", quantity: 1 },
    ],
    packageId: "PKG-002",
    packageName: "Sports NOC Bundle",
    purpose: "State Games — Kabaddi",
    purposeDetails: "State Games selection — both bonafide and character cert required. Match starts June 27.",
    requestedBy: "student",
    requestedOn: "2025-06-17",
    requiredBy: "2025-06-24",
    approvedOn: "2025-06-17",
    assignedTo: "Mrs. Priya Nair",
    remarks: "Sports achievement — expedited.",
    timeline: [
      { date: "2025-06-17", time: "11:30 AM", action: "Package request submitted", by: "Ishaan Malhotra", note: "Package: Sports NOC Bundle" },
      { date: "2025-06-17", time: "02:00 PM", action: "Package request approved", by: "Mrs. Priya Nair", note: "Expedited for state games" },
    ],
  },
  {
    id: "REQ-2025-014",
    requestType: "single",
    status: "published",
    urgency: "normal",
    studentName: "Tanvi Desai",
    studentClass: "XII",
    studentSection: "C",
    studentRollNo: "2025014",
    parentName: "Hemant Desai",
    parentPhone: "+91 65432 12345",
    documents: [{ documentKind: "marksheet", categoryLabel: "Marksheet (Class XI)", quantity: 1 }],
    purpose: "NEET counseling",
    purposeDetails: "NEET-UG 2025 counseling requires Class XI marksheet to verify Physics, Chemistry, Biology scores.",
    requestedBy: "student",
    requestedOn: "2025-06-03",
    requiredBy: "2025-06-15",
    approvedOn: "2025-06-04",
    generatedOn: "2025-06-05",
    publishedOn: "2025-06-06",
    assignedTo: "Mr. Vikram Tiwari",
    remarks: "Issued and uploaded to NEET portal.",
    timeline: [
      { date: "2025-06-03", time: "10:00 AM", action: "Request submitted", by: "Tanvi Desai", note: "" },
      { date: "2025-06-04", time: "09:30 AM", action: "Request approved", by: "Mr. Vikram Tiwari", note: "" },
      { date: "2025-06-05", time: "11:00 AM", action: "Draft generated", by: "System", note: "" },
      { date: "2025-06-06", time: "10:00 AM", action: "Published & issued", by: "Mr. Vikram Tiwari", note: "NEET portal upload confirmed" },
    ],
  },
  {
    id: "REQ-2025-015",
    requestType: "single",
    status: "pending",
    urgency: "normal",
    studentName: "Rahul Mishra",
    studentClass: "VII",
    studentSection: "B",
    studentRollNo: "2025015",
    parentName: "Dinesh Mishra",
    parentPhone: "+91 54321 12345",
    documents: [{ documentKind: "bonafide", categoryLabel: "Bonafide Certificate", quantity: 1 }],
    purpose: "Railway concession card",
    purposeDetails: "Indian Railway student concession requires current enrollment bonafide.",
    requestedBy: "parent",
    requestedOn: "2025-06-19",
    requiredBy: "2025-06-30",
    assignedTo: null,
    remarks: "",
    timeline: [
      { date: "2025-06-19", time: "09:00 AM", action: "Request submitted", by: "Parent (Dinesh Mishra)", note: "" },
    ],
  },
  {
    id: "REQ-2025-016",
    requestType: "single",
    status: "approved",
    urgency: "normal",
    studentName: "Priya Singh",
    studentClass: "IX",
    studentSection: "A",
    studentRollNo: "2025004",
    parentName: "Mohan Singh",
    parentPhone: "+91 65432 10987",
    documents: [{ documentKind: "marksheet", categoryLabel: "Marksheet (Class VIII)", quantity: 1 }],
    purpose: "Scholarship renewal",
    purposeDetails: "Scholarship renewal requires previous year marksheet. Marks above 85% confirm eligibility.",
    requestedBy: "parent",
    requestedOn: "2025-06-14",
    requiredBy: "2025-06-28",
    approvedOn: "2025-06-15",
    assignedTo: "Ms. Sunita Rao",
    remarks: "",
    timeline: [
      { date: "2025-06-14", time: "10:30 AM", action: "Request submitted", by: "Parent (Mohan Singh)", note: "" },
      { date: "2025-06-15", time: "09:00 AM", action: "Request approved", by: "Ms. Sunita Rao", note: "" },
    ],
  },
  {
    id: "REQ-2025-017",
    requestType: "package",
    status: "draft_generated",
    urgency: "normal",
    studentName: "Ananya Patel",
    studentClass: "X",
    studentSection: "B",
    studentRollNo: "2025002",
    parentName: "Suresh Patel",
    parentPhone: "+91 87654 32109",
    documents: [
      { documentKind: "transfer", categoryLabel: "Transfer Certificate", quantity: 1 },
      { documentKind: "character", categoryLabel: "Character Certificate", quantity: 1 },
      { documentKind: "marksheet", categoryLabel: "Marksheet (Class IX–X)", quantity: 1 },
    ],
    packageId: "PKG-003",
    packageName: "Mid-Year Transfer Bundle",
    purpose: "Mid-year school transfer — Delhi admission",
    purposeDetails: "Full documentation required for mid-year transfer to Delhi school. All 3 documents generated.",
    requestedBy: "parent",
    requestedOn: "2025-06-16",
    requiredBy: "2025-06-25",
    approvedOn: "2025-06-17",
    generatedOn: "2025-06-18",
    assignedTo: "Mr. Vikram Tiwari",
    remarks: "Drafts pending principal sign-off.",
    timeline: [
      { date: "2025-06-16", time: "04:00 PM", action: "Package request submitted", by: "Parent (Suresh Patel)", note: "Package: Mid-Year Transfer Bundle" },
      { date: "2025-06-17", time: "10:00 AM", action: "Package approved", by: "Mr. Vikram Tiwari", note: "" },
      { date: "2025-06-18", time: "03:00 PM", action: "All 3 drafts generated", by: "System", note: "" },
    ],
  },
  {
    id: "REQ-2025-018",
    requestType: "multiple",
    status: "rejected",
    urgency: "normal",
    studentName: "Kabir Verma",
    studentClass: "VIII",
    studentSection: "B",
    studentRollNo: "2025005",
    parentName: "Rajesh Verma",
    parentPhone: "+91 54321 09876",
    documents: [
      { documentKind: "bonafide", categoryLabel: "Bonafide Certificate", quantity: 1 },
      { documentKind: "conduct", categoryLabel: "Conduct Certificate", quantity: 1 },
    ],
    purpose: "Inter-school debate competition NOC",
    purposeDetails: "Zonal competition requires both bonafide and conduct cert to confirm enrollment and good standing.",
    requestedBy: "student",
    requestedOn: "2025-06-09",
    requiredBy: "2025-06-14",
    assignedTo: "Ms. Sunita Rao",
    remarks: "",
    rejectionReason: "Previous fee dues still outstanding. Fee dues must be cleared before any document issuance. Contact accounts dept.",
    timeline: [
      { date: "2025-06-09", time: "11:00 AM", action: "Request submitted", by: "Kabir Verma", note: "" },
      { date: "2025-06-10", time: "10:00 AM", action: "Request rejected", by: "Ms. Sunita Rao", note: "Outstanding fee dues on record" },
    ],
  },
  {
    id: "REQ-2025-019",
    requestType: "single",
    status: "approved",
    urgency: "normal",
    studentName: "Diya Iyer",
    studentClass: "XII",
    studentSection: "B",
    studentRollNo: "2025006",
    parentName: "Subramaniam Iyer",
    parentPhone: "+91 43210 98765",
    documents: [{ documentKind: "migration", categoryLabel: "Migration Certificate", quantity: 1 }],
    purpose: "University migration certificate",
    purposeDetails: "University admission committee requires board-level migration certificate alongside TC.",
    requestedBy: "parent",
    requestedOn: "2025-06-12",
    requiredBy: "2025-06-30",
    approvedOn: "2025-06-13",
    assignedTo: "Mr. Vikram Tiwari",
    remarks: "",
    timeline: [
      { date: "2025-06-12", time: "12:00 PM", action: "Request submitted", by: "Parent (Subramaniam Iyer)", note: "" },
      { date: "2025-06-13", time: "10:00 AM", action: "Request approved", by: "Mr. Vikram Tiwari", note: "" },
    ],
  },
  {
    id: "REQ-2025-020",
    requestType: "single",
    status: "published",
    urgency: "normal",
    studentName: "Rohan Mehta",
    studentClass: "XI",
    studentSection: "C",
    studentRollNo: "2025003",
    parentName: "Amit Mehta",
    parentPhone: "+91 76543 21098",
    documents: [{ documentKind: "marksheet", categoryLabel: "Marksheet (Class X)", quantity: 1 }],
    purpose: "Career counseling center",
    purposeDetails: "Submitted to career counseling center for stream selection assessment.",
    requestedBy: "student",
    requestedOn: "2025-05-30",
    requiredBy: "2025-06-08",
    approvedOn: "2025-05-31",
    generatedOn: "2025-06-01",
    publishedOn: "2025-06-03",
    assignedTo: "Mr. Vikram Tiwari",
    remarks: "Issued. Career center notified.",
    timeline: [
      { date: "2025-05-30", time: "10:00 AM", action: "Request submitted", by: "Rohan Mehta", note: "" },
      { date: "2025-05-31", time: "09:00 AM", action: "Request approved", by: "Mr. Vikram Tiwari", note: "" },
      { date: "2025-06-01", time: "11:00 AM", action: "Draft generated", by: "System", note: "" },
      { date: "2025-06-03", time: "10:00 AM", action: "Published & issued", by: "Mr. Vikram Tiwari", note: "" },
    ],
  },
  {
    id: "REQ-2025-021",
    requestType: "single",
    status: "pending",
    urgency: "urgent",
    studentName: "Sneha Gupta",
    studentClass: "XI",
    studentSection: "A",
    studentRollNo: "2025008",
    parentName: "Deepak Gupta",
    parentPhone: "+91 21098 76543",
    documents: [{ documentKind: "bonafide", categoryLabel: "Bonafide Certificate", quantity: 1 }],
    purpose: "Emergency bank loan for family",
    purposeDetails: "Parent needs school bonafide urgently to process education loan. Bank deadline is tomorrow.",
    requestedBy: "parent",
    requestedOn: "2025-06-19",
    requiredBy: "2025-06-20",
    assignedTo: null,
    remarks: "",
    timeline: [
      { date: "2025-06-19", time: "08:30 AM", action: "Request submitted", by: "Parent (Deepak Gupta)", note: "Urgent — bank loan deadline tomorrow" },
    ],
  },
  {
    id: "REQ-2025-022",
    requestType: "multiple",
    status: "pending",
    urgency: "urgent",
    studentName: "Aditya Kumar",
    studentClass: "XI",
    studentSection: "B",
    studentRollNo: "2025011",
    parentName: "Sunil Kumar",
    parentPhone: "+91 98765 12345",
    documents: [
      { documentKind: "transfer", categoryLabel: "Transfer Certificate", quantity: 1 },
      { documentKind: "migration", categoryLabel: "Migration Certificate", quantity: 1 },
    ],
    purpose: "Full school transfer — ISC board",
    purposeDetails: "Aditya is moving to an ISC school. Both TC and migration cert required. New school enrollment closes June 25.",
    requestedBy: "parent",
    requestedOn: "2025-06-18",
    requiredBy: "2025-06-24",
    assignedTo: null,
    remarks: "",
    timeline: [
      { date: "2025-06-18", time: "02:00 PM", action: "Request submitted", by: "Parent (Sunil Kumar)", note: "Urgent — ISC school enrollment closes June 25" },
    ],
  },
  {
    id: "REQ-2025-023",
    requestType: "package",
    status: "approved",
    urgency: "normal",
    studentName: "Kavya Sharma",
    studentClass: "IX",
    studentSection: "B",
    studentRollNo: "2025012",
    parentName: "Rakesh Sharma",
    parentPhone: "+91 87654 12345",
    documents: [
      { documentKind: "bonafide", categoryLabel: "Bonafide Certificate", quantity: 1 },
      { documentKind: "marksheet", categoryLabel: "Marksheet (Class VIII)", quantity: 1 },
      { documentKind: "character", categoryLabel: "Character Certificate", quantity: 1 },
    ],
    packageId: "PKG-004",
    packageName: "State Merit Scholarship Kit",
    purpose: "State merit scholarship application",
    purposeDetails: "KVS scholarship requires all 3 documents. Kavya has 91% average — strong candidate.",
    requestedBy: "parent",
    requestedOn: "2025-06-15",
    requiredBy: "2025-06-28",
    approvedOn: "2025-06-16",
    assignedTo: "Mrs. Priya Nair",
    remarks: "Scholarship candidate — priority handling.",
    timeline: [
      { date: "2025-06-15", time: "10:00 AM", action: "Package request submitted", by: "Parent (Rakesh Sharma)", note: "Package: State Merit Scholarship Kit" },
      { date: "2025-06-16", time: "09:00 AM", action: "Package approved", by: "Mrs. Priya Nair", note: "Priority — scholarship deadline" },
    ],
  },
  {
    id: "REQ-2025-024",
    requestType: "single",
    status: "draft_generated",
    urgency: "normal",
    studentName: "Tanvi Desai",
    studentClass: "XII",
    studentSection: "C",
    studentRollNo: "2025014",
    parentName: "Hemant Desai",
    parentPhone: "+91 65432 12345",
    documents: [{ documentKind: "conduct", categoryLabel: "Conduct Certificate", quantity: 1 }],
    purpose: "Hostel admission — Manipal University",
    purposeDetails: "Manipal hostel admission requires conduct certificate from previous school.",
    requestedBy: "student",
    requestedOn: "2025-06-14",
    requiredBy: "2025-06-25",
    approvedOn: "2025-06-15",
    generatedOn: "2025-06-16",
    assignedTo: "Mrs. Priya Nair",
    remarks: "Draft ready. Pending signature.",
    timeline: [
      { date: "2025-06-14", time: "03:00 PM", action: "Request submitted", by: "Tanvi Desai", note: "" },
      { date: "2025-06-15", time: "10:00 AM", action: "Request approved", by: "Mrs. Priya Nair", note: "" },
      { date: "2025-06-16", time: "11:00 AM", action: "Draft generated", by: "System", note: "PDF ready for signature" },
    ],
  },
  {
    id: "REQ-2025-025",
    requestType: "multiple",
    status: "published",
    urgency: "normal",
    studentName: "Arjun Nair",
    studentClass: "VII",
    studentSection: "A",
    studentRollNo: "2025007",
    parentName: "Krishnakumar Nair",
    parentPhone: "+91 32109 87654",
    documents: [
      { documentKind: "conduct", categoryLabel: "Conduct Certificate", quantity: 1 },
      { documentKind: "bonafide", categoryLabel: "Bonafide Certificate", quantity: 1 },
    ],
    purpose: "Summer camp enrollment",
    purposeDetails: "IIT Bombay summer camp requires both conduct and bonafide for enrollment of participating students.",
    requestedBy: "parent",
    requestedOn: "2025-05-25",
    requiredBy: "2025-06-05",
    approvedOn: "2025-05-26",
    generatedOn: "2025-05-27",
    publishedOn: "2025-05-28",
    assignedTo: "Ms. Sunita Rao",
    remarks: "Issued. Camp enrollment confirmed.",
    timeline: [
      { date: "2025-05-25", time: "09:00 AM", action: "Request submitted", by: "Parent (Krishnakumar Nair)", note: "" },
      { date: "2025-05-26", time: "10:00 AM", action: "Request approved", by: "Ms. Sunita Rao", note: "" },
      { date: "2025-05-27", time: "11:00 AM", action: "Drafts generated", by: "System", note: "2 PDFs" },
      { date: "2025-05-28", time: "09:30 AM", action: "Published & issued", by: "Ms. Sunita Rao", note: "Both docs collected" },
    ],
  },
];
