import type { SportsActivity, SportsActivityInput } from "./activities-types";
import { defaultNotificationPrefs } from "./activities-notifications";
import { addDays, isoDate } from "@/activity-workspace/hub/calendar";

const today = new Date();

export function cloneSportsActivity(a: SportsActivity): SportsActivity {
  return {
    ...a,
    attachments: a.attachments.map((x) => ({ ...x })),
    coordinators: { ...a.coordinators },
    notifications: { ...a.notifications },
    linkedTeamIds: [...a.linkedTeamIds],
  };
}

export function createActivityFromInput(input: SportsActivityInput, id?: string): SportsActivity {
  const now = isoDate(new Date());
  return {
    id: id ?? `sact-${Date.now()}`,
    title: input.title.trim(),
    activityType: input.activityType,
    sportType: input.sportType,
    description: input.description.trim(),
    venue: input.venue.trim(),
    date: input.date,
    startTime: input.startTime,
    endTime: input.endTime,
    status: "draft",
    audience: input.audience,
    attachments: input.attachments.map((x) => ({ ...x })),
    coordinators: { ...input.coordinators },
    linkedTeamIds: input.linkedTeamIds ?? [],
    notifications: input.notifications ?? defaultNotificationPrefs(),
    createdAt: now,
    updatedAt: now,
  };
}

export const sportsActivitiesSeed: SportsActivity[] = [
  {
    id: "sact-1",
    title: "Football Practice — Morning Drills",
    activityType: "practice",
    sportType: "football",
    description: "Warm-up, passing drills, and small-sided games for the senior squad.",
    venue: "Main Ground",
    date: isoDate(today),
    startTime: "07:00",
    endTime: "08:30",
    status: "in_progress",
    audience: { type: "teams", teamIds: ["team-football"], teamLabels: ["Senior Football Team"] },
    attachments: [
      {
        id: "att-1",
        name: "Drill-plan.pdf",
        kind: "document",
        sizeLabel: "240 KB",
        uploadedAt: "2026-03-01",
      },
    ],
    coordinators: {
      sportsCoordinator: "Ananya Iyer",
      coach: "Rahul Menon",
      assistantCoach: "Karthik Naidu",
    },
    linkedTeamIds: ["team-football"],
    notifications: { notifyAudience: true, notifyParents: false, notifyTeachers: true },
    publishedAt: "2026-03-08",
    createdAt: "2026-03-01",
    updatedAt: isoDate(today),
  },
  {
    id: "sact-2",
    title: "Basketball Match — Inter-House League",
    activityType: "match",
    sportType: "basketball",
    description: "Emerald House vs Sapphire House — semi-final league fixture.",
    venue: "Indoor Court A",
    date: isoDate(today),
    startTime: "10:30",
    endTime: "12:00",
    status: "scheduled",
    audience: { type: "teams", teamIds: ["team-basketball"], teamLabels: ["Basketball Team"] },
    attachments: [],
    coordinators: { sportsCoordinator: "Ananya Iyer", coach: "Ananya Iyer" },
    linkedTeamIds: ["team-basketball"],
    notifications: { notifyAudience: true, notifyParents: true, notifyTeachers: false },
    publishedAt: "2026-03-05",
    createdAt: "2026-03-02",
    updatedAt: "2026-03-10",
  },
  {
    id: "sact-3",
    title: "Cricket Net Practice",
    activityType: "practice",
    sportType: "cricket",
    description: "Batting and bowling nets ahead of the district championship.",
    venue: "Cricket Nets",
    date: isoDate(today),
    startTime: "14:00",
    endTime: "16:00",
    status: "scheduled",
    audience: { type: "teams", teamIds: ["team-cricket"], teamLabels: ["Cricket Team"] },
    attachments: [
      {
        id: "att-2",
        name: "Net-rotation.pdf",
        kind: "schedule",
        sizeLabel: "128 KB",
        uploadedAt: "2026-03-09",
      },
    ],
    coordinators: {
      sportsCoordinator: "Suresh Kumar",
      coach: "Suresh Kumar",
      assistantCoach: "Manoj Pillai",
    },
    linkedTeamIds: ["team-cricket"],
    notifications: { notifyAudience: true, notifyParents: false, notifyTeachers: true },
    publishedAt: "2026-03-09",
    createdAt: "2026-03-03",
    updatedAt: "2026-03-09",
  },
  {
    id: "sact-4",
    title: "Badminton Selection Trials",
    activityType: "trial",
    sportType: "badminton",
    description: "Trials for Class 9–10 badminton squad selection.",
    venue: "Court 2",
    date: isoDate(addDays(today, 1)),
    startTime: "15:00",
    endTime: "17:00",
    status: "scheduled",
    audience: {
      type: "sections",
      sections: [
        { className: "9", section: "A" },
        { className: "9", section: "B" },
        { className: "10", section: "A" },
      ],
    },
    attachments: [],
    coordinators: { sportsCoordinator: "Pooja Desai", coach: "Pooja Desai" },
    linkedTeamIds: ["team-badminton"],
    notifications: { notifyAudience: true, notifyParents: true, notifyTeachers: true },
    publishedAt: "2026-03-07",
    createdAt: "2026-03-04",
    updatedAt: "2026-03-07",
  },
  {
    id: "sact-5",
    title: "Athletics Sprint Training",
    activityType: "training",
    sportType: "athletics",
    description: "100m and 200m sprint intervals with timing gates.",
    venue: "Athletics Track",
    date: isoDate(addDays(today, 2)),
    startTime: "06:30",
    endTime: "08:00",
    status: "draft",
    audience: { type: "teams", teamIds: ["team-athletics"], teamLabels: ["Athletics Squad"] },
    attachments: [],
    coordinators: { sportsCoordinator: "Deepa Nambiar", coach: "Deepa Nambiar" },
    linkedTeamIds: ["team-athletics"],
    notifications: defaultNotificationPrefs(),
    createdAt: "2026-03-06",
    updatedAt: "2026-03-06",
  },
  {
    id: "sact-6",
    title: "Chess Coaching Session",
    activityType: "coaching",
    sportType: "chess",
    description: "Opening theory and rapid-game practice for inter-school prep.",
    venue: "Library Hall",
    date: isoDate(addDays(today, 3)),
    startTime: "16:00",
    endTime: "17:30",
    status: "scheduled",
    audience: { type: "classes", classNames: ["9", "10"] },
    attachments: [
      {
        id: "att-3",
        name: "Opening-repertoire.pdf",
        kind: "rules",
        sizeLabel: "512 KB",
        uploadedAt: "2026-03-01",
      },
    ],
    coordinators: { sportsCoordinator: "Vivek Sharma", coach: "Vivek Sharma" },
    linkedTeamIds: ["team-chess"],
    notifications: { notifyAudience: true, notifyParents: false, notifyTeachers: false },
    publishedAt: "2026-03-02",
    createdAt: "2026-02-28",
    updatedAt: "2026-03-02",
  },
  {
    id: "sact-7",
    title: "Sports Day — Track Events",
    activityType: "event",
    sportType: "athletics",
    description: "Annual sports day track and field programme for the entire institute.",
    venue: "Main Stadium",
    date: isoDate(addDays(today, 14)),
    startTime: "08:00",
    endTime: "16:00",
    status: "scheduled",
    audience: { type: "entire_institute" },
    attachments: [
      {
        id: "att-4",
        name: "Sports-day-schedule.pdf",
        kind: "schedule",
        sizeLabel: "1.2 MB",
        uploadedAt: "2026-02-20",
      },
      {
        id: "att-5",
        name: "Event-rules.pdf",
        kind: "rules",
        sizeLabel: "340 KB",
        uploadedAt: "2026-02-20",
      },
    ],
    coordinators: {
      sportsCoordinator: "Ananya Iyer",
      coach: "Deepa Nambiar",
      assistantCoach: "Rahul Menon",
    },
    linkedTeamIds: ["team-athletics", "team-football"],
    notifications: { notifyAudience: true, notifyParents: true, notifyTeachers: true },
    publishedAt: "2026-02-25",
    createdAt: "2026-02-20",
    updatedAt: "2026-03-01",
  },
  {
    id: "sact-8",
    title: "Volleyball Friendly — Cancelled",
    activityType: "match",
    sportType: "volleyball",
    description: "Friendly fixture cancelled due to venue maintenance.",
    venue: "Indoor Court B",
    date: isoDate(addDays(today, -2)),
    startTime: "15:00",
    endTime: "16:30",
    status: "cancelled",
    audience: { type: "teams", teamIds: ["team-volleyball"], teamLabels: ["Volleyball Team"] },
    attachments: [],
    coordinators: { sportsCoordinator: "Lakshmi Reddy", coach: "Lakshmi Reddy" },
    linkedTeamIds: ["team-volleyball"],
    notifications: { notifyAudience: true, notifyParents: true, notifyTeachers: true },
    publishedAt: "2026-02-10",
    createdAt: "2026-02-05",
    updatedAt: "2026-03-04",
  },
  {
    id: "sact-9",
    title: "Swimming Technique Session (2024–25)",
    activityType: "session",
    sportType: "swimming",
    description: "Archived session from previous academic year — retained for records.",
    venue: "Aquatic Centre",
    date: "2025-03-15",
    startTime: "07:00",
    endTime: "08:30",
    status: "archived",
    audience: { type: "teams", teamIds: ["team-swimming-legacy"], teamLabels: ["Swimming Team (2024–25)"] },
    attachments: [],
    coordinators: { sportsCoordinator: "Neha Kulkarni", coach: "Neha Kulkarni" },
    linkedTeamIds: ["team-swimming-legacy"],
    notifications: { notifyAudience: true, notifyParents: false, notifyTeachers: false },
    publishedAt: "2025-03-01",
    archivedAt: "2025-04-15",
    createdAt: "2025-02-20",
    updatedAt: "2025-04-15",
  },
  {
    id: "sact-10",
    title: "Kabaddi Conditioning",
    activityType: "practice",
    sportType: "kabaddi",
    description: "Strength and raid practice for invitational tournament squad.",
    venue: "Indoor Arena",
    date: isoDate(addDays(today, 5)),
    startTime: "17:00",
    endTime: "18:30",
    status: "draft",
    audience: {
      type: "individual_students",
      studentIds: ["stu-11", "stu-12", "stu-13", "stu-14"],
    },
    attachments: [],
    coordinators: { sportsCoordinator: "Harish Pillai", coach: "Harish Pillai" },
    linkedTeamIds: ["team-kabaddi"],
    notifications: defaultNotificationPrefs(),
    createdAt: isoDate(today),
    updatedAt: isoDate(today),
  },
];
