import type { PracticeSession, PracticeSessionInput } from "./practice-sessions-types";
import { defaultPracticeNotificationPrefs } from "./practice-sessions-notifications";
import { addDays, isoDate } from "@/activity-workspace/hub/calendar";

const today = new Date();

export function clonePracticeSession(s: PracticeSession): PracticeSession {
  return {
    ...s,
    notifications: { ...s.notifications },
  };
}

export function createPracticeSessionFromInput(
  input: PracticeSessionInput,
  meta: { activityTitle: string; teamName: string },
  id?: string,
): PracticeSession {
  const now = isoDate(new Date());
  return {
    id: id ?? `psess-${Date.now()}`,
    title: input.title.trim(),
    sportsActivityId: input.sportsActivityId,
    sportsActivityTitle: meta.activityTitle,
    teamId: input.teamId,
    teamName: meta.teamName,
    coach: input.coach.trim(),
    assistantCoach: input.assistantCoach?.trim() || undefined,
    venue: input.venue.trim(),
    date: input.date,
    startTime: input.startTime,
    endTime: input.endTime,
    objectives: input.objectives.trim(),
    equipmentRequired: input.equipmentRequired.trim(),
    notes: input.notes.trim(),
    status: "scheduled",
    notifications: input.notifications ?? defaultPracticeNotificationPrefs(),
    createdAt: now,
    updatedAt: now,
  };
}

export const practiceSessionsSeed: PracticeSession[] = [
  {
    id: "psess-1",
    title: "Passing & Movement Drills",
    sportsActivityId: "sact-1",
    sportsActivityTitle: "Football Practice — Morning Drills",
    teamId: "team-football",
    teamName: "Senior Football Team",
    coach: "Rahul Menon",
    assistantCoach: "Karthik Naidu",
    venue: "Main Ground",
    date: isoDate(today),
    startTime: "07:00",
    endTime: "08:00",
    objectives: "Improve short passing accuracy and off-the-ball movement in a 4-4-2 shape.",
    equipmentRequired: "Cones (20), bibs (16), footballs (12)",
    notes: "Focus on weak-foot passing in the second half of the session.",
    status: "in_progress",
    notifications: { notifyAudience: true, notifyParents: false, notifyTeachers: true },
    createdAt: "2026-03-05",
    updatedAt: isoDate(today),
  },
  {
    id: "psess-2",
    title: "Small-Sided Games Block",
    sportsActivityId: "sact-1",
    sportsActivityTitle: "Football Practice — Morning Drills",
    teamId: "team-football",
    teamName: "Senior Football Team",
    coach: "Rahul Menon",
    venue: "Main Ground",
    date: isoDate(today),
    startTime: "08:00",
    endTime: "08:30",
    objectives: "Apply passing patterns under match pressure in 7v7 games.",
    equipmentRequired: "Portable goals (2), bibs, footballs",
    notes: "Rotate goalkeepers every 5 minutes.",
    status: "scheduled",
    notifications: { notifyAudience: true, notifyParents: false, notifyTeachers: true },
    createdAt: "2026-03-06",
    updatedAt: "2026-03-08",
  },
  {
    id: "psess-3",
    title: "Batting Nets — Top Order",
    sportsActivityId: "sact-3",
    sportsActivityTitle: "Cricket Net Practice",
    teamId: "team-cricket",
    teamName: "Cricket Team",
    coach: "Suresh Kumar",
    assistantCoach: "Manoj Pillai",
    venue: "Cricket Nets",
    date: isoDate(today),
    startTime: "14:00",
    endTime: "15:00",
    objectives: "Front-foot drives and leave balls outside off stump.",
    equipmentRequired: "Bats, helmets, balls, side-arm feeder",
    notes: "Video review after session for top 4 batters.",
    status: "scheduled",
    notifications: { notifyAudience: true, notifyParents: true, notifyTeachers: true },
    createdAt: "2026-03-07",
    updatedAt: "2026-03-09",
  },
  {
    id: "psess-4",
    title: "Bowling Accuracy Block",
    sportsActivityId: "sact-3",
    sportsActivityTitle: "Cricket Net Practice",
    teamId: "team-cricket",
    teamName: "Cricket Team",
    coach: "Manoj Pillai",
    venue: "Cricket Nets",
    date: isoDate(today),
    startTime: "15:00",
    endTime: "16:00",
    objectives: "Line-and-length drills for pace and spin bowlers.",
    equipmentRequired: "Stumps, cones, balls",
    notes: "",
    status: "scheduled",
    notifications: { notifyAudience: true, notifyParents: false, notifyTeachers: true },
    createdAt: "2026-03-07",
    updatedAt: "2026-03-09",
  },
  {
    id: "psess-5",
    title: "Sprint Intervals — 100m",
    sportsActivityId: "sact-5",
    sportsActivityTitle: "Athletics Sprint Training",
    teamId: "team-athletics",
    teamName: "Athletics Squad",
    coach: "Deepa Nambiar",
    venue: "Athletics Track",
    date: isoDate(addDays(today, 2)),
    startTime: "06:30",
    endTime: "07:30",
    objectives: "6 × 100m intervals with 90s recovery — target sub-13s.",
    equipmentRequired: "Starting blocks, timing gates, cones",
    notes: "Hydration break at 07:00.",
    status: "scheduled",
    notifications: defaultPracticeNotificationPrefs(),
    createdAt: "2026-03-06",
    updatedAt: "2026-03-06",
  },
  {
    id: "psess-6",
    title: "Raid & Defence Drills",
    sportsActivityId: "sact-10",
    sportsActivityTitle: "Kabaddi Conditioning",
    teamId: "team-kabaddi",
    teamName: "Kabaddi Team",
    coach: "Harish Pillai",
    venue: "Indoor Arena",
    date: isoDate(addDays(today, 5)),
    startTime: "17:00",
    endTime: "18:00",
    objectives: "Chain tackles and bonus-line raids.",
    equipmentRequired: "Mats, agility ladder",
    notes: "Invite-only squad of 8 players.",
    status: "scheduled",
    notifications: { notifyAudience: true, notifyParents: false, notifyTeachers: false },
    createdAt: isoDate(today),
    updatedAt: isoDate(today),
  },
  {
    id: "psess-7",
    title: "Recovery Session (Cancelled)",
    sportsActivityId: "sact-8",
    sportsActivityTitle: "Volleyball Friendly — Cancelled",
    teamId: "team-volleyball",
    teamName: "Volleyball Team",
    coach: "Lakshmi Reddy",
    venue: "Indoor Court B",
    date: isoDate(addDays(today, -2)),
    startTime: "15:00",
    endTime: "16:00",
    objectives: "Light serve-and-receive practice.",
    equipmentRequired: "Volleyballs, net",
    notes: "Cancelled with parent activity.",
    status: "cancelled",
    notifications: { notifyAudience: true, notifyParents: true, notifyTeachers: true },
    createdAt: "2026-02-08",
    updatedAt: "2026-03-04",
  },
];
