/** Tax / commercial invoice PDF for subscription renewals (no payment gateway). */

import { renderTextPdf } from "../documents/render-pdf.js";

export type InvoicePdfInput = {
  invoiceNumber: string;
  instituteName: string;
  instituteId: string;
  status: string;
  periodStartsAt: string;
  periodEndsAt: string;
  dueAt: string | null;
  issuedAt: string | null;
  activeStudentCount: number;
  assignedRateInr: number;
  regularAmountInr: number;
  discountAmountInr: number;
  payableAmountInr: number;
  amountPaidInr: number;
  notes?: string | null;
};

function formatInr(n: number): string {
  return `INR ${Math.round(n).toLocaleString("en-IN")}`;
}

function formatDate(iso: string | null): string {
  if (!iso) return "—";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toISOString().slice(0, 10);
}

export function renderInvoicePdf(input: InvoicePdfInput): Uint8Array {
  const balance = Math.max(0, Math.round(input.payableAmountInr - input.amountPaidInr));
  const lines = [
    "LumenX — Subscription Invoice",
    "",
    `Invoice: ${input.invoiceNumber}`,
    `Status: ${input.status}`,
    `Issued: ${formatDate(input.issuedAt)}`,
    `Due: ${formatDate(input.dueAt)}`,
    "",
    `Bill to: ${input.instituteName}`,
    `Institute ID: ${input.instituteId}`,
    "",
    `Billing period: ${formatDate(input.periodStartsAt)} to ${formatDate(input.periodEndsAt)}`,
    `Active students: ${input.activeStudentCount.toLocaleString("en-IN")}`,
    `Assigned rate: ${formatInr(input.assignedRateInr)} / student / month`,
    "",
    `Regular amount: ${formatInr(input.regularAmountInr)}`,
    `Discount: ${formatInr(input.discountAmountInr)}`,
    `Payable: ${formatInr(input.payableAmountInr)}`,
    `Amount paid: ${formatInr(input.amountPaidInr)}`,
    `Balance due: ${formatInr(balance)}`,
    "",
    "Payment: offline / bank transfer only (no online gateway).",
    "Pay using the invoice number as payment reference.",
  ];
  if (input.notes?.trim()) {
    lines.push("", `Notes: ${input.notes.trim()}`);
  }
  lines.push("", "Generated by LumenX Nexus billing.");
  return renderTextPdf(lines);
}
