import type { EquipmentItem, EquipmentItemInput, EquipmentSupplier } from "./types";

export const equipmentSuppliersSeed: EquipmentSupplier[] = [
  {
    id: "sup-1",
    name: "SportZone India",
    contactPerson: "Rajesh Kumar",
    phone: "+91 98765 43210",
    email: "orders@sportzone.demo",
  },
  {
    id: "sup-2",
    name: "ProGear Athletics",
    contactPerson: "Meera Shah",
    phone: "+91 91234 56789",
    email: "sales@progear.demo",
  },
  {
    id: "sup-3",
    name: "FieldMaster Supplies",
    contactPerson: "Vikram Nair",
    email: "supply@fieldmaster.demo",
  },
];

export function cloneEquipmentItem(item: EquipmentItem): EquipmentItem {
  return { ...item };
}

export function createEquipmentFromInput(input: EquipmentItemInput, id?: string): EquipmentItem {
  const now = new Date().toISOString().slice(0, 10);
  const qty = Math.max(0, input.quantity);
  return {
    id: id ?? `eq-${Date.now()}`,
    name: input.name.trim(),
    categoryId: input.categoryId,
    quantity: qty,
    available: qty,
    issued: 0,
    damaged: 0,
    lost: 0,
    inMaintenance: 0,
    condition: input.condition,
    purchaseDate: input.purchaseDate,
    cost: input.cost,
    vendor: input.vendor.trim(),
    supplierId: input.supplierId,
    status: "active",
    notes: input.notes?.trim(),
    createdAt: now,
    updatedAt: now,
  };
}

export const equipmentSeed: EquipmentItem[] = [
  {
    id: "eq-1",
    name: "Football — Size 5 (Match)",
    categoryId: "balls",
    quantity: 24,
    available: 18,
    issued: 4,
    damaged: 1,
    lost: 0,
    inMaintenance: 1,
    condition: "good",
    purchaseDate: "2025-08-12",
    cost: 14400,
    vendor: "SportZone India",
    supplierId: "sup-1",
    status: "active",
    createdAt: "2025-08-12",
    updatedAt: "2026-03-01",
  },
  {
    id: "eq-2",
    name: "Cricket Bat — English Willow",
    categoryId: "training",
    quantity: 15,
    available: 10,
    issued: 3,
    damaged: 2,
    lost: 0,
    inMaintenance: 0,
    condition: "fair",
    purchaseDate: "2025-06-20",
    cost: 67500,
    vendor: "ProGear Athletics",
    supplierId: "sup-2",
    status: "active",
    createdAt: "2025-06-20",
    updatedAt: "2026-02-15",
  },
  {
    id: "eq-3",
    name: "Shin Guards — Youth",
    categoryId: "protective_gear",
    quantity: 40,
    available: 32,
    issued: 8,
    damaged: 0,
    lost: 0,
    inMaintenance: 0,
    condition: "good",
    purchaseDate: "2025-09-01",
    cost: 12000,
    vendor: "SportZone India",
    supplierId: "sup-1",
    status: "active",
    createdAt: "2025-09-01",
    updatedAt: "2026-03-05",
  },
  {
    id: "eq-4",
    name: "Portable Football Goals",
    categoryId: "field_equipment",
    quantity: 4,
    available: 2,
    issued: 2,
    damaged: 0,
    lost: 0,
    inMaintenance: 0,
    condition: "good",
    purchaseDate: "2024-11-10",
    cost: 48000,
    vendor: "FieldMaster Supplies",
    supplierId: "sup-3",
    status: "active",
    createdAt: "2024-11-10",
    updatedAt: "2026-01-20",
  },
  {
    id: "eq-5",
    name: "Volleyball — Official",
    categoryId: "balls",
    quantity: 12,
    available: 8,
    issued: 2,
    damaged: 1,
    lost: 1,
    inMaintenance: 0,
    condition: "fair",
    purchaseDate: "2025-07-15",
    cost: 9600,
    vendor: "ProGear Athletics",
    supplierId: "sup-2",
    status: "active",
    createdAt: "2025-07-15",
    updatedAt: "2026-02-28",
  },
  {
    id: "eq-6",
    name: "Agility Ladder Set",
    categoryId: "fitness",
    quantity: 6,
    available: 4,
    issued: 1,
    damaged: 0,
    lost: 0,
    inMaintenance: 1,
    condition: "under_maintenance",
    purchaseDate: "2025-10-05",
    cost: 7200,
    vendor: "SportZone India",
    supplierId: "sup-1",
    status: "active",
    createdAt: "2025-10-05",
    updatedAt: "2026-03-08",
  },
  {
    id: "eq-7",
    name: "Sports Jersey — Home Kit",
    categoryId: "uniforms",
    quantity: 50,
    available: 12,
    issued: 36,
    damaged: 2,
    lost: 0,
    inMaintenance: 0,
    condition: "good",
    purchaseDate: "2025-08-01",
    cost: 75000,
    vendor: "ProGear Athletics",
    supplierId: "sup-2",
    status: "active",
    createdAt: "2025-08-01",
    updatedAt: "2026-03-06",
  },
  {
    id: "eq-8",
    name: "Training Cones (Set of 50)",
    categoryId: "training",
    quantity: 10,
    available: 3,
    issued: 5,
    damaged: 1,
    lost: 1,
    inMaintenance: 0,
    condition: "fair",
    purchaseDate: "2024-12-01",
    cost: 5000,
    vendor: "FieldMaster Supplies",
    supplierId: "sup-3",
    status: "active",
    createdAt: "2024-12-01",
    updatedAt: "2026-02-10",
  },
];
