import type { SetupStepDef } from "./types";

/** Ordered setup steps — done is computed from API counts, not manual ticks. */
export const SETUP_STEPS: SetupStepDef[] = [
  {
    id: "academic_year",
    kind: "core",
    title: "Academic year",
    description:
      "Create the current academic year (first year activates automatically).",
    href: "/academic-management",
    search: { view: "years" },
    requires: [],
  },
  {
    id: "classes",
    kind: "core",
    title: "Classes",
    description: "Add at least one class for the active year.",
    href: "/classes",
    requires: ["academic_year"],
  },
  {
    id: "sections",
    kind: "core",
    title: "Sections",
    description: "Add sections under each class (needed before students).",
    href: "/classes",
    requires: ["classes"],
  },
  {
    id: "subjects",
    kind: "core",
    title: "Subjects",
    description: "Create subjects used for timetable, diary, and marks.",
    href: "/subjects",
    requires: ["sections"],
  },
  {
    id: "teachers",
    kind: "core",
    title: "Teachers",
    description: "Onboard teachers and link Connect logins where possible.",
    href: "/teachers",
    requires: ["subjects"],
  },
  {
    id: "students",
    kind: "core",
    title: "Students",
    description:
      "Add students after class + section exist (enrollment requires both).",
    href: "/students",
    requires: ["academic_year", "classes", "sections"],
  },
  {
    id: "parents",
    kind: "core",
    title: "Parents",
    description:
      "Parents are created with each student; link any remaining guardians here.",
    href: "/parents",
    requires: ["students"],
  },
  {
    id: "attendance_config",
    kind: "extended",
    title: "Attendance rules",
    description: "Configure student attendance so teachers can mark registers.",
    href: "/academic-management",
    search: { view: "settings" },
    requires: ["sections", "teachers"],
  },
  {
    id: "fees",
    kind: "extended",
    title: "Fee plan",
    description: "Create and publish at least one fee plan.",
    href: "/fees",
    requires: ["academic_year", "classes"],
  },
  {
    id: "calendar",
    kind: "extended",
    title: "Academic calendar",
    description: "Add holidays or school events.",
    href: "/calendar",
    requires: ["academic_year"],
  },
  {
    id: "transport_fleet",
    kind: "extended",
    title: "Transport fleet",
    description: "Add vehicles and drivers for bus operations.",
    href: "/transport",
    search: { view: "vehicles" },
    requires: [],
  },
  {
    id: "transport_routes",
    kind: "extended",
    title: "Transport routes",
    description: "Create or approve at least one route.",
    href: "/transport",
    search: { view: "routes" },
    requires: ["transport_fleet"],
  },
  {
    id: "transport_enrollments",
    kind: "extended",
    title: "Transport enrollments",
    description: "Assign students to routes and approve enrollments.",
    href: "/transport",
    search: { view: "students" },
    requires: ["transport_routes", "students"],
  },
];
