import type { SportsVenue, SportsVenueInput } from "./types";

export function cloneVenue(v: SportsVenue): SportsVenue {
  return { ...v, equipmentAvailable: [...v.equipmentAvailable] };
}

export function createVenueFromInput(input: SportsVenueInput, id?: string): SportsVenue {
  const now = new Date().toISOString().slice(0, 10);
  return {
    id: id ?? `venue-${Date.now()}`,
    name: input.name.trim(),
    venueType: input.venueType,
    location: input.location.trim(),
    capacity: Math.max(1, input.capacity),
    status: "available",
    equipmentAvailable: [...input.equipmentAvailable],
    maintenanceNotes: input.maintenanceNotes?.trim(),
    description: input.description.trim(),
    createdAt: now,
    updatedAt: now,
  };
}

export const venuesSeed: SportsVenue[] = [
  {
    id: "venue-1",
    name: "Main Football Ground",
    venueType: "outdoor_ground",
    location: "East Campus",
    capacity: 500,
    status: "available",
    equipmentAvailable: ["Portable goals (2)", "Corner flags", "Scoreboard"],
    description: "Full-size grass pitch with floodlights for evening matches.",
    createdAt: "2024-08-01",
    updatedAt: "2026-03-01",
  },
  {
    id: "venue-2",
    name: "Indoor Sports Hall",
    venueType: "indoor",
    location: "Block B — Ground Floor",
    capacity: 200,
    status: "available",
    equipmentAvailable: ["Basketball hoops", "Badminton nets", "Mats"],
    description: "Multi-purpose indoor hall for basketball, badminton, and assemblies.",
    createdAt: "2024-08-01",
    updatedAt: "2026-02-20",
  },
  {
    id: "venue-3",
    name: "Olympic Swimming Pool",
    venueType: "swimming_pool",
    location: "Aquatics Centre",
    capacity: 80,
    status: "available",
    equipmentAvailable: ["Lane ropes", "Starting blocks", "Rescue equipment"],
    description: "25m × 8-lane heated pool with timing system.",
    createdAt: "2024-09-15",
    updatedAt: "2026-03-05",
  },
  {
    id: "venue-4",
    name: "Cricket Practice Nets",
    venueType: "court",
    location: "West Wing",
    capacity: 24,
    status: "available",
    equipmentAvailable: ["Bowling machine", "Stumps", "Bats (loaner)"],
    description: "Four synthetic turf practice nets.",
    createdAt: "2024-10-01",
    updatedAt: "2026-01-15",
  },
  {
    id: "venue-5",
    name: "Synthetic Athletics Track",
    venueType: "track",
    location: "Stadium Complex",
    capacity: 300,
    status: "maintenance",
    equipmentAvailable: ["Hurdles", "Starting blocks", "Javelin cage"],
    maintenanceNotes: "Resurfacing lane 3–4 until 15 Mar 2026",
    description: "400m standard synthetic track with field event pits.",
    createdAt: "2024-06-01",
    updatedAt: "2026-03-08",
  },
  {
    id: "venue-6",
    name: "Basketball Court A",
    venueType: "court",
    location: "Outdoor Courts — North",
    capacity: 50,
    status: "available",
    equipmentAvailable: ["Balls", "Scoreboard", "Benches"],
    description: "Full-size outdoor basketball court.",
    createdAt: "2025-01-10",
    updatedAt: "2026-02-28",
  },
  {
    id: "venue-7",
    name: "Central Auditorium",
    venueType: "auditorium",
    location: "Admin Block",
    capacity: 800,
    status: "available",
    equipmentAvailable: ["PA system", "Projector", "Stage lighting"],
    description: "Air-conditioned auditorium for ceremonies and indoor events.",
    createdAt: "2024-01-01",
    updatedAt: "2026-03-02",
  },
  {
    id: "venue-8",
    name: "Volleyball Court",
    venueType: "court",
    location: "Indoor Sports Hall — Court 2",
    capacity: 40,
    status: "available",
    equipmentAvailable: ["Net system", "Volleyballs", "Referee stand"],
    description: "Standard indoor volleyball court with sprung floor.",
    createdAt: "2025-03-01",
    updatedAt: "2026-03-06",
  },
];
