import type { ActivityDashboardSnapshot } from "./types";
import { addDays, formatDisplayDate, isoDate } from "@/activity-workspace/hub/calendar";

const today = new Date();

export const activityDashboardSnapshot: ActivityDashboardSnapshot = {
  stats: {
    todayActivities: 5,
    thisWeekEvents: 8,
    activeClubs: 12,
    pendingAttendance: 2,
    openCompetitions: 3,
    workshopSessions: 4,
    unreadMessages: 6,
    certificatesIssued: 28,
  },
  todayActivities: [
    {
      id: "ta-1",
      title: "Inter-House Basketball — Quarter Finals",
      category: "sports",
      venue: "Main Sports Complex",
      time: "08:30 AM",
      participantCount: 48,
      status: "completed",
    },
    {
      id: "ta-2",
      title: "Science Club — Robotics Workshop",
      category: "clubs",
      venue: "Innovation Lab, Block C",
      time: "10:00 AM",
      participantCount: 24,
      status: "ongoing",
    },
    {
      id: "ta-3",
      title: "Annual Day Rehearsal — Dance Troupe",
      category: "events",
      venue: "Auditorium",
      time: "02:00 PM",
      participantCount: 36,
      status: "upcoming",
    },
    {
      id: "ta-4",
      title: "Table Tennis Selection Trials",
      category: "competitions",
      venue: "Indoor Games Hall",
      time: "03:30 PM",
      participantCount: 18,
      status: "upcoming",
    },
    {
      id: "ta-5",
      title: "Leadership Workshop — Student Council",
      category: "workshops",
      venue: "Seminar Hall 2",
      time: "04:45 PM",
      participantCount: 22,
      status: "upcoming",
    },
  ],
  upcomingEvents: [
    {
      id: "ev-1",
      title: "Founder's Day Cultural Evening",
      date: formatDisplayDate(addDays(today, 2)),
      time: "05:30 PM",
      venue: "Open Air Amphitheatre",
      audience: "Entire Institute",
    },
    {
      id: "ev-2",
      title: "Parent–Coach Sports Meet",
      date: formatDisplayDate(addDays(today, 4)),
      time: "09:00 AM",
      venue: "Athletics Track",
      audience: "Classes 8–12",
    },
    {
      id: "ev-3",
      title: "Eco Club Tree Plantation Drive",
      date: formatDisplayDate(addDays(today, 6)),
      time: "07:30 AM",
      venue: "Campus Green Belt",
      audience: "Eco Club Members",
    },
  ],
  upcomingCompetitions: [
    {
      id: "cmp-1",
      title: "District Inter-School Cricket",
      sport: "Cricket",
      date: formatDisplayDate(addDays(today, 3)),
      teamsRegistered: 14,
      maxTeams: 16,
    },
    {
      id: "cmp-2",
      title: "State Level Chess Championship",
      sport: "Chess",
      date: formatDisplayDate(addDays(today, 7)),
      teamsRegistered: 8,
      maxTeams: 12,
    },
    {
      id: "cmp-3",
      title: "Inter-House Athletics Meet",
      sport: "Athletics",
      date: formatDisplayDate(addDays(today, 10)),
      teamsRegistered: 4,
      maxTeams: 4,
    },
  ],
  calendarMarks: [
    { date: isoDate(today), count: 5, highlight: true },
    { date: isoDate(addDays(today, 1)), count: 2 },
    { date: isoDate(addDays(today, 2)), count: 3 },
    { date: isoDate(addDays(today, 4)), count: 1 },
    { date: isoDate(addDays(today, 6)), count: 2 },
    { date: isoDate(addDays(today, 7)), count: 4 },
    { date: isoDate(addDays(today, 10)), count: 6 },
    { date: isoDate(addDays(today, 14)), count: 1 },
  ],
  notifications: [
    {
      id: "n-1",
      title: "Basketball quarter-final results posted",
      body: "Emerald House advances to the semi-finals. Certificates will be issued tomorrow.",
      category: "result",
      timeAgo: "12 min ago",
      unread: true,
    },
    {
      id: "n-2",
      title: "24 students registered for Robotics Workshop",
      body: "Class 9–10 slots are nearly full. Consider opening a waitlist.",
      category: "registration",
      timeAgo: "1 hr ago",
      unread: true,
    },
    {
      id: "n-3",
      title: "Annual Day rehearsal reminder",
      body: "Dance troupe must report to the auditorium by 1:45 PM with costumes.",
      category: "reminder",
      timeAgo: "3 hrs ago",
      unread: true,
    },
    {
      id: "n-4",
      title: "Transport delay for away cricket match",
      body: "Bus departs at 6:15 AM instead of 6:00 AM on Thursday.",
      category: "urgent",
      timeAgo: "Yesterday",
      unread: false,
    },
  ],
  timeline: [
    {
      id: "tl-1",
      action: "Attendance marked",
      detail: "Science Club — Robotics Workshop (22 present)",
      timeAgo: "25 min ago",
      category: "attendance",
    },
    {
      id: "tl-2",
      action: "Competition bracket updated",
      detail: "Inter-House Basketball — Semi-final pairings published",
      timeAgo: "1 hr ago",
      category: "competitions",
    },
    {
      id: "tl-3",
      action: "Event audience confirmed",
      detail: "Founder's Day — 840 recipients across Classes 6–12",
      timeAgo: "2 hrs ago",
      category: "events",
    },
    {
      id: "tl-4",
      action: "Certificates generated",
      detail: "District Swimming Meet — 18 participation certificates",
      timeAgo: "Yesterday",
      category: "certificates",
    },
    {
      id: "tl-5",
      action: "Workshop materials uploaded",
      detail: "Leadership Workshop — facilitator slides attached",
      timeAgo: "Yesterday",
      category: "workshops",
    },
  ],
  participationSummary: {
    totalParticipants: 412,
    weekOverWeekChange: 8.4,
    byCategory: [
      { category: "sports", count: 156, label: "Sports" },
      { category: "clubs", count: 98, label: "Clubs" },
      { category: "events", count: 74, label: "Events" },
      { category: "workshops", count: 42, label: "Workshops" },
      { category: "competitions", count: 42, label: "Competitions" },
    ],
  },
};
