import type { RegisteredNotificationTemplate } from "../shared/registry/types";
import { NOTIFICATION_TEMPLATE_IDS as IDS } from "../shared/registry/ids";
import { extractAllowedVariables } from "../shared/registry/variables";
import { DEFAULT_DEEP_LINK } from "../shared/registry/legacy-map";

function daysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

function tpl(
  partial: Omit<RegisteredNotificationTemplate, "allowedVariables" | "deepLink"> & {
    allowedVariables?: readonly string[];
    deepLink?: string;
  },
): RegisteredNotificationTemplate {
  return {
    ...partial,
    allowedVariables:
      partial.allowedVariables ?? extractAllowedVariables(partial.title, partial.message),
    deepLink: partial.deepLink ?? DEFAULT_DEEP_LINK[partial.category],
  };
}

export const TRANSPORT_TEMPLATES: RegisteredNotificationTemplate[] = [
  tpl({
    templateId: IDS.transport.teacher.routeConfirmed,
    category: "transport",
    audience: "teacher",
    title: "Morning route confirmed",
    message: "{{routeName}} is scheduled to depart at {{departureTime}} from {{originStop}}.",
    priority: "normal",
    status: "published",
    version: "1.5.0",
    description: "Confirm transport route assignment to staff.",
    whereUsed: ["Transport app", "Admin Transport"],
    updatedAt: daysAgo(15),
  }),
  tpl({
    templateId: IDS.transport.teacher.studentPickupUpdated,
    category: "transport",
    audience: "teacher",
    title: "Student pickup updated",
    message: "{{studentName}} will board from {{stopName}} today.",
    priority: "normal",
    status: "published",
    version: "1.5.0",
    whereUsed: ["Transport app", "Admin Transport"],
    updatedAt: daysAgo(15),
  }),
  tpl({
    templateId: IDS.transport.teacher.routeDelayReminder,
    category: "transport",
    audience: "teacher",
    title: "Route delay reminder",
    message: "Allow extra travel time near {{location}} due to planned road work.",
    priority: "important",
    status: "published",
    version: "1.5.0",
    whereUsed: ["Transport app"],
    updatedAt: daysAgo(15),
  }),
  tpl({
    templateId: IDS.transport.teacher.schoolTimingNotice,
    category: "transport",
    audience: "teacher",
    title: "School timing notice",
    message: "{{message}}",
    priority: "important",
    status: "published",
    version: "1.5.0",
    whereUsed: ["Transport app"],
    updatedAt: daysAgo(15),
  }),
  tpl({
    templateId: IDS.transport.teacher.busInspectionComplete,
    category: "transport",
    audience: "teacher",
    title: "Bus inspection complete",
    message: "{{message}}",
    priority: "success",
    status: "published",
    version: "1.5.0",
    whereUsed: ["Transport app"],
    updatedAt: daysAgo(15),
  }),
  tpl({
    templateId: IDS.transport.teacher.driverBriefing,
    category: "transport",
    audience: "teacher",
    title: "Driver briefing",
    message: "The monthly transport briefing is scheduled for {{day}} at {{time}}.",
    priority: "normal",
    status: "published",
    version: "1.5.0",
    whereUsed: ["Transport app"],
    updatedAt: daysAgo(15),
  }),
  tpl({
    templateId: IDS.transport.parent.delay,
    category: "transport",
    audience: "parent",
    title: "Bus delayed",
    message: "Route {{routeName}} is delayed by ~{{minutes}} minutes.",
    priority: "important",
    status: "published",
    version: "1.2.1",
    description: "Inform parents of route delays.",
    whereUsed: ["Transport", "Connect parent"],
    updatedAt: daysAgo(9),
  }),
  tpl({
    templateId: IDS.transport.parent.tripStarted,
    category: "transport",
    audience: "parent",
    title: "Trip started",
    message: "{{busNumber}} is on route {{routeCode}} with {{driverName}}.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/transport",
    whereUsed: ["Transport notification bridge", "Connect"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.transport.parent.approach30,
    category: "transport",
    audience: "parent",
    title: "Bus approaching in 30 minutes",
    message:
      "{{studentName}}: stop {{stopName}} · ETA {{eta}} · {{vehicleNumber}} ({{busStatus}}) · {{routeCode}}.",
    priority: "normal",
    status: "published",
    version: "1.0.0",
    deepLink: "/transport",
    whereUsed: ["Transport notification bridge", "Connect"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.transport.parent.approach15,
    category: "transport",
    audience: "parent",
    title: "Bus approaching in 15 minutes",
    message:
      "{{studentName}}: stop {{stopName}} · ETA {{eta}} · {{vehicleNumber}} ({{busStatus}}) · {{routeCode}}.",
    priority: "normal",
    status: "published",
    version: "1.0.0",
    deepLink: "/transport",
    whereUsed: ["Transport notification bridge", "Connect"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.transport.parent.approach5,
    category: "transport",
    audience: "parent",
    title: "Bus approaching in 5 minutes",
    message:
      "{{studentName}}: stop {{stopName}} · ETA {{eta}} · {{vehicleNumber}} ({{busStatus}}) · {{routeCode}}.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/transport",
    whereUsed: ["Transport notification bridge", "Connect"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.transport.parent.studentBoarded,
    category: "transport",
    audience: "parent",
    title: "Student boarded",
    message: "{{studentName}} boarded at {{stopName}} on {{vehicleNumber}}.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/transport",
    whereUsed: ["Transport attendance bridge", "Connect"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.transport.parent.studentNotBoarded,
    category: "transport",
    audience: "parent",
    title: "Student not boarded",
    message: "{{studentName}} was marked not boarded at {{stopName}} ({{vehicleNumber}}).",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/transport",
    whereUsed: ["Transport attendance bridge", "Connect"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.transport.parent.reachedSchool,
    category: "transport",
    audience: "parent",
    title: "Reached school",
    message: "{{busNumber}} reached school on {{routeCode}}.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/transport",
    whereUsed: ["Transport trip store", "Connect"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.transport.parent.boardingStarted,
    category: "transport",
    audience: "parent",
    title: "Boarding started",
    message: "{{busNumber}} started boarding attendance on {{routeCode}}.",
    priority: "normal",
    status: "published",
    version: "1.0.0",
    deepLink: "/transport",
    whereUsed: ["Transport trip store", "Connect"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.transport.parent.studentDropped,
    category: "transport",
    audience: "parent",
    title: "Child dropped successfully",
    message: "{{studentName}} was dropped at {{stopName}} ({{vehicleNumber}}).",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/transport",
    whereUsed: ["Transport attendance bridge", "Connect"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.transport.parent.emergencySos,
    category: "transport",
    audience: "parent",
    title: "Emergency on your bus",
    message: "{{vehicleNumber}} · {{routeCode}} · {{driverName}}.",
    priority: "critical",
    status: "published",
    version: "1.0.0",
    deepLink: "/transport",
    whereUsed: ["Transport emergency", "Connect"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.transport.parent.emergencyBreakdown,
    category: "transport",
    audience: "parent",
    title: "Bus breakdown",
    message: "{{vehicleNumber}} · {{routeCode}} · {{driverName}}.",
    priority: "critical",
    status: "published",
    version: "1.0.0",
    deepLink: "/transport",
    whereUsed: ["Transport emergency", "Connect"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.transport.parent.emergencyDelay,
    category: "transport",
    audience: "parent",
    title: "Major bus delay",
    message: "{{vehicleNumber}} · {{routeCode}} · {{driverName}}.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/transport",
    whereUsed: ["Transport emergency", "Connect"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.transport.parent.emergencyRouteIssue,
    category: "transport",
    audience: "parent",
    title: "Route issue on your bus",
    message: "{{vehicleNumber}} · {{routeCode}} · {{driverName}}.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/transport",
    whereUsed: ["Transport emergency", "Connect"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.transport.admin.tripStarted,
    category: "transport",
    audience: "admin",
    title: "Trip started",
    message: "{{driverName}} started {{busNumber}} on {{routeCode}}.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/transport?view=attendance",
    whereUsed: ["Transport notification bridge", "Admin"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.transport.admin.attendancePending,
    category: "transport",
    audience: "admin",
    title: "Transport attendance not submitted",
    message:
      "{{driverName}} · {{busNumber}} · {{routeCode}}: {{pendingCount}} student marks still pending.",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/transport?view=attendance",
    whereUsed: ["Transport trip end", "Admin"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.transport.admin.emergencySos,
    category: "transport",
    audience: "admin",
    title: "SOS raised",
    message: "{{driverName}} · {{vehicleNumber}} · {{routeCode}}",
    priority: "critical",
    status: "published",
    version: "1.0.0",
    deepLink: "/transport?view=emergencies",
    whereUsed: ["Transport emergency", "Admin"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.transport.admin.emergencyBreakdown,
    category: "transport",
    audience: "admin",
    title: "Bus breakdown",
    message: "{{driverName}} · {{vehicleNumber}} · {{routeCode}}",
    priority: "critical",
    status: "published",
    version: "1.0.0",
    deepLink: "/transport?view=emergencies",
    whereUsed: ["Transport emergency", "Admin"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.transport.admin.emergencyDelay,
    category: "transport",
    audience: "admin",
    title: "Major delay",
    message: "{{driverName}} · {{vehicleNumber}} · {{routeCode}}",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/transport?view=emergencies",
    whereUsed: ["Transport emergency", "Admin"],
    updatedAt: daysAgo(1),
  }),
  tpl({
    templateId: IDS.transport.admin.emergencyRouteIssue,
    category: "transport",
    audience: "admin",
    title: "Route issue",
    message: "{{driverName}} · {{vehicleNumber}} · {{routeCode}}",
    priority: "important",
    status: "published",
    version: "1.0.0",
    deepLink: "/transport?view=emergencies",
    whereUsed: ["Transport emergency", "Admin"],
    updatedAt: daysAgo(1),
  }),
];
